### ISSUE TITLE
Pre-commit integration issue

### ISSUE THREAD

**Issue by sfdye** [ambv/black#117]
I couldn't install this version and seems `pre-commit` integration is broken because of it.

**Comment by sfdye** [comment]
@ambv

**Comment by ambv** [comment]
No, as the README states, this version is not released yet. As a workaround for the time being, please point your config at the "master" rev, not at "stable".

**Comment by sfdye** [comment]
Got it thanks @ambv any ETA for the stable release?

**Comment by sfdye** [comment]
Pointing to `master` seems to work now.

When I do `git commit` after I installed the hook, this is what I got. Code is reformatted, however I have to run a subsequent `git commit` again to stage the change. Is this the expected behaviour or am I missing something?

```
[WARNING] Unstaged files detected.
[INFO] Stashing unstaged files to /Users/liuyang/.cache/pre-commit/patch1523327524.
black....................................................................Failed
hookid: black

Files were modified by this hook. Additional output:

reformatted test.py

[INFO] Restored changes from /Users/liuyang/.cache/pre-commit/patch152332752
```

**Comment by sfdye** [comment]
This is a pre-commit's defined behaviour.

**Comment by robertlagrant** [comment]
@sfdye It looks more as though Black is causing the pre-commit behaviour, by reformatting and `exit(1)`ing instead of reformatting and `exit(0)`ing.
