### ISSUE TITLE
Cannot parse complex dict/list expansion

### ISSUE THREAD

**Issue by touilleMan** [ambv/black#122]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Ubuntu 16.04
Python version: 3.6.5
Black version: 18.4a0 and master
Does also happen on master: Yes

It seems black fail parsing file containing dict/list expansion combined with if/else structure:
```
(venv) ➜  black git:(master) ✗ cat dict_expansion.py 
print(**{} if True else {})
(venv) ➜  black git:(master) ✗ cat list_exansion.py 
print(*[] if True else [])
(venv) ➜  black git:(master) ✗ python dict_expansion.py 

(venv) ➜  black git:(master) ✗ python list_exansion.py 

(venv) ➜  black git:(master) ✗ python -m black dict_expansion.py 
error: cannot format dict_expansion.py: Cannot parse: 1:6: print(**{} if True else {})
(venv) ➜  black git:(master) ✗ python -m black list_exansion.py 
error: cannot format list_exansion.py: Cannot parse: 1:10: print(*[] if True else [])
```

However if parenthesis are added before the expansion (e.g. `print(**({} if True else {}))`) black works fine.

And btw thanks for this awesome tool, I've got already [two](https://github.com/touilleMan/godot-python) [projects](https://github.com/scille/parsec-cloud) converted to it ;-)

**Comment by zsol** [comment]
Nice, thanks for reporting! This looks like the same issue as #2. Glad you're enjoying black :)
