### ISSUE TITLE
Can't parse `return (i * 2 async for i in arange(n))`

### ISSUE THREAD

**Issue by ambv** [ambv/black#125]
Title says all.

**Comment by zsol** [comment]
I can't reproduce this on master anymore with this file:
```
> cat test.py
async def f():
    return (i * 2 async for i in arange(42))
> python black.py test.py
test.py already well formatted, good job.
```

In fact I can't repro this with `18.4a0` either.

**Comment by ambv** [comment]
Your example should be a synchronous def:
```
def make_arange(n):
    # This syntax is legal starting with Python 3.7
    return (i * 2 async for i in arange(n))
```

(note: not an `async def`)

This is perfectly valid in 3.7+ as you are only *producing* an async gen. You are not consuming it.
