### ISSUE TITLE
Wrapping imports is incompatible with isort

### ISSUE THREAD

**Issue by shivawu** [ambv/black#127]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Mac OS X 10.13.4
Python version: 3.6.5
Black version: 18.4a1
Does also happen on master: Yes

For example,
```
from django.http import HttpResponse, HttpResponseBadRequest, JsonResponse, HttpResponse, HttpRequest
```

would be formatted as

```
from django.http import (
    HttpResponse, HttpResponseBadRequest, JsonResponse, HttpResponse, HttpRequest
)
```

This is probably personal, but this looks a little bit weird. I would suggest this as a better formatting:
```
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseBadRequest,
    JsonResponse,
)
```

**Comment by shivawu** [comment]
To add a bit of context, I'm trying to make black work with isort. But it seems that black's formatting style is not among isort's list of multi-line output modes (https://github.com/timothycrosley/isort#multi-line-output-modes).

This creates a problem. When I save my python file, it's formatted with black, but isort (flake8-isort) would complain about incorrectly formatted imports, which basically put my code in a bad state.

**Comment by carljm** [comment]
This is also going to be a problem for Instagram adoption of Black.

**Comment by ambv** [comment]
This form of wrapping lines applies to all code in Black. Making an exception for imports alone is inconsistent, especially if motivated purely by another, optional tool for Black users.

I'm [talking to](https://twitter.com/llanga/status/984669545993420800?s=21) @timothycrosley about introducing "multiline mode 8" in isort which would enable both tools to peacefully co-exist. I hope this works, if not, we'll think of other options.

**Comment by djm** [comment]
Yeah, we do this form of wrapping everywhere too, especially in function/method signatures. If we need to drop at all, we drop one item per line. I can understand if it can't be supported though, it's going to be impossible to please everyone while keeping the no configuration thing.

**Comment by ambv** [comment]
Reported on the isort end as https://github.com/timothycrosley/isort/issues/694.

**Comment by ambv** [comment]
Due to Timothy's silence on the isort end I decided to change how we're formatting imports to be compatible with his valuable tool.

**Comment by monkut** [comment]
hmmm.. hit this issue where `black` wants a comma, but `isort` does not...

**Comment by monkut** [comment]
Added the following to the `.isort.cfg`:

```
[settings]
multi_line_output=3
include_trailing_comma=True
```

**Comment by monkut** [comment]
Having an issue with this again for some reason:

_.isort.cfg_
```
[settings]
multi_line_output=3
include_trailing_comma=True
force_grid_wrap=0
use_parentheses=True
line_length=150
```

_black formatted imports_
```
from controllers.models import (
    ControllerCamera,
    ControllerWorkspaceExport,
    KController,
)
```

_isort formatted imports_
```
from controllers.models import ControllerCamera, ControllerWorkspaceExport, KController
```

**Comment by alexey-v-paramonov** [comment]
I also had to add 
`line_length=88
`
cause isort has a max line length of 79 vs 88 in black

**Comment by BwL1289** [comment]
has anyone seen this issue pop up again?

**Comment by tardunge** [comment]
im good with these.
[settings]
multi_line_output=3
include_trailing_comma=True
line_length=88
