### ISSUE TITLE
Plugin installation via Vim plugin managers (Vundle, etc.)

### ISSUE THREAD

**Issue by skgbanga** [ambv/black#129]
It would be nice to have `black` vim plugin installed via popular vim package managers e.g. Vundle.

**Comment by anowlcalledjosh** [comment]
I've not done this before, but I'd be really interested to give it a go!

**Comment by JackLeo** [comment]
As long as it's a valid repo structure it will be installed. Example http://learnvimscriptthehardway.stevelosh.com/chapters/43.html

so to make it work, you should split it into a new repository.

**Comment by ambv** [comment]
Yeah, let's make a separate repo.

**Comment by alejandrodnm** [comment]
You can install it with Vundle like this
```
Plugin 'ambv/black', {'rtp': 'vim'}
```
From the vundle help

The 'rtp' option
----------------

Specifies a directory inside the repository (relative path from the root of
the repository) where the vim plugin resides. It determines the path that will
be added to the |runtimepath|.

For example:
>  Plugin 'git_URI', {'rtp': 'some/subdir/'}

This can be used with git repositories that put the vim plugin inside a
subdirectory.
