### ISSUE TITLE
--diff doesn't display full file path

### ISSUE THREAD

**Issue by anowlcalledjosh** [ambv/black#130]
Operating system: Ubuntu 16.04.4
Python version: 3.6.3
Black version: 18.4a2
Does also happen on master: I believe so

Doing `black --diff path/to/foo.py` results in:

```diff
--- foo.py  (original)
+++ foo.py  (formatted)
@@ -39,24 +39,21 @@
...
```

caused by the following two lines:

https://github.com/ambv/black/blob/f294cc272c3aa5b8d3cd35b9f9283721b7e458d8/black.py#L298-L299

IMO, Black should print the full path to each file it formats in `--diff` output to be consistent with the behaviour of other diff-producing programs. Not printing the full path also makes it hard to read several concatenated diffs (especially when filenames are duplicated in different directories).

**Comment by ambv** [comment]
Agreed. I didn't think this through when I was implementing that. A full path is clearly important for validity of the diff if multiple paths were given.

**Comment by ambv** [comment]
Is it fine that we're using the `(original)` and `(formatted)` conventions? Git is using `a/` and `b/` prepended to the path but I find this less readable.

**Comment by ambv** [comment]
Yeah, I guess if I put "original" and "formatted" *before* the path then the user can use `patch -p1`.
