### ISSUE TITLE
Failure to reformat a lamba expression

### ISSUE THREAD

**Issue by emonty** [ambv/black#133]
Operating system: Ubuntu Bionic
Python version: 3.6.5
Black version: 18.4a2
Does also happen on master: yes (or, rather, with 18.4a2, but that's the latest commit on master)

I hit an error with black formatting https://github.com/openstack/python-openstackclient/blob/30b2203dc75a4fc776875b02258f8d54660249d7/openstackclient/tests/unit/compute/v2/test_server.py

The black log is
[blk_4urz_4d8.log](https://github.com/ambv/black/files/1912566/blk_4urz_4d8.log)

I isolated it down to the following as a reproduction case:

```
foo = (lambda port_id, ignore_missing:
       {"port1": port1_resource,
        "port2": port2_resource}[port_id])
```

It seems to be line-length + lambda related. If I change the code to 

```
foo = (lambda port_id, ignore_missing:
       {"a1": a1_resource,
        "a2": a2_resource}[port_id])
```

it works.

**Comment by ambv** [comment]
Thanks for your report, will fix in the next release.
