### ISSUE TITLE
SublimeText integration

### ISSUE THREAD

**Issue by jgirardet** [ambv/black#135]
Hello,

I started a plugin for SublimeText 3 :
https://github.com/jgirardet/sublack

not yet in package control, you have to clone the repo to use it.

Only one feature at the moment : run black on the current file.

Opinions and tests are welcome.

Jimmy

**Comment by ambv** [comment]
Thanks, man! This is great. The only other thing I think some people might want is the ability to format on save. The existing functionality is exactly what we need :-)

Submit a pull request for the README.md to link to your plugin!

**Comment by ruslanoid** [comment]
maybe consider also support of a `run black on selected lines only` feature?

**Comment by jgirardet** [comment]
Because sublimetext uses python 3.3 and do not support python 3.6, I can't use the black api(format_line, ..). I have to use the command line instead and I'm not sure we can change only some lines in command line.
More generaly, why would you format jsut some lines of you document ?

**Comment by ruslanoid** [comment]
you are right, i just started porting some projects and doing it gradually - actually using the `fmt: on/off`  is better approach

**Comment by ambv** [comment]
Yeah, Black deliberately doesn't support partial formatting. See #134 for a thorough explanation.

**Comment by jgirardet** [comment]
no need to let it opened
