### ISSUE TITLE
Adds E251 unexpected space after equals

### ISSUE THREAD

**Issue by hugovk** [ambv/black#14]
macOS High Sierra
Python 3.6.4
black==18.3a0

```python
# existing
def __init__(params={}):
    pass

#black
def __init__(params= {}):
    pass
```

```console
# existing
$ pycodestyle 1.py

# black
$ pycodestyle 2.py
2.py:1:21: E251 unexpected spaces around keyword / parameter equals
```

**Comment by ambv** [comment]
There are two bugs here. The first is mine, the extra space I will fix. But on your end: don't put mutable data structures as defaults :-) Use flake8 with bugbear to warn against this.

**Comment by ambv** [comment]
Thank you for your report, this is now fixed!

**Comment by hugovk** [comment]
Thanks, and my bug is also now fixed!
