### ISSUE TITLE
Support line range?

### ISSUE THREAD

**Issue by laixintao** [ambv/black#142]
Did black support line range? Like I have huge python file to edit, and just want to format part of the file (in Vim mostly)

In Vim I see `No range allowed`, so did black support line range? Or just vim-plugin didn't have that feature?

**Comment by zsol** [comment]
Black supports `# fmt: off` and `# fmt: on` to control where it shouldn't apply _any_ formatting. You should be able to use that to solve your problem

**Comment by ambv** [comment]
See https://github.com/ambv/black/issues/134 for a longer explanation why Black doesn't support partial file reformatting.

**Comment by laixintao** [comment]
Thanks

**Comment by wbolster** [comment]
fyi, i wrote https://github.com/wbolster/black-macchiato

**Comment by akaihola** [comment]
Also FYI, I wrote [darker](https://github.com/akaihola/darker) with which you can apply Black formatting only to lines which have changed in the Git working tree since the last commit.
