### ISSUE TITLE
Shouldn't change the indentation of comments

### ISSUE THREAD

**Issue by njsmith** [ambv/black#16]
This kind of changes the meaning of the comment a lot :-).

```diff
             else:
                 timeout = 0
-                # and loop back to the start
+        # and loop back to the start
         for event in events:
```

(Actual code [is here](https://github.com/python-trio/trio/blob/aee2676fd5096daf2849db9756242a30e0aa1f30/trio/_core/_io_kqueue.py#L45-L53), for reference.)

**Comment by ambv** [comment]
Comments don't have a place in the grammar. The AST I'm using, lib2to3, is placing them as whitespace prefixes on the *next* instruction. An explicit goal of Black is to be deterministic by never consulting existing formatting on the file.

Those two things combined together make it very hard for me to support one particular use case: "suffix" comments on blocks. Prefix comments are easy and this is what most code does: standalone comments describe the line behind them, not before them.

I'm not closing this as this might have a solution in the future, but this is not easy to fix.

**Comment by boppreh** [comment]
There's a workaround if your parser doesn't support comments the way you want: transform the comments into strings with a unique random prefix, run it through your pretty-printer, then transform any strings with that have the prefix back into comments.

It's incredibly dirty (you'll need to escape quotes, for example), but matches well with programmers' intuition about comments and ASTs, and is quite easy to implement.

**Comment by njsmith** [comment]
If lib2to3 turns out to be too limited, I think you could also hack comment support into a regular parser by doing a second pass scanning for comments (they're included in `tokenize` output) and then matching that up with your AST using the line/offset numbers. I think [prettier](https://github.com/prettier) might use this way?

Comment handling is super hard so I sympathize. But I'm really skeptical about whether a real-world formatter can get away with handling comments properly without taking their original spacing into account. For another much simpler example: the way black mangles the vertical spacing around [section break comments](https://github.com/python-trio/trio/blob/aee2676fd5096daf2849db9756242a30e0aa1f30/trio/_socket.py#L345-L347) in [this file](https://github.com/python-trio/trio/blob/master/trio/_socket.py) is pretty annoying. I'm not happy that that file is so complicated that it needs those section breaks, but since I'm reimplementing the huge `socket` module interface I can't really change the file, and those comments help make it more manageable.

#22 is another tricky comment handling issue -- I hope it's just a minor bug, but I wouldn't be shocked if it turns out to be unfixable while sticking to lib2to3's grammar.

**Comment by carljm** [comment]
The approach suggested by @boppreh seems promising. In Python we could use triple-quoted strings for the temporary replacement, which would dramatically reduce the frequency of needing quoting.

**Comment by boppreh** [comment]
Here's an example of the replace-twice approach, in this case to avoid processing comments and strings by replacing them identifiers: https://github.com/boppreh/altpython/blob/master/altpython.py

**Comment by hugovk** [comment]
Here's an example of changing indents of commented code. Subsequently uncommenting for debugging would not work as originally intended.

```diff
@@ -22,7 +25,8 @@ class TestBmpReference(PillowTestCase):
                 im.load()
             except Exception:  # as msg:
                 pass
-                # print("Bad Image %s: %s" %(f,msg))
+
+    # print("Bad Image %s: %s" %(f,msg))

     def test_questionable(self):
         """ These shouldn't crash/dos, but it's not well defined that these
@@ -47,35 +51,38 @@ class TestBmpReference(PillowTestCase):
             except Exception:  # as msg:
                 if os.path.basename(f) in supported:
                     raise
-                # print("Bad Image %s: %s" %(f,msg))
+
+    # print("Bad Image %s: %s" %(f,msg))

     def test_good(self):

```
