### ISSUE TITLE
add trailing comma in function definitions

### ISSUE THREAD

**Issue by ocavue** [ambv/black#160]
Operating system: ubuntu 16.04
Python version: 3.5.2
Black version: 18.4a2
Does also happen on master: yes

background: 

I'm running python 3.5 in the production environment and 3.6 for development. For 3.6, all three functions below work well. But for 3.5, function `f_wrong` has SyntaxError because it has trailing comma right after `keyword_argument_g`.

test file:

```
def f_correct1(
    position_argument_a,
    position_argument_b,
    position_argument_c,
    position_argument_d,
    position_argument_e,
    position_argument_f,
    position_argument_g,
):
    return [position_argument_a, position_argument_g]


def f_correct2(
    *,
    keyword_argument_a,
    keyword_argument_b,
    keyword_argument_c,
    keyword_argument_d,
    keyword_argument_e,
    keyword_argument_f,
    keyword_argument_g  # no trailing comma here

):
    return [keyword_argument_a, keyword_argument_g]


def f_wrong(
    *,
    keyword_argument_a,
    keyword_argument_b,
    keyword_argument_c,
    keyword_argument_d,
    keyword_argument_e,
    keyword_argument_f,
    keyword_argument_g,
):
    return [keyword_argument_a, keyword_argument_g]
```

shell output:
```
bash-3.2$ pyenv local system ; python3 --version
Python 3.6.4
bash-3.2$ python3 testpython.py
bash-3.2$ pyenv local 3.5.2 ; python3 --version
Python 3.5.2
bash-3.2$ python3 testpython.py
  File "testpython.py", line 36
    ):
    ^
SyntaxError: invalid syntax
bash-3.2$ pyenv local 3.5.5 ; python3 --version
Python 3.5.5
bash-3.2$ python3 testpython.py
  File "testpython.py", line 36
    ):
    ^
SyntaxError: invalid syntax
```

The problem is that black will add trailing comma in function definitions. In other words, black will turn `f_correct2` into `f_wrong`, who will cause SyntaxError in python 3.5.

Since python 3.5.5, which is the [last version of 3.5](https://www.python.org/doc/versions/), has this behavior, I think it's a future instead of a bug of 3.5.

**Comment by ambv** [comment]
Black recognizes if it's safe to put trailing commas in signatures. If you use f-strings or put trailing commas after stars in function signatures or function calls, Black will assume it's a 3.6 file (because it is).

Remove the trailing commas you don't want to see and try again. If Black stil keeps adding them back, please share an example file so I can debug why this is.

**Comment by ocavue** [comment]
> If you (...) put trailing commas after stars in function signatures or function calls, Black will assume it's a 3.6 file (because it is).

That explain my question! I added a trailing comma wrongly at first, and then black througth it's a 3.6 file, therefore black added trailing commas after stars for all functions. Thanks for your help!
