### ISSUE TITLE
Comparison with rustfmt seems misplaced

### ISSUE THREAD

**Issue by anowlcalledjosh** [ambv/black#167]
> In terms of inspiration, Black is about as configurable as gofmt and rustfmt are. This is deliberate.

[and yet][1]:

> Rustfmt is designed to be very configurable.

[1]: https://github.com/rust-lang-nursery/rustfmt/blob/master/Configurations.md

rustfmt also seems to have [somewhat different ideas behind it][2], e.g.:

> ### Heuristic rather than algorithmic
>
> Many formatting tools use a very general algorithmic or even algebraic tool for pretty printing. This results in very elegant code, but I believe does not give the best results.

or

> ### Use the source code as guidance
>
> There are often multiple ways to format code and satisfy standards. Where this is the case, we should use the source code as a hint for reformatting. Furthermore, where the code has been formatted in a particular way that satisfies the coding standard, it should not be changed

[2]: https://github.com/rust-lang-nursery/rustfmt/blob/master/Design.md

NB: I have only just started using Rust, so it's possible that I've got totally the wrong end of the stick :)

**Comment by ambv** [comment]
Right, I should reword it!
