### ISSUE TITLE
Maybe its time to export ChangeLog to a file of its own say CHANGELOG.rst

### ISSUE THREAD

**Issue by csurfer** [ambv/black#168]
Title says it all.

**Comment by ambv** [comment]
I want to move the change log to its own file when we get out of alpha. Currently it's nice to see how far we've gone. And I'd like to keep it visible on PyPI.

**Comment by SethMichaelLarson** [comment]
You could keep the file separate and then combine them within `setup.py` for the `long_description` field? [This is what urllib3 does](https://github.com/urllib3/urllib3/blob/master/setup.py#L25).

**Comment by ambv** [comment]
If you have a minute to do this via a pull request, I'll accept that. Just remember to symlink it to docs/, too.

**Comment by ambv** [comment]
I like Carol's approach with navigation links better.
