### ISSUE TITLE
Maybe black should consider precedence of binary operations when splitting expressions?

### ISSUE THREAD

**Issue by njsmith** [ambv/black#169]
Here's an odd bit of formatting that black gave me, using black on latest master with `-l 79`:

```python
def test_foo():
    expected = (
        [("before_run",)]
        + 6
        * [("schedule", task), ("before", task), ("after", task)]
        + [("after_run",)]
    )
```

This is weird because the `*` binds more tightly than the `+`, so it's actually 6 copies of that list. If I add explicit parentheses around the `*` operation, then black gives me the much more sensible:

```python
def test_foo():
    expected = (
        [("before_run",)]
        + (6 * [("schedule", task), ("before", task), ("after", task)])
        + [("after_run",)]
    )
```

So that's a workaround, but maybe black should realize that `*` binds more tightly than `+` and treat the first case the same way as it treats the parenthesized case? Or insert parentheses, or... something? It feels like black has enough information here to do something better.

**Comment by ambv** [comment]
Yes, see #148.

**Comment by njsmith** [comment]
Ah, sounds like this is a dupe indeed, feel free to close.
