### ISSUE TITLE
Reformatting print()s that span multiple lines does not remove extraneous "s

### ISSUE THREAD

**Issue by cricalix** [ambv/black#170]
Operating system: Linux
Python version: 3.6.3rc1
Black version: 18.4a1
Does also happen on master: Yes (18.4a3 cloned today)

Original code:
```
            self.logger.debug(
                f'Skipped {skipped_count} virtual '
                f'interfaces for {device.name}'
            )
```

black'd code:
```
            self.logger.debug(
                f"Skipped {skipped_count} virtual " f"interfaces for {device.name}"
            )
```

Could black detect that it's done this (with or without f-string markers), and remove the ' " " ' that results, or is that considered too invasive a change to the code?

**Comment by Lukas0907** [comment]
See also #26, possible duplicate.

**Comment by cricalix** [comment]
Absolutely a duplicate :( Didn't see that in my searching.
