### ISSUE TITLE
upload on conda-forge

### ISSUE THREAD

**Issue by carlodri** [ambv/black#184]
@ambv if you agree I would like to upload black on the [conda-forge repository](https://conda-forge.org/). Is this ok for you? Would you like to be added as a feedstock maintainer together with me?

**Comment by ambv** [comment]
Yes on both counts. Thanks for helping spread Black :-)

**Comment by willingc** [comment]
Huge +1 for conda-forge.

**Comment by carlodri** [comment]
almost done: https://github.com/conda-forge/staged-recipes/pull/5778

**Comment by carlodri** [comment]
done. @ambv I think you need to accept your invitation to join the conda forge team.
