### ISSUE TITLE
Trailing comma after from .. import

### ISSUE THREAD

**Issue by jooon** [ambv/black#185]
Operating system: Ubuntu 16.04
Python version: 3.6.5
Black version: 18.4a4
Does also happen on master: yes

The following import:
```
from datetime import (
    timedelta,
)
```
is incorrectly transformed to:

```
from datetime import timedelta,
```

Thankfully caught by black --safe who told me: INTERNAL ERROR: Black produced invalid code: trailing comma not allowed without surrounding parentheses (<unknown>, line 1).

**Comment by skapil** [comment]
@ambv if you want, I can take a look.
Do we want to keep user code as it is or want to format some other way?

**Comment by ambv** [comment]
Sure, take a look. It should be transformed but the trailing comma should be removed.

**Comment by skapil** [comment]
@ambv Thanks for working on it!! 👍

**Comment by ambv** [comment]
Sorry I didn't leave you the bug to play with but this turned out to be more popular with code in the wild than I anticipated so I had to fix quickly.

**Comment by skapil** [comment]
@ambv no worries. 👍
