### ISSUE TITLE
Standardize case for string prefixes

### ISSUE THREAD

**Issue by JelleZijlstra** [ambv/black#198]
In implementing a fix for #188 it occurred to me that black could also standardize the case of string literal prefixes (presumably to lowercase). For example, change `R"string"` to `r"string"`.

@ambv is this something you'd be open to doing?

**Comment by ambv** [comment]
Yes, that's an obvious omission from our previous standardization. Fortunately way fewer people actually use upper-case string prefixes :)

cc @zsol

**Comment by JelleZijlstra** [comment]
Sounds good, I can implement this in #199.
