### ISSUE TITLE
black must be run twice when used with pre-commit

### ISSUE THREAD

**Issue by mxr** [ambv/black#201]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Mac OS 10.13.4
Python version: 3.6.5 (through pyenv)
Black version: 18.4a4
Does also happen on master:  yes

To answer the last question, follow these steps:
* create a new virtualenv (make sure it's the same Python version);
* clone this repository;
* run `pip install -e .`;
* make sure it's sane by running `python setup.py test`; and
* run `black` like you did last time.

___

When I change a file and use `black` with `pre-commit` to update the file on commit, `black` will fix the file but return an error code. I have to try to commit again (then `black` does not change the code and allows the commit). So when I use `black` with `pre-commit` I have to issue all my commits twice. I would expect for `black` to fix the code & let me commit in one attempt though.

```
$ cat .pre-commit-config.yaml
- repo: https://github.com/ambv/black
  rev: stable
  hooks:
  - id: black
    python_version: python3.6

$ echo 'x =    1' > file.py
$ git add . && git commit -m 'create file.py'
black....................................................................Failed
hookid: black

Files were modified by this hook. Additional output:

reformatted /Users/maxr/tmp/py3/file.py

$ cat file.py
x = 1
$ git add . && git commit -m 'create file.py'
black....................................................................Passed
[master 0e5c697] create file.py
 1 file changed, 1 insertion(+)
 create mode 100644 file.py
$ git show
commit 0e5c697bfb1b2362dd4f45faa427baa51497b5b6 (HEAD -> master)
Author: Max Rozentsveyg <redacted@example.com>
Date:   Wed May 9 00:44:17 2018 -0700

    create file.py

diff --git a/file.py b/file.py
new file mode 100644
index 0000000..7d4290a
--- /dev/null
+++ b/file.py
@@ -0,0 +1 @@
+x = 1

**Comment by asottile** [comment]
This is intentional. See https://github.com/pre-commit/pre-commit/issues/747#issuecomment-386782080

pre-commit will never modify your staging area. Hooks can be buggy and undoing that is a huge pain

**Comment by mxr** [comment]
Got it, thanks.
