### ISSUE TITLE
Is the concatenating lines with strings intended like this?

### ISSUE THREAD

**Issue by obestwalter** [ambv/black#205]
Operating system: Arch Linux
Python version: 3.6
Black version: 18.4a4
Does also happen on master: dunno - I don't even know if it is a bug or a feature yet.

With default line length black turns

    fmt = (
        "%(asctime)s %(filename)s.%(funcName)s:%(lineno)d %(levelname)s: "
        "%(message)s"
    )

into

    fmt = (
        "%(asctime)s %(filename)s.%(funcName)s:%(lineno)d %(levelname)s: " "%(message)s"
    )

I would expect to either leave it alone or concatenate the strings like:

    fmt = (
        "%(asctime)s %(filename)s.%(funcName)s:%(lineno)d %(levelname)s: %(message)s"
    )

Is this behaviour intended?

**Comment by zsol** [comment]
Yes, in the future black will be able to merge these strings, see https://github.com/ambv/black/issues/26 for some more discussion around this

**Comment by obestwalter** [comment]
Hi @zsol thanks, I missed that one, when looking for open issues.
