### ISSUE TITLE
black line length isn't correctly enforced for comments in dicts

### ISSUE THREAD

**Issue by offbyone** [ambv/black#208]
Operating system: MacOS
Python version: Python 3.6.5
Black version: black, version 18.4a4
Does also happen on master: yes

Given python code like this:

```python
f(
    {
        "k": {
            # NOTE: many of these are also set in kwarg defaults above; but having
            # them here too means once we get rid of our custom release(), the
            # behavior stays.
            "sign": True
        }
    }
)
```

Running black with line length 79 does not actually wrap the comment correctly:

```
black -l 79 sample.py ; flake8 sample.py
reformatted /Users/offby1/projects/fab/paramiko/sample.py
sample.py:8:80: E501 line too long (82 > 79 characters)
```

**Comment by ambv** [comment]
Thanks for your report!

Comments are not and will not be hand-edited by Black. Black is not able to understand if the comment is safe to rewrap. Use your editor to re-flow the comments which *are* safe and Black will respect your edit.

Similarly, Black will not reflow multiline strings (like docstrings).

**Comment by kylrth** [comment]
Can this be placed in the code style guide? I had to come here to learn this fact.
