### ISSUE TITLE
black introduces PEP 8 violation: operators should go at beginning of lines when possible

### ISSUE THREAD

**Issue by njsmith** [ambv/black#21]
```
 @contextmanager
 def ki_manager(deliver_cb, restrict_keyboard_interrupt_to_checkpoints):
     if (
-        threading.current_thread() != threading.main_thread()
-        or signal.getsignal(signal.SIGINT) != signal.default_int_handler
+        threading.current_thread() != threading.main_thread() or
+        signal.getsignal(signal.SIGINT) != signal.default_int_handler
     ):
```

Ok, technically PEP 8 waffles a bit b/c it used to recommend the other version. But these days it says that operator-at-beginning "usually results in more readable code" and "For new code [operator-at-beginning] style is suggested".

**Comment by ambv** [comment]
Oh, I never noticed PEP 8's change in direction here. This is a relatively new change, Knuth-inspired, no less:

**Comment by njsmith** [comment]
This was always one of my biggest wtf's with PEP 8, so I'm excited they changed it :-)

**Comment by ambv** [comment]
Yay! Thanks, @Autophagy.
