### ISSUE TITLE
Allow to disable emoji in output

### ISSUE THREAD

**Issue by giuscri** [ambv/black#223]
As an environment variable (e.g. `BLACK_HIDE_EMOJIS`) or as an option.

**Comment by JelleZijlstra** [comment]
What's your motivation?

**Comment by giuscri** [comment]
emoji support can be problematic on some platform. https://debbugs.gnu.org/cgi/bugreport.cgi?bug=30045

The reason why I noticed you can't toggle emojis is that my terminal crashed when using `black .` Currently I solved by sending stderr of black to devnull.

**Comment by ambv** [comment]
This sounds like something that should be fixed or worked around in your terminal, not in end-user tools that use Unicode characters. I happen to have a non-Latin 1 character in my first name so [I'm rather sensitive to bad Unicode support](https://www.youtube.com/watch?v=7m5JA3XaZ4k&).

**Comment by giuscri** [comment]
I see your point. Also, I didn't noticed there's a `--quiet` option in black. Closing this.

**Comment by waldronfaulkner** [comment]
Opinion: there should be an option to disable emoji output. There are a lot of people—_old_ or not—who feel emojis are dumb and unprofessional and just lower the tone of everyday work when they're spattered all across our consoles

**Comment by ArsenArsen** [comment]
Hi! Some of my co-developers raised concerns about emojis looking out of place in CI output, so I'd like to propose a `BLACK_NO_FUN` environment variable that allows for them to be disabled on site, if the user hates fun.

I see that it's been proposed to use `--quiet`, the issue with that, though, is that it does not show other information too, so it's not worth it.

PS: I'd be fine with contributing this myself, but I'd like to get prior discussion with the maintainers.

Thanks in advance.

**Comment by jap** [comment]
I just ran across some code making use of emojis, all-caps words and coloring in a script that calls black and some other formatters and linters. 
The reason was to make sure it stands out more than black's output. This is just a race to the bottom for attention :(

**Comment by TimZaman** [comment]
unicode support is fine, but just like jap said - there is no need to hijack attention what is otherwise a calming terminal experience.

**Comment by draeath** [comment]
I'd like to see this as well. Gives it a non-professional feel, which is unfair I know, but there it is.
