### ISSUE TITLE
sdist is missing files

### ISSUE THREAD

**Issue by tiran** [ambv/black#226]
I noticed that source distribution is missing some files and directories:

- [ ] ~docs/~
- [ ] plugin/
- [ ] ~Pipfile~
- [ ] ~mypy.ini~
- [ ] blib2to3/README
- [ ] blib2to3/LICENSE
- [ ] blib2to3/**/*.pyi

**Comment by ambv** [comment]
I don't want to ship those in the source distribution. What for?

**Comment by auscompgeek** [comment]
The *.pyi files might make sense if for some reason people wanted to use blib2to3 directly, and perhaps the lib2to3 license text should be preserved somewhere, but the rest would make absolutely no sense to ship in a source distribution.

**Comment by tiran** [comment]
The license file of ``lib2to3`` should be included for legal reasons. I don't care much about the rest, though.

**Comment by ambv** [comment]
Alright, sounds like all essential files are now distributed. Closing :-)
