### ISSUE TITLE
Black introduce whitespace before ":" inside parentheses, resulting in breaking flake8 E203

### ISSUE THREAD

**Issue by hotsyk** [ambv/black#227]
Sorry, if this was discussed, or closed before, tried to find and haven't found.

```
Operating system: MacOS
Python version: 3.6.3
Black version: master
Does also happen on master: Yes
```

Having code:
```
def chunks(l, n):
    for i in range(0, len(l), n):
        yield l[i:i + n]
```
black formats last line to 
```
yield l[i : i + n]
```
which leads to Flake8 [E203](https://lintlyci.github.io/Flake8Rules/rules/E203.html) error.

**Comment by zsol** [comment]
Yep, the readme covers this :) https://github.com/ambv/black#slices

**Comment by mloning** [comment]
Fixed link: https://black.readthedocs.io/en/stable/the_black_code_style.html?highlight=slices#slices
