### ISSUE TITLE
black fails with hanging line comments

### ISSUE THREAD

**Issue by offbyone** [ambv/black#228]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: macos
Python version: Python 3.6.4
Black version: 18.4a0
Does also happen on master: yes

This file fails:

```python
def main():
    if True:
        showconfig()
        sys.exit(42)  # a comment
                      # a hanging comment

```

This is the error:

`error: cannot format /Users/chrisros/tmp/failure.py: Cannot parse: 5:0:                       # another`

**Comment by ambv** [comment]
Thanks for your report! Hm, I fixed a problem like this already. Those unaligned comments come back to haunt me! Will fix for the next release.

**Comment by ambv** [comment]
Well, I cannot repro with this file on master. It formats fine to:
```py3
def main():
    if True:
        showconfig()
        sys.exit(42)  # a comment
        # a hanging comment
```

Can you test with 18.5b0 instead of 18.4a0 which is super old?

**Comment by offbyone** [comment]
I've confirmed what I said on Twitter; it turns out that the repro-with-head instructions need an extra step: rehash the shell PATH. I was still running the system black even though I thought I was using -dev.
