### ISSUE TITLE
Long lines in dictionary comprehensions break due to trailing comma

### ISSUE THREAD

**Issue by ojii** [ambv/black#23]
This input:
```python
{k: v for k, v in this_is_a_very_long_variable_which_will_cause_a_trailing_comma_which_breaks_the_comprehension}
```

becomes

```python
{
    k: v
    for k,
    v in this_is_a_very_long_variable_which_will_cause_a_trailing_comma_which_breaks_the_comprehension,
}
```

Note the trailing comma after `...comprehension`, this is not allowed in dictionary comprehensions.

**Comment by ambv** [comment]
Yes, the trailing comma handling is invalid here.

**Comment by ambv** [comment]
Black was fooled by "k, v" in the dictionary comprehension here. This is now fixed. Thanks for testing Black and your reports! :-)
