### ISSUE TITLE
Opinion: Unwanted indentation of multiline string

### ISSUE THREAD

**Issue by KangOl** [ambv/black#233]
I tend to write my SQL queries using this formatting.
```python
def get_stuff(cr, value):
    cr.execute("""
        SELECT whatever
          FROM some_table t
         WHERE id = %s
    """, [value])
    return cr.fetchone()
```

However, `black --diff` produce the following output
```diff
--- foo.py  (original)
+++ foo.py  (formatted)
@@ -1,8 +1,11 @@
 def get_stuff(cr, value):
-    cr.execute("""
+    cr.execute(
+        """
         SELECT whatever
           FROM some_table t
          WHERE id = %s
-    """, [value])
+    """,
+        [value],
+    )
     return cr.fetchone()

reformatted foo.py
```

Which I find less readable, unpleasant.

Shouldn't `black` keep a multiline string first argument on the same line? (unless the line is too long, obviously)

**Comment by JelleZijlstra** [comment]
I encountered the same issue with calls to `re.compile("""really long multiline regex""", re.VERBOSE)`

**Comment by ambv** [comment]
No. Black never hugs arguments to parentheses. Think of the opening triple quotes like an opening bracket. Black wouldn't keep it on the same line with another opening bracket.

Instead of using this formatting:
```py3
def get_stuff(cr, value):
    cr.execute("""
        SELECT whatever
          FROM some_table t
         WHERE id = %s
    """, [value])
    return cr.fetchone()
```

Black considers this a better formatting:
```py3
def get_stuff(cr, value):
    cr.execute(
        """
        SELECT whatever
        FROM some_table t
        WHERE id = %s
        """,
        [value],
    )
    return cr.fetchone()
```

This is symmetrical to something like:
```py3
def get_stuff(cr, value):
    cr.execute(
        (
            'SELECT whatever '
            'FROM some_table t '
            'WHERE id = %s'
        ),
        [value],
    )
    return cr.fetchone()
```

Unfortunately it's not safe for Black to change indentation *within* your multiline strings, so that it up to you.

**Comment by ambv** [comment]
There are cases of multiline string support that need improvements (like #256) but this doesn't seem actionable to me. Closing.
