### ISSUE TITLE
Pre-formatted logical expressions losing formatting.

### ISSUE THREAD

**Issue by csurfer** [ambv/black#239]
Code for long logical expressions of the sort

```python
flag = boolParam1 and \
boolParam2 and \
boolParam3 and \
boolParam4 and \
boolParam5
```

is changed to

```python
flag = boolParam1 and boolParam2 and boolParam3 and boolParam4 and boolParam5
```

Many a times exceeding the line length. The right way to format would be 

```python
flag = (
    boolParam1
    and boolParam2
    and boolParam3
    and boolParam4
    and boolParam5
)
```

which can be achieved by covering the preformatted code with `\` as
1. Cover the code with parenthesis `( ... )`
2. Remove `\` used for pre-formatting.
3. Other formatting rules that black imposes.

**Comment by ambv** [comment]
You probably didn't test this with 18.5b0.

**Comment by csurfer** [comment]
Not reproducible with 18.5b0.
