### ISSUE TITLE
PATH invaild

### ISSUE THREAD

**Issue by ridegod** [ambv/black#240]
Usage: black [OPTIONS] [SRC]...

Error: Invalid value for "src": Path "E:\Programming" does not exist.
it can't support the path have the Chinese?

**Comment by ambv** [comment]
Do you have spaces in your paths? You will need to pass your file name using quotation marks around it then, like this:
```
> black "E:\Programming And Hobbies\file.py"
```

This is what the error you pasted suggests. If there really were Chinese characters there, please provide an example path for us to check.

**Comment by ridegod** [comment]
I had solved the issues. There is a space in the Folder name. Delete it .It's OK.
