### ISSUE TITLE
Opinion: Extra whitespace for function inside a function

### ISSUE THREAD

**Issue by oxo42** [ambv/black#243]
If I have the following

```python
def foo():
    def bar():
        pass
    
    pass
```

Black will reformat it to 
```python
def foo():

    def bar():
        pass

    pass
```

Is the blank line between `def foo` and `def bar` necessary.  My opinion is not, but if you disagree, feel free to close and I'll keep quiet 😄

**Comment by ambv** [comment]
Also, this is a duplicate of #196.
