### ISSUE TITLE
Only format git diff (similar to clang-format-diff)

### ISSUE THREAD

**Issue by Rikorose** [ambv/black#245]
Relevant yapf issue: https://github.com/google/yapf/issues/190

It would be really helpfull to only format code that was changed which also helps to minimize the diff.

`clang-format-diff` example:
```sh
git diff -U0 --no-color HEAD^ | clang-format-diff.py -p1 -i
svn diff --diff-cmd=diff -x-U0 | clang-format-diff.py -i
```

**Comment by ambv** [comment]
Black is unable to format line ranges. This would be rather problematic given how it's currently implemented. More importantly, this goes against PEP 8's philosophy of staying consistent within a file (and more generally, within a project). See #134 for a longer explanation.

**Comment by Lukas0907** [comment]
You can format the whole file and only commit relevant changes via `git add -p` and revert what you don't want to change.

**Comment by ambv** [comment]
This is not a planned feature.

**Comment by wbolster** [comment]
fyi, i wrote https://github.com/wbolster/black-macchiato

**Comment by akaihola** [comment]
Also FYI, I wrote [darker](https://github.com/akaihola/darker) which can apply Black formatting only to lines which have changed in the Git working tree since the last commit.

**Comment by sieu-n** [comment]
For quick solution, run the following script.
```
#!/bin/bash

# Get a list of changed Python files in the diff
changed_files=$(git diff --name-only --diff-filter=d HEAD | grep '\.py$')

# Apply isort and black to the changed files
for file in $changed_files; do
  isort "$file"
  black "$file"
done
```
