### ISSUE TITLE
Add command line option to ignore cache

### ISSUE THREAD

**Issue by dgouldin** [ambv/black#248]
I ❤️ Black!

It would be nice to have the option to ignore its local cache in order to force it to reevaluate all files. Perhaps a `--no-cache` flag?

Thanks!

**Comment by ambv** [comment]
What's your use case for this?

**Comment by ambv** [comment]
There are a number of things we could do to make developmen a bit easier but that's not a use case I'd like to prioritize.

A need to ignore the cache suggests there is something wrong with it that needs to be fixed.

**Comment by tiran** [comment]
In the mean time and on Linux, you can set ``XDG_CACHE_HOME`` to an invalid path to suppress caching:

```
$ XDG_CACHE_HOME=/invalid python3 -m black black.py 
```

**Comment by ambv** [comment]
X Desktop Group to the rescue.

**Comment by dgouldin** [comment]
From the source, it looks like a cache hit is determined by a file's size and modified time. I can conceive of ways this could result in false positives, but admittedly it would be an unusual case.

I think it's reasonable to say you don't want to prioritize this feature. I hadn't seen it proposed yet, so I thought I would. Thankfully the cache storage path is well documented, so when I was uncertain about the cache hits I was seeing, I was able to `rm -rf` the cache itself.

**Comment by ambv** [comment]
If this is reassuring to you, what Black is caching on is exactly what `git status` is using to determine changes. It would take a deliberate attempt or a broken file system to fool it.

Or a bug, which is why I'd like those exposed and fixed rather than worked around.

**Comment by ambv** [comment]
I'll close this as this is not a planned feature.

**Comment by sanmai-NL** [comment]
> There are a number of things we could do to make developmen a bit easier but that's not a use case I'd like to prioritize.
> 
> A need to ignore the cache suggests there is something wrong with it that needs to be fixed.

Suggests, but doesn't imply. Not all calls to disable a feature are due to (functional) correctness defects, it's also a matter of performance efficiency.
