### ISSUE TITLE
Documentation for running Black in vim on save?

### ISSUE THREAD

**Issue by ns-cweber** [ambv/black#252]
I've Googled vigorously for "how to run a vim command on save", but I haven't been able to figure this out. I've also searched this repository. Could you provide a blurb under the "vim" section?

**Comment by mahmoudhossam** [comment]
I was able to get it to work in neovim by using the vim plugin provided here and putting this in my `init.vim` file (`.vimrc` if you're using vim)

```autocmd BufWritePost *.py execute ':Black'```

**Comment by ns-cweber** [comment]
Thanks! Is there any way to elide the output:

```
"main.py" 2L, 22C written
Reformatted in 0.0049s.
Press ENTER or type command to continue
```

**Comment by ambv** [comment]
I'm open to a pull request that mentions that in the README.

**Comment by dgouldin** [comment]
`autocmd BufWritePost *.py silent! execute ':Black'` will suppress the output, but it suppresses errors too, which is probably not exactly what you want.

**Comment by ns-cweber** [comment]
@dgouldin I don't mind that it suppresses errors, since I use syntastic, but the cursor doesn't stay at the same position (in the AST, it might well keep its same offset from the start of the file or whatever). This probably isn't the right issue to address this, but a good on-save story would probably help adoption; `vim-go`'s support for `gofmt` could be used as a reference here.

**Comment by ambv** [comment]
I'm not sure how we would signal where the cursor should go after a save but it sounds like a sensible idea. I'd be open to a PR like this.

Same with a PR introducing :BlackQuiet that only outputs errors.

**Comment by di** [comment]
For anyone landing here in the future, the documentation is here: https://black.readthedocs.io/en/stable/editor_integration.html#vim

**Comment by t-eckert** [comment]
> For anyone landing here in the future, the documentation is here: https://black.readthedocs.io/en/stable/editor_integration.html#vim

I get a 404 on that page today.

**Comment by ichard26** [comment]
Yeah we moved things around in the documentation a few months ago, sorry for the breakage!

Perhaps I should consider adding redirects (although the nature of the movement makes that hard).

**Comment by t-eckert** [comment]
I don't know if you need to worry about it. I found my way to what I needed anyway. I just wanted to save future versions of myself the trouble.

**Comment by ubaldot** [comment]
I have also stumbled into this issue and I fixed by adding the following in `~/.vim/ftplugin/markdown.vim`:

```
# Autocmd to format with black.
augroup BLACK
    autocmd! * <buffer>
    autocmd BufWritePre <buffer> call Black(&l:textwidth)
augroup END

def Black(textwidth: number)
        var win_view = winsaveview()
        exe $":%!cat {shellescape(expand("%"))} | black - -q --line-length {textwidth}"
        winrestview(win_view)
enddef

# Call black to format 120 line length
command! Black120 call Black(120)
```
