### ISSUE TITLE
Different input on second pass / comment in chained call

### ISSUE THREAD

**Issue by cosmith** [ambv/black#253]
Hi, I tried running Black on my codebase and got one error:
INTERNAL ERROR: Black produced different code on the second pass of the formatter

I narrowed it down to this section:
```
(
    queryset.annotate(rating_null=Coalesce("rating", Value(0)))  # transform NULL to 0
        .order_by("-rating_null", "-rating", "-updated")
)
```

Operating system: OSX
Python version: 3.6
Black version: 18.5b0
Does also happen on master: Yes

This is the diff generated:
```diff
--- source
+++ first pass
@@ -1,5 +1,6 @@
 (
-    queryset.annotate(rating_null=Coalesce("rating", Value(0)))  # transform NULL to 0
-        .order_by("-rating_null", "-rating", "-updated")
+    queryset.annotate(
+        rating_null=Coalesce("rating", Value(0))
+    ).order_by("-rating_null", "-rating", "-updated")  # transform NULL to 0
 )
 
--- first pass
+++ second pass
@@ -1,6 +1,6 @@
 (
-    queryset.annotate(
-        rating_null=Coalesce("rating", Value(0))
-    ).order_by("-rating_null", "-rating", "-updated")  # transform NULL to 0
+    queryset.annotate(rating_null=Coalesce("rating", Value(0))).order_by(
+        "-rating_null", "-rating", "-updated"
+    )  # transform NULL to 0
 )
```

The good news is I realized this was actually some dead code so I removed it and Black runs on the whole code base :)

**Comment by ambv** [comment]
Are you sure this is still happening on master? I was specifically targetting this bug in one of the fixes there.

**Comment by cosmith** [comment]
I tried again by uninstalling black and then reinstalling with `pip install git+https://github.com/ambv/black.git` and this time it worked. I guess the existing install was left there when I tried it the first time.
