### ISSUE TITLE
Create backup files instead of always overwriting.

### ISSUE THREAD

**Issue by chungy** [ambv/black#257]
Operating system: Linux (Arch, 64-bit)
Python version: 3.6.5
Black version: 18.5b0
Does also happen on master: yes

Black doesn't copy the input file(s) to a backup (eg, by appending `~` to the name), instead always overwrites in-place. This is kind of fine for files that are already managed by a VCS, but for ones outside of it, it will be nice to see what changes have happened and even the possibility to revert in case of bugs in Black itself that may produce invalid code.

**Comment by ambv** [comment]
If Black discovers it would produce invalid code, it will refuse to save the file. It checks the AST is the same before and after. The only unwanted changes might be in comments and whitespace. I don't want to litter users' directories with backup files.
