### ISSUE TITLE
Invalid syntax error of Vim plugin

### ISSUE THREAD

**Issue by medihack** [ambv/black#266]
Operating system:
Ubuntu 16.04

Python version:
Python 3.6.5

Black version:
Vim Plug installs master from Github

Does also happen on master:
Yes.

After installation of the Vim plugin (using Plug under Vim 8.1.20) I get the following error every time I launch Vim:
```
Error detected while processing /home/ubuntu/.vim/plugged/black/plugin/black.vim:
line  114:
  File "<string>", line 17
    return venv_path / 'lib' / f'python{pyver[0]}.{pyver[1]}' / 'site-packages'
                                                            ^
SyntaxError: invalid syntax
```

Any idea how to fix this?

**Comment by ambv** [comment]
Your Vim is compiled with Python 2. Use Vim compiled with Python 3 (or both).

**Comment by ottojolanki** [comment]
I would like to add, for completeness sake, that this error occurs also with python 3 versions that are <3.6
