### ISSUE TITLE
quiet is too quiet, non-quiet is too noisy

### ISSUE THREAD

**Issue by rbtcollins** [ambv/black#283]
Operating system: Ubuntu Bionic
Python version: 3.6
Black version: 18.5b1
Does also happen on master: haven't checked but code inspection says it will

Without --quiet, we see messages like `test_postgres_lib.py wasn't modified on disk since last run.`, or that its already formatted fine, neither of which tell a developer about actual changes that have happened (though sure, they can be useful diagnostics).

With --quiet, we see no output at all, and developers using less capable IDEs won't know to reload the file - or even that anything happened at all.

It would be really nice to have a middle ground, where messages about changes made are emitted to stderr, but not messages that reflect no-change-being-made.

**Comment by ambv** [comment]
Thanks for your report, this is fixed in 18.6b0.
