### ISSUE TITLE
Suggestion for big assignments

### ISSUE THREAD

**Issue by kootenpv** [ambv/black#291]
Imagine:

    `secret = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"`

Black makes this:

```
secret = ( 
 "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa",
)

```
I don't think that makes sense. Is there a way this can be solved?

**Comment by auscompgeek** [comment]
I think this is a duplicate of #273.

**Comment by kootenpv** [comment]
Indeed! Duplicate.
