### ISSUE TITLE
Public programmatic api

### ISSUE THREAD

**Issue by asottile** [ambv/black#292]
I'd like to use the functionality of black to apply to unique cases where black is (probably) not interested in covering.

The specific example I had in mind, was parsing out `.. code-block:: python` portions in `.rst` files or fenced `python` blocks in markdown and formatting them.

Initial idea inspired from [here](https://github.com/pytest-dev/pytest/issues/3525)

**Comment by zsol** [comment]
You should be able to depend on black as a library and use [format_str](http://black.readthedocs.io/en/stable/reference/reference_functions.html#black.format_str) for this for now, but you probably already figured this out.

So your real question seems to be how stable do we expect these APIs to be. I think until we're out of beta we won't give any promises, but I'll let @ambv give you a definitive answer

**Comment by asottile** [comment]
Yep, definitely found that -- though it's not documented anywhere and I wasn't sure about the stability there.

**Comment by ambv** [comment]
Anthony, we don't define `__all__` yet and at some point we might break black into a few modules. We've grown quite a bit in the last three months.

That being said, if you are using `format_str()`, you should be fine. I'm already trying not to break its compatibility (there are already existing use cases for it).

**Comment by asottile** [comment]
Cool, this wasn't so bad.  In all I needed:

- [`black.DEFAULT_LINE_LENGTH`](https://github.com/asottile/blacken-docs/blob/e533e19caaa94ed46c0350b255d41e8e3b4c8066/blacken_docs.py#L90)
- [`black.FileMode`](https://github.com/asottile/blacken-docs/blob/e533e19caaa94ed46c0350b255d41e8e3b4c8066/blacken_docs.py#L102)
- [`black.format_str`](https://github.com/asottile/blacken-docs/blob/e533e19caaa94ed46c0350b255d41e8e3b4c8066/blacken_docs.py#L48)
