### ISSUE TITLE
When I include `black` in my git commit message, black gets run 

### ISSUE THREAD

**Issue by Mariatta** [ambv/black#295]
Operating system: mac OS High Sierra 10.13.4
Python version: 3.6.5
Black version: 18.5b1
Does also happen on master: yes

`black` is being run when I have a git commit message that includes `black` 😅

example:

```
git commit -am "🤖 Format code using `black`"
```

or even
```
git commit -am "`black`"
```

output:
```
$ git commit -am "`black`"
No paths given. Nothing to do 😴
On branch pr_13
nothing to commit, working tree clean
```

It can have undesired side effect. For now I can update my git commit message, but thought I'll report this strange edge case :)

**Comment by zsol** [comment]
I bet this is your shell playing tricks with you :)

Try using single quotes (no pun intended)

**Comment by Mariatta** [comment]
I can't use single quotes instead of double quotes. The git commit command is part of my bot (Python code) that has been formatted with black.

**Comment by Mariatta** [comment]
This also runs black btw:
```
 git commit -am "`black .`"
```

**Comment by zsol** [comment]
It's hard to be more helpful without seeing the actual code that triggers this. As far as I can tell your bot builds that `git commit` string and shells out to execute it? Black shouldn't change quotes _inside_ that string; if it does, it's a bug.

**Comment by ambv** [comment]
Mariatta, this is because your shell is treating backticks as syntax to run an arbitrary command. Try committing something with `yes` in the commit message, you'll see what I mean.

This isn't something that Black can fix, you need to escape your strings. Try single quotes around your commit message (e.g. `git commit -m '\`black\`'`).
