### ISSUE TITLE
Additional space after star unpacking

### ISSUE THREAD

**Issue by carmocca** [ambv/black#297]
Python version: 3.6.5
Black version: 18.5b1

Black seems to add an additional space after a `*` when unpacking a tuple

```diff
--- test.py  (original)
+++ test.py  (formatted)
@@ -1,2 +1,2 @@
-x = 1, *(2, 3)
+x = 1, * (2, 3)
```

I'm guessing this should be already well formatted.

**Comment by ambv** [comment]
Good catch, Black misinterprets unpacking in a tuple here for a multiplication. We'll fix it!

**Comment by tweakimp** [comment]
Somehow this does not happen inside something:
```python
c = 1,*(1,*(2, 3))
```
becomes
```python
c = 1, * (1, *(2, 3))
```

**Comment by tweakimp** [comment]
Still happening with string unpacking:
Python 3.6.5
black, version 18.6b1
```python
x = 1, *"ab" # original
x = 1, * "ab" # formatted
````
