### ISSUE TITLE
stdout is not equivalent to stdin in 18.6b0

### ISSUE THREAD

**Issue by jgirardet** [ambv/black#299]
Since the new version, black add by default "reformatted" or "unchanged' to stdout, even in --diff.

That breaks the expected behavior, as explained in README.

> Any tool that can pipe code through Black using its stdio mode (just use - as the file name). The formatted code will be returned on stdout (unless --check was passed). Black will still emit messages on stderr but that shouldn't affect your use case.

I personally think it's regression since `black -` can't be used anymore for anything else printing in a console.

The usage of "quiet", which gives a valid stdout, make loose the non error messages.

I not asking to change it at any price (even if I'd like) but I want to be sure it's the expected behavior.

Jimmy

**Comment by zsol** [comment]
You're right, this breaks diff output for example. Let me patch it real quick.

**Comment by jgirardet** [comment]
thanks for the quick fix

**Comment by ambv** [comment]
Fixed already, released as 18.6b1.
