### ISSUE TITLE
Black fails on empty multiline string (`''''''`): string index out of range

### ISSUE THREAD

**Issue by nschloe** [ambv/black#313]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system:
Python version: 3.6.5
*Black* version: 18.8b0

When running black on
```
a = ''''''
```
one gets
```
error: string index out of range
```
Workaround: Manually replace the six `'` by `"`.

**Comment by zsol** [comment]
This repros on master, I'll take a look. Thanks for reporting!
