### ISSUE TITLE
Trailing whitespace in triple double quotes does not get cut

### ISSUE THREAD

**Issue by tweakimp** [ambv/black#318]
Operating system: Windows 10 x64
Python version: 3.6.5
**Black** version: 18.6b1
Does also happen on master: :heavy_check_mark:

Black does not change anything in this:
```python
"""
This string has 
trailing whitespace 
in every but the last line.
"""
```
Is it supposed to be that way?

**Comment by ambv** [comment]
Thanks for your interest in Black! 💯 

As for your question: yes, all contents in a multiline strings is data. It would be invalid for Black to modify it because your application may depend on it being exactly as is.
