### ISSUE TITLE
`black` mishandles functions that end in a comment

### ISSUE THREAD

**Issue by dhermes** [ambv/black#32]
For the repro file `too_many_returns.py`, I have a `pylint: disable` / `pylint: enable` at the beginning and end of a function (but it is within the scope of the function):

```python
"""``black`` issue repro."""


def squared(value):
    """Just squares a number."""
    # pylint: disable=too-many-return-statements
    if value == 1:
        return 1

    elif value == 2:
        return 4

    elif value == 3:
        return 9

    elif value == 4:
        return 16

    elif value == 5:
        return 25

    elif value == 6:
        return 36

    elif value == 7:
        return 49

    elif value == 8:
        return 64

    elif value == 9:
        return 81

    elif value == 10:
        return 100

    else:
        return value * value
    # pylint: enable=too-many-return-statements


def cubed(value):
    """Just cubes a number."""
    return value * squared(value)
```

Running `black` (installed from `HEAD` as in #30) does two "strange" things:

- Moves the `# pylint: enable` comment to just before the next function
- Adds 2 empty lines in between the two functions (so there is now 4, instead of 2)

```
$ venv-HEAD/bin/black too_many_returns.py
reformatted too_many_returns.py
```

See the diff

```diff
diff --git a/too_many_returns.py b/too_many_returns.py
index b7251d5..3b65b6c 100644
--- a/too_many_returns.py
+++ b/too_many_returns.py
@@ -36,9 +36,11 @@ def squared(value):
 
     else:
         return value * value
-    # pylint: enable=too-many-return-statements
 
 
+
+
+# pylint: enable=too-many-return-statements
 def cubed(value):
     """Just cubes a number."""
     return value * squared(value)
```

----

I realize the `pylint: enable...` at the end isn't needed, since the disable is scoped to the function, but I figured you'd still want to see this surprising reformatted result.

**Comment by ambv** [comment]
This is the same issue as #16. Funnily they're consecutive powers of two.

**Comment by dhermes** [comment]
@ambv Happy to close this, though I think the added newlines makes this slightly different than #16?

**Comment by dhermes** [comment]
Thanks a lot @ambv!
