### ISSUE TITLE
BufWritePost vs BufWritePre

### ISSUE THREAD

**Issue by davidszotten** [ambv/black#321]
Hi,

the readme section on vim recommends `BufWritePost`. Does `BufWritePre` not make more sense or am i missing something?

**Comment by hugovk** [comment]
That was added in https://github.com/ambv/black/pull/255 by @mahmoudhossam.

@mahmoudhossam What do you think?

**Comment by mahmoudhossam** [comment]
I really don't have an opinion on this, either works.

`BufWritePost` just lets you review the changes before saving again, which makes the changes "undoable".

But of course if I'm wrong and the same happens with `BufWritePre` then definitely use that.

**Comment by davidszotten** [comment]
to add some context: my workflow is 
1) edit some code
2) write the file
3) add/commit 

with a post-hook i end up committing the unformatted version (unless i :write again)

**Comment by ambv** [comment]
@davidszotten, I think your suggestion makes sense to advertise `BufWritePre` rather than the other. The point is you shouldn't have to review auto-formatting changes.
