### ISSUE TITLE
INTERNAL ERROR: Black produced invalid code: f-string expression part cannot include a backslash

### ISSUE THREAD

**Issue by Chronophylos** [ambv/black#322]
Operating system: `Windows 10 1803`
Python version:  `Python 3.6.4 :: Anaconda, Inc.`
*Black* version: `black, version 18.5b0`
Does also happen on master: Yes

Full error message: `cannot format main.py: INTERNAL ERROR: Black produced invalid code: f-string expression part cannot include a backslash (<unknown>, line 129)`

[Log from 18.5b0](https://github.com/ambv/black/files/2085780/blk_qqujvtxx.log)
[Log from master](https://github.com/ambv/black/files/2085785/blk_klfgjh_c.log)

**Comment by ambv** [comment]
Good catch and sorry for your trouble!

@zsol, this is when attempting to normalize string quotes on something like:
```py3
print(f'Loading \'{colored(modpack.name, "green")}\'')
```

It produces this which is invalid:
```py3
print(f"Loading '{colored(modpack.name, \"green\")}'")
```
