### ISSUE TITLE
Chained method calls quite unreadable

### ISSUE THREAD

**Issue by dcramer** [ambv/black#323]
*Black* version: 18.6b2

I find this vomit-worthy:

```diff
--- a/tests/zeus/artifacts/test_checkstyle.py
+++ b/tests/zeus/artifacts/test_checkstyle.py
@@ -12,11 +12,9 @@ def test_result_generation(sample_checkstyle, default_job):
     handler.process(fp)

     results = list(
-        StyleViolation.query.unrestricted_unsafe().filter(
-            StyleViolation.job_id == default_job.id
-        ).order_by(
-            StyleViolation.filename.asc(), StyleViolation.message.asc()
-        )
+        StyleViolation.query.unrestricted_unsafe()
+        .filter(StyleViolation.job_id == default_job.id)
+        .order_by(StyleViolation.filename.asc(), StyleViolation.message.asc())
     )
```

**Comment by dcramer** [comment]
Recommendation:

- Keep them newline separated similar to the original (probably hard)
- Indent each follow-up line
- ???

**Comment by ambv** [comment]
That's intentional and an implementation of https://github.com/ambv/black/issues/67. Read there for specifics.

Specifically for use like yours (with ORMs), it's cleaner to specify subsequent calls with a leading dot. It's symmetrical to, say, list comprehensions:
```py3
results = [
    element
    for element in collection
    if X
    if Y
]
```

**Comment by dcramer** [comment]
Ok fine :(

FWIW JS has this everywhere, and anecdotally I believe the standard is indent for following lines and it has made it quite readable.

**Comment by ambv** [comment]
The indentation in JavaScript is to that you can see where the chain *ends*. In Python we require parentheses around the call chain so we don't need additional indentation to make it explicit what's going on. We don't indent other operators (+/-/and/or and so on) either.
