### ISSUE TITLE
Long list of ints, floats, ...

### ISSUE THREAD

**Issue by etienned** [ambv/black#326]
Operating system: macOS 10.12.6
Python version: 3.6.5
*Black* version: 18.6b2
Does also happen on master: probably because it's the expected behaviour

Black reformat this:

```python
def link_related():
    amounts = [
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 5
    ]
```
as that:

```python
def link_related():
    amounts = [
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        1,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        2,
        3,
        3,
        3,
        3,
        4,
        4,
        5,
    ]
```

I know it's the expected behaviour and I understand and agree in general with the rule (one item by line if it doesn't fit) but I find the results less then optimal in those cases where you have a list of integers, floats, etc. (data tables). Unfortunately I do not have a good suggestion for the moment but my idea was to open the reflection.

**Comment by ambv** [comment]
I agree with you that it doesn't look particularly nice. However, that's one of the things that are not possible to get right deterministically. There's plenty of situations where this style doesn't look bad even with "long lists of ints", like (real-world example):
```py3
config = some.Structure(
    globalMap={
        103310322020340: [
            100000031211103,
            101042000320420,
            100100001202021,
            112320301100420,
            110101024402203,
            112001202000203,
            112101112010031,
            102130400200010,
            100401014300441,
            103000401422033,
        ],
        110040120003212: [
            114413100031332,
            102101001412002,
            100210000032130,
            214000110100040,
            103031420121210,
            112114222301010,
            110133330100020,
            100001001203011,
            102210220202130,
            102200120234012,
        ],
        244402003102200: [
            110212012114431,
            100001140020000,
            100012101223021,
            110031301200114,
            114002020044120,
            100021004302202,
            102202200240222,
            114102010220042,
            102021301441201,
            104103102103201,
        ],
        ...
    },
)
```

If you have lists of ints that have a specific shape, you will want to use `# fmt: off` on those.

**Comment by etienned** [comment]
Thanks for the answer and sorry for the noise. Somehow I managed to wrongly understand the documentation about `# fmt: off`. I was with the impression that black didn't support this kind of deactivating comments. It was probably too late.
