### ISSUE TITLE
fmt:on/off placed asymmetrically ends up with a cryptic exception

### ISSUE THREAD

**Issue by virtuald** [ambv/black#329]
Operating system: Fedora Linux 28
Python version: 3.6
Black version: 18.6b2
Does also happen on master: Yes

```
something = {
    # fmt: off
    'element': 1,
}
# fmt: on

something_else = 1

```
Results in the following output

```
$ black black_error.py 
error: cannot format black_error.py: 10
All done! 💥 💔 💥
1 file failed to reformat.
```

Expected something telling me which line the error occurred on.

**Comment by ambv** [comment]
Agreed! As a workaround in the mean time, put `# fmt: on` and `# fmt: off` on the same indentation level, like:
```py3
# fmt: off
something = {
    'element': 1,
}
# fmt: on

something_else = 1
```
