### ISSUE TITLE
Numpy-style indexing gets "mushed" (i.e. loses a space)

### ISSUE THREAD

**Issue by dhermes** [ambv/black#33]
For the repro file `its_science.py`

```python
def first_column1d(values):
    """First column, as a 1D array."""
    return values[:, 0]


def first_column2d(values):
    """First column, but still a 2D array."""
    return values[:, 0:1]
```

Running `black` (installed from `HEAD` as in #30)

```
$ venv-HEAD/bin/black its_science.py
reformatted its_science.py
```

changes the "exotic" slice argument:

```diff
diff --git a/its_science.py b/its_science.py
index f3c4a8b..3a5dba0 100644
--- a/its_science.py
+++ b/its_science.py
@@ -5,4 +5,4 @@ def first_column1d(values):
 
 def first_column2d(values):
     """First column, but still a 2D array."""
-    return values[:, 0:1]
+    return values[:,0:1]
```

----

PS @ambv This is my fourth and last issue (for now) and it's just "wrong" things I encountered when running this on a large codebase of mine. I am **SOOOOO** happy you have created `black` and look forward to evangelizing it in the community.

**Comment by ambv** [comment]
This is now fixed and will be part of 18.3a2. Thanks for all your reports!

**Comment by dhermes** [comment]
Awesome response time, you rock!

**Comment by dhermes** [comment]
@ambv It seems the fix didn't cover all cases. Given `moar_numpy.py`:

```python
def delta(points):
    return points[:, 1:] - points[:, :-1]
```

running (from `HEAD`)

```
$ venv/bin/black moar_numpy.py
reformatted moar_numpy.py
```

the 2nd slice gets "mushed":

```diff
diff --git a/moar_numpy.py b/moar_numpy.py
index d9ba020..e36b529 100644
--- a/moar_numpy.py
+++ b/moar_numpy.py
@@ -1,2 +1,2 @@
 def delta(points):
-    return points[:, 1:] - points[:, :-1]
+    return points[:, 1:] - points[:,:-1]
```

**Comment by ambv** [comment]
Alright, will add a test with this example, too. Missed today's release but there should be another one in a few days tops :-)

**Comment by ambv** [comment]
This should solve your problem once and for all: https://github.com/ambv/black/commit/21c49d942264a1f36858036a9235e5ecb337bf4c

**Comment by dhermes** [comment]
Thanks for another quick fix! I just tried installed the latest

```
$ git log -1 --pretty=%H
21c49d942264a1f36858036a9235e5ecb337bf4c
$ venv/bin/pip install .
```

and re-ran it on my mostly converted codebase and it seems there is a regression in how slices are handled. Consider  `moar_numpy.py`

```python
def first_row1d(points):
    return points[0, :]
```

Running

```
$ venv/bin/black moar_numpy.py
reformatted moar_numpy.py
```

yields

```diff
diff --git a/moar_numpy.py b/moar_numpy.py
index 4a057d6..f1efb82 100644
--- a/moar_numpy.py
+++ b/moar_numpy.py
@@ -1,2 +1,2 @@
 def first_row1d(points):
-    return points[0, :]
+    return points[0,:]
```

I promise I'm not trying to be difficult :grinning:

**Comment by ambv** [comment]
Sigh...

**Comment by ambv** [comment]
😂

**Comment by ambv** [comment]
Is this the last form? If you have any other uses of tuple indexing in your code, list them all please so I can add tests in one go.

**Comment by dhermes** [comment]
Sure thing. I did a `git grep [` to find every use of slicing in the [project][1] I've been running `black` on and found the following comprehensive-ish list of all "slice types":

```python
mat[0, 4]
mat[0, :]
mat[:, i]
mat[0, :2]
mat[:N, 0]
mat[:, 1:3]
mat[:2, :4]
mat[2:4, 1:5]
mat[4:, 2:]
mat[:, (0, 1, 2, 5)]
mat[0, [0]]
mat[:, [i]]
mat.flat[d::d + 1]
mat[:c, c - 1]
mat[1:c + 1, c]
mat[-(c + 1):, d]
mat[:, l[-2]]
mat[:, ::-1]
vec[np.newaxis, :]
```

I "normalized" the list. I'm sure there are lots more ways that people use slices in the wild. I also have other projects with 3D arrays, so slices like `mat[:, :, j]` are common.

[1]: https://github.com/dhermes/bezier

**Comment by dhermes** [comment]
Thanks again!
