### ISSUE TITLE
black unable to decide between two formats, cycles between them.

### ISSUE THREAD

**Issue by brunns** [ambv/black#337]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: OSX 10.12
Python version: Target code for version 2.7, Black running on 3.6/
*Black* version: 18.5b1

Given this code:

```python
    parser.add_argument(
        "-v",
        "--verbosity",
        action="count",
        default=0,
        help="Specify up to three times to increase verbosity, "
        "i.e. -v to see warnings, -vv for information messages, "
        "or -vvv for debug messages.",
    )
```

Black is cycling between two indentation levels for the 2nd two lines of the help parameter, either aligning them below the `help=`... or below the `"Specify`...

**Comment by zsol** [comment]
Hmm, I can't reproduce this on 18.5b1 or on master. Can you give some more context please? Command line args, bigger code snippet, etc

**Comment by brunns** [comment]
Sorry, my mistake. The issue is that Black and PyCharm are fighting over this, it's not Black's problem.
