### ISSUE TITLE
black inserts 'unnecessary' newline for consistency

### ISSUE THREAD

**Issue by svisser** [ambv/black#35]
Operating system: Mac OS X 10.12.5
Python version: 3.6.1
Black version: 18.3a2
Does also happen on master: Yes

```python
def example(session):
    result = session.query(models.Customer.id).filter(
        models.Customer.account_id == account_id,
        models.Customer.email == email_address,
    ).order_by(
        models.Customer.id.asc(),
    ).all()
```

becomes:

```python
def example(session):
    result = session.query(models.Customer.id).filter(
        models.Customer.account_id == account_id, models.Customer.email == email_address
    ).order_by(
        models.Customer.id.asc(),
    ).all(
    )
```

Although the newline in `all()` is consistent with the other calls above it, I think it's unlikely that the code would be written this way normally.

**Comment by svisser** [comment]
I see now that this matches the philosophy described in the README (to make diffs as small as possible). If so then feel free to close this issue.

**Comment by ambv** [comment]
I actually have a check *not* to insert a newline like you are seeing in the last line:
https://github.com/ambv/black/blob/master/black.py#L1199-L1209

I guess it doesn't work quite right. Your intuition was correct, this is not nice formatting. But almost! :-)

I'll fix this for you.

**Comment by ambv** [comment]
This is now fixed, thanks for your report!

**Comment by svisser** [comment]
Thanks for fixing it!
