### ISSUE TITLE
on demand mode of format, but also run the check logic

### ISSUE THREAD

**Issue by gaborbernat** [ambv/black#353]
This is an integration issue with tox. Ideally, we would like to have a single common environment for both the CI check that format looks good; and also format it if it does not. Achieving this at the moment is not possible. I need to create a tox environment to check if the code is formatted in CI, and another one that the user can use to do the formatting. 

What I need to do now:

```bash
tox -e format  # this will format the code-base
tox -e format-check  # this will just return a fail return code, if the formatting fails
```

Use the first locally, use the second inside CI.

What I would like to do:

```bash
tox -e format  # this will format the code and return 0 if no-chance was done, 1 otherwise 
```

Use ``format`` both locally and in the CI.

Note because tox stops at the first command failed there's no cross platform way to achieve the above in a single env:

```ini
commands = black folder
           black folder --check
# this way the check always passes

commands = black folder --check
           black folder
# this way the formatting is not done if bad format
```

**Comment by jgirardet** [comment]
https://github.com/ambv/black/issues/285

**Comment by gaborbernat** [comment]
Yeah, I read that. But I'm not saying to change what the default behaviour is, but provide a way to do it. In that case, only tools that want this behaviour can explicitly opt-in.

**Comment by jgirardet** [comment]
Ok, I read to fast.
You can check the stderr message to do it or --diff and apply if  stdout is not empty.

**Comment by gaborbernat** [comment]
@jgirardet I see you haven't used tox before. Neither of those is usable in that context. You don't have access to the stdout/stderr. And tox is not a plugin, it's just a way to invoke your commands. I would have the same issue with calling the format with a make target in both CI and locally.

**Comment by jgirardet** [comment]
@gaborbernat I used it but, It didn't guess it was implicit to your question.

**Comment by ambv** [comment]
I don't understand what the problem is. `tox -e format-check` has a different purpose than `tox -e format`. In the first case, you want to fail if the file isn't already clean. In the second case, you want to fail only if Black fails to format your file.

Why do you need both to be one command?

**Comment by ambv** [comment]
Locally you always want to fix. What's the value behind a non-zero return value?

Remotely you never want to fix as writing the file back is a waste of time. This is why we have --check for CI.

It seems to me like you are trying to combine those separate use cases into one.

**Comment by gaborbernat** [comment]
While remotely is a waste of time, generally not too expensive (the formatting takes negligible time compared to the test suite). The benefit of having it as one is that you have one single configuration for these. Instead of:

```ini
[testenv:format]
description = ensure the source code is correctly formatted
basepython = python3.6
commands = black package tests  setup.py

[testenv:format-check]
description = check the source code is correctly formated
basepython = python3.6
commands = black --check package tests setup.py
```

I can just have:

```ini
[testenv:format]
description = ensure the source code is correctly formatted
basepython = python3.6
commands = black package tests setup.py --check-return
```

The main benefit is now I have a single environment that checks and handles formatting, and I need to specify the configurations to black also in a single place. Black does not have a configuration file, needing to specify all the params on the command line as flags. If I need two separate configs for these two I needlessly increase the config size, and also open the door for the two getting out of sync. E.g. I can now format one set of files locally, and check a different set of files remotely. Generally is nice to minimize the ways I can mess up; merging the two offers this with some negligible performance drawback (formatting the files in the CI env - this does no harm).

**Comment by ambv** [comment]
Read the README's section called pyproject.toml. Look at Black's pyproject.toml for inspiration.

In general, I don't feel like the minor convenience in configuration warrants another command-line option.

**Comment by gaborbernat** [comment]
Sad to hear but understood, seems your unwilling to compromise on this. So users are forced to create a pyproject.toml now. It still creates the annoyance of needing to have different config for local and CI which I find an annoyance. Users should be able to run ci locally.

**Comment by gaborbernat** [comment]
@ambv note that you still have duplication with the ``pyproject.toml`` e.g. the black version which may get out of sync between environments.

```
[testenv:format]
description = ensure the source code is correctly formatted
basepython = python3.6
commands = black package tests  setup.py

[testenv:format-check]
description = check the source code is correctly formated
basepython = python3.6
deps = {[testenv]deps}
       black == 18.6b2
commands = black --check package tests setup.py
```
