### ISSUE TITLE
Black and pycodestyle disagree about whitespace before :

### ISSUE THREAD

**Issue by dmerejkowsky** [ambv/black#354]
Operating system: Debian 9
Python version: python 3.6
*Black* version: 18.6b2
Does also happen on master: yes

Steps to reproduce:

```python
# in foo.py 
a[len(b) :]
```

```
$ black --diff foo.py
All done! ✨ 🍰 ✨
1 file left unchanged.
$ pycodestyle foo.py
foo.py:1:9: E203 whitespace before ':'
```

This is unfortunate because I use `pycodestyle` for CI (not everyone can/want use to black yet), but I use black in my editor to format on save ...

Of course, a workaround is to use `# fmt: off`, but I still think this is a bug in black and should be fixed.

**Comment by JelleZijlstra** [comment]
pycodestyle is breaking PEP 8 here; see https://github.com/ambv/black#slices.

**Comment by ambv** [comment]
Turn off E203 and W503 and you can continue to use Black and pycodestyle.

**Comment by dmerejkowsky** [comment]
> pycodestyle is breaking PEP 8 here

Woops, my bad. Sorry for the noise

**Comment by simonwiles** [comment]
For future readers (including, no doubt, me the next time I forget), @JelleZijlstra's link is now https://black.readthedocs.io/en/stable/the_black_code_style.html#slices.

**Comment by antgel** [comment]
That link in 2021: https://black.readthedocs.io/en/stable/the_black_code_style/current_style.html#slices

Well, it is beta... ;)
