### ISSUE TITLE
Please add the link to readthedocs at top of project page

### ISSUE THREAD

**Issue by Mariatta** [ambv/black#364]
It would be nice to have the link to http://black.readthedocs.io/en/latest/ at the top of the GitHub project page: see screenshot of where it can be added.
<img width="1018" alt="screen shot 2018-06-18 at 3 23 33 pm" src="https://user-images.githubusercontent.com/5844587/41565558-216b2ef4-730c-11e8-8733-92dd34339336.png">

Project admin should see the "Edit" button right there and add the link.

Thanks!

**Comment by ambv** [comment]
Done, thanks for letting me know :-)
