### ISSUE TITLE
Need an option to disable slicing formatting

### ISSUE THREAD

**Issue by scythargon** [ambv/black#367]
Hi guys! Thank you, finally there is a decent autoformatter! But these whitespaces around slice operator are too unusual for me and my team, is there is an option to disable this or can you add one?
Thanks!

**Comment by scythargon** [comment]
BTW this does not seem to be working currently:
```
Before submitting pull requests, run tests with:

$ python setup.py test
```

**Comment by zsol** [comment]
Hi @scythargon thanks for the kind words :) Black tries to provide as little configurability as possible ([as mentioned in the readme](https://github.com/ambv/black#the-black-code-style)), so it's very unlikely that such an option is going to be considered.

The spacing inside slices are in line with what PEP-8 suggests, which was the source of inspiration. Having said that, it's not impossible to change how Black formats these (i.e. we're open to iterate on the formatting, see #67 as an example), but any change would need to have significant, obvious advantages over the current one. You would need to come up with these and explain them.

As for the tests not working, is there any error message you're getting? This works fine for me on master.

**Comment by scythargon** [comment]
Hey @zsol , thank you for the quick answer!:)
Right, tests work if run like this (you do it a bit different in CI), just checked with the clean virtualenv and `pip install -e .`, sorry.
For the slice formatting advantages - well there are non except that it will be hard for many people to adopt this. Image how much time and nerves you can save the for the people (our fellow developers and not-so-fellow customers, managers and product owners) around the globe upon arguing if they should use `black` because of awesome autoformatting overall or if they should not only because the spaces around the slice operators look too unusual for some dense developers in the team or rise too much interruptions of broken CI build if somebody forgets (or just too stubborn again) to install pre-commit hooks:)

**Comment by ambv** [comment]
> For the slice formatting advantages - well there are non except that it will be hard for many people to adopt this.

Why is it hard to adopt? The slice formatting it to the letter of PEP 8.

> if somebody forgets (or just too stubborn again) to install pre-commit hooks

This is not something we should optimize for.

**Comment by ambv** [comment]
Closing as this is not a planned feature.
