### ISSUE TITLE
Black installs on Python 3.5 and older from the wheel

### ISSUE THREAD

**Issue by xiaomingdaily** [ambv/black#37]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: ubuntu16.04
Python version: Python 3.5.2 
Black version:
Does also happen on master: 

after I install black  by using  `pip3 install black` , 
and execute command `black`, error occur.

----
root@leguproject001:~/Pocsuite# black
Traceback (most recent call last):
  File "/usr/local/bin/black", line 7, in <module>
    from black import main
  File "/usr/local/lib/python3.5/dist-packages/black.py", line 72
    sources: List[Path] = []
           ^
SyntaxError: invalid syntax

**Comment by ambv** [comment]
Hi Xiaoming! Black requires Python 3.6+. Looks like the uploaded package for some reason doesn't state this clearly and installs on any Python 3 version. I will have to look into that.

**Comment by ambv** [comment]
I don't quite know what information in setup.py suggests to `setup.py bdist_wheel` that this is a package that will run on any Python 3. I am specifying `python_requires=` after all.

**Comment by iboates** [comment]
I was having a similar issue when I mistakenly installed the Ubuntu pre-commit snap package. It was for some reason always then trying to run in a Python 3.5 environment. Apparently you don't need this. Uninstall it and just install the Python package. Make sure to open a new terminal first for the changes to take effect.
