### ISSUE TITLE
ENH: incremental changes to modify only code neighboring already changed lines

### ISSUE THREAD

**Issue by mattip** [ambv/black#370]
Idea: allow running black with a `-n --dry-run=filename` option and store the resulting changeset. Then allow using this in a subsequent run to only update newly found changes.

Rational: In a workflow on an established managed repository, this would allow running black incrementally, reformatting only parts of the code that have been changed, minimizing git churn and blame lines.

**Comment by ambv** [comment]
This is something we explicitly don't support. Incremental style changes are against PEP 8's philosophy of staying consistent within a file. They also mix formatting changes with semantic changes, making review harder than it needs to be. See https://github.com/ambv/black/issues/134 for a longer explanation.

Reformat your entire project in one go. Then there is a single commit that is trivial to omit using `git hyper-blame` or simply by using `git blame $BLACK_COMMIT^ -- $FILE`. It's a cleaner approach than trying to smear adoption over time.

See also: https://github.com/ambv/black/issues/320

**Comment by wbolster** [comment]
fyi, i wrote https://github.com/wbolster/black-macchiato

**Comment by akaihola** [comment]
Also FYI, I wrote [darker](https://github.com/akaihola/darker) for applying Black formatting only to lines which have changed in the Git working tree since the last commit.
