### ISSUE TITLE
Revisit not using Pythonic single quotes

### ISSUE THREAD

**Issue by cas--** [ambv/black#373]
I was considering letting black format the project code but enforcing double-quotes is a major red flag and honestly shocked by this decision. 

Single quotes are Pythonic and have become the defacto standard in recent years, many code checkers (e.g. [flake-quotes]) and standards (e.g. [Plone]) default/request single quotes. Just because other programming languages use double is not a reason to try to strongarm a different practice onto Python codebases. 

Typing single quotes are faster due to not needing to use shift.

It will convert huge swaths of project code for no benefit and negatively effect code history. I know this because I converted from double to single for a large project and was much harder to review code history. Was any consideration made for the number of Python projects using double or single quotes?

You say this project is still in beta so you still have time to change this. Just look at the responses in #118, the community is not happy with this decision, giving quite valid reasons. Skipping checking the quotes is not a good solution as it will result in mixed quotes which is much worse.

I am certainly not asking for the arbitrary mix of double and single depending on intention. Double is only reserved for docstrings or where a single quote is needed in a string.

Please just enforce single quotes as the Python community has mutually agreed upon.

[Plone]:https://docs.plone.org/develop/styleguide/python.html#quoting
[flake8-quotes]:https://github.com/zheller/flake8-quotes

**Comment by ambv** [comment]
There is `--skip-string-normalization` if you feel strongly about this. Most people don't. We won't be changing the default behavior.

**Comment by jaraco** [comment]
Another point in favor of preferring single quotes to double quotes is that's what Python itself prefers:

```
>>> print(repr("my string"))
'my string'
```

In my opinion, that's the strongest argument for why black should _prefer_ single quotes.

**Comment by guitarmanvt** [comment]
The main advantage of using a code formatter is that it forces the same formatting. The main advantage of using `black` _in particular_ is that I can blame _you guys_ for the arbitrary choices you make, and it's no longer _"my fault."_

Personally, the decision to use double-quotes seems really "pig-headed" to me (for ignoring Python historical convention), but as anyone can see, the `black` team has provided the option to `--skip-string-normalization` (for those who are "pig-headed" in the other direction). (Experienced developers will recognize my alternate spelling of "opinionated" in this paragraph. ;) )

Pragmatically, the benefit of having consistent, enforced code formatting outweighs any trivial tastes I or my team have developed over the years. Will I use `black`? Absolutely. Will I accept all its arbitrary choices? Probably some day.

Until then, it's "good enough." Well done, `black` team. Don't let people give you grief. (Even about double-quotes.)

**Comment by ssbarnea** [comment]
The skip option is clearly useful to make adoption easier by delaying normalization for later.

I was wondering  myself why double vs single and I found some explanation that makes sense:
* in English language is more likely to need to use single quote inside a string than double, see `"That's good example?"`
* YAML and JSON also standardized on double ones.
* Most common quoting in literacy is double quotes, not single ones, right?

So there are some reasons.

When it comes to `repr()`, how about changing it to default to double quotes? Would this break the world?

**Comment by psavery** [comment]
Unfortunately, Black's insistence to not add a single quote option is a deal breaker for me as well. I work on several projects that settled on using single-quotes a long time ago, and we strive for consistency. Changing our projects from single quotes to double quotes will not happen easily. And, because we want to enforce single quotes, `--skip-string-normalization` will not work for us.

Thus, I literally cannot use Black for the time being.

**Comment by hugovk** [comment]
@psavery You can use `pre-commit` to run [`double-quote-string-fixer`](https://pre-commit.com/hooks.html) ([examples](https://github.com/search?l=YAML&q=double-quote-string-fixer&type=Code)):

> This hook replaces double quoted strings with single quoted strings

You can use it to chain the Black and `double-quote-string-fixer` runs into a single command, and even if you don't like Git pre-commit hooks, you can use it as a CLI lint tool: `pre-commit run all-files`.

**Comment by richardARPANET** [comment]
It seems single quotes are most widely used and agreed on in the Python community. Judging by many years of experience along with the various issues listed on this repo.

Whatever the reason for it is irrelevant, more people prefer single. 

It's a shame since @ambv wrote this little library then he gets to just wade in and close every issue about it saying in a round-about way "I personally prefer double quotes so no thanks". How a project with such a dictatorial regime gets listed under "https://github.com/psf/" is beyond me.

Maybe this will improve in the future :crossed_fingers:

**Comment by piotr-dobrogost** [comment]
> Typing single quotes are faster due to not needing to use shift.

This.

**Comment by ambv** [comment]
This is a bad argument. You are using an auto-formatter. Type whatever is faster on your keyboard and let the tool auto-format it for you.

There are no additional points for pre-formatting code manually to look exactly as Black would format it.

There are no additional points for hanging onto closed issues, either. I'm locking this.
