### ISSUE TITLE
The check doesn't accept max lenght of row.

### ISSUE THREAD

**Issue by Pajinek** [ambv/black#375]
Hi, I run black on my project `black /app --check -l 120 --exclude venv` and all code was reformated. But when I run --check I received messsage that  the files would be reformated. It looks that the `check` doesn't accept max lenght of row.

Operating system: 
Python version: 
*Black* version: black::18.6b4
Does also happen on master:

```
black /app --pyi -l 120 --exclude venv 
black /app --check -l 120 --exclude venv 
```

**Comment by ambv** [comment]
Your problem is that you missed --pyi in your --check call.

**Comment by ambv** [comment]
I'm not sure why you'd use --pyi in the first place though. Black will reconize .pyi files just fine by default. Using --pyi means ALL found Python files are reformatted like .pyi files. Is this really what you want?

**Comment by Pajinek** [comment]
For my case is not import  --pyi. I wanted to check files with 120 max length. It is the point. But the command doesn't accept parameter "-l".

**Comment by ambv** [comment]
It does, which is why I'm asking what you're trying to do. Look at the code, --check simply means we don't write the file back and return 1 if there are changes. It's the same code path otherwise.

**Comment by ambv** [comment]
Can you re-run without --pyi anywhere but with --verbose?

**Comment by zsol** [comment]
I'll close this for now but @Pajinek let us know if you manage to reproduce it without using `--pyi` anywhere
