### ISSUE TITLE
Does black provide module usage?

### ISSUE THREAD

**Issue by ocavue** [ambv/black#380]
*this issue is a feature request*

Provide black as a python model just like [yapf - Example as a module](https://github.com/google/yapf#example-as-a-module). I didn't find something related in document and github issues page. If someone has already posted it then you can close this issue.

**Comment by zsol** [comment]
Hi @ocavue this has been discussed in #292. You can already use black by importing it and using the high level functions which are unlikely to change. Something nicer and more well documented is going to come before we go out of beta.

**Comment by zsol** [comment]
There's also some barebones docs here: http://black.readthedocs.io/en/stable/reference/reference_functions.html

**Comment by ocavue** [comment]
Thanks. Closing this issue.
