### ISSUE TITLE
Unnecessary empty liens around functions inside an if statement

### ISSUE THREAD

**Issue by expobrain** [ambv/black#384]
Operating system: OSX 10.13.5
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master: yes

When formatting this code:
```
if x:
    def y():
        pass
else:
    def z():
        pass
```

`black` adds some unnecessary empty lines in around then functions:

```
if x:

    def y():
        pass


else:

    def z():
        pass
```

**Comment by zsol** [comment]
Looks like this is a dupe of #377. Thanks for reporting!
