### ISSUE TITLE
`# fmt: off` directly before `yield` only affects the `yield`

### ISSUE THREAD

**Issue by matejcik** [ambv/black#385]
this is on current master:

```python
# fmt: off
yield    "hello"
yield    "world"
# fmt: on
```
formats to:
```python
# fmt: off
yield    "hello"
yield "world"
# fmt: on
```

The bug seems to be avoided by putting any (afaict) statement after the `# fmt: off` declaration, like:
```python
# fmt: off
...
yield    "hello"
yield    "world"
# fmt: on
```

**Comment by zsol** [comment]
Thanks for reporting, this is definitely a bug, I'll take a look
