### ISSUE TITLE
Inline pylint comment tags don't move how they should

### ISSUE THREAD

**Issue by nixjdm** [ambv/black#386]
Operating system: Ubuntu 18.04 LTS
Python version: Python 3.6.4 :: Anaconda, Inc.
*Black* version: black, version 18.6b4
Does also happen on master: yes

-------

Problem: On long lines that get reformatted, inline comments used to tell pylint to ignore certain rules simply get moved to the end of the reformatted code. This is not  necessarily the new appropriate place for the comment.

E.g.:

```python
exec('print("printexectest that exceeds line limit aaaaaaaaaaa.")')  # pylint: disable=exec-used
```
currently reformats to
```python
exec(
    'print("printexectest that exceeds line limit aaaaaaaaaaa.")'
)  # pylint: disable=exec-used
```

This no longer satisfies pylint. That comment should be on the first line, with the `exec`. Thankfully the comment can be manually moved and black allows that, allowing the code to then satisfy pylint.

I don't see an easy way to fix this unfortunately, since I think that would necessitate knowing pylint's rules to make choices. That's perhaps possible, but increases the scope of black a lot. Nonetheless, it is a hurdle for adoption of larger projects. Perhaps there's another solution I don't see.

**Comment by kingmoduk** [comment]
[ @nixjdm  ](url)

**Comment by zsol** [comment]
Hey @nixjdm your assessment is correct in that this is something of a hurdle for adoption and there's no easy & clean way to address this, as black would need to understand comment semantics. Something similar is tracked in #195 so I'll close this.

**Comment by nixjdm** [comment]
Thanks @zsol. I didn't see that issue about the flake8 comments. It is very similar.
