### ISSUE TITLE
Fails when importing __future__ as renaming it

### ISSUE THREAD

**Issue by horta** [ambv/black#389]
Operating system: Darwin horta-ml 17.6.0 Darwin Kernel Version 17.6.0
Python version: Python 3.6.6 :: Anaconda custom (64-bit)
*Black* version: 18.6b4
Does also happen on master: yes

This works:
```python
# test1.py
from __future__ import absolute_import
```

This does not work:
```python
# test2.py
from __future__ import absolute_import as _absolute_import
```

Output:

> error: cannot format test2.py:
> All done! 💥 💔 💥
> 1 file failed to reformat.

**Comment by zsol** [comment]
Looks like this is a bug in how black processes future imports. Thanks for reporting, will fix!
