### ISSUE TITLE
Document missing trailing comma on function calls with unpacking on non-3.6 files

### ISSUE THREAD

**Issue by sanjioh** [ambv/black#39]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Mac OS 10.13.3
Python version: 3.6.4
Black version: 18.3a2
Does also happen on master: Yes

To answer the last question, follow these steps:
* create a new virtualenv (make sure it's the same Python version);
* clone this repository;
* run `pip install -e .`;
* make sure it's sane by running `python setup.py test`; and
* run `black` like you did last time.

Hi, and a huge thank you for this project!
I think I might have found a glitch in how function calls are formatted.

```
func_1(
    first_argument_with_a_very_long_name,
    second_argument_with_a_very_long_name,
    third_argument_with_a_very_long_name,
)
func_2(
    *first_argument_with_a_very_long_name,
    second_argument_with_a_very_long_name,
    third_argument_with_a_very_long_name
)
```

When an argument has the unpacking notation, black removes the trailing comma from the last one.
Is this intended behaviour?

Thanks again!

**Comment by ambv** [comment]
This is missing because this style of trailing comma is not safe pre-3.6. If you want this, just put that trailing comma yourself, Black will keep it.

**Comment by ambv** [comment]
This behavior was introduced in https://github.com/ambv/black/commit/f71fc7811e6c6e5412152dee785f9d3d12722c56 and is documented there in the commit message. We need to put this in the README.

**Comment by sanjioh** [comment]
Great, thanks for the clarification.

**Comment by ambv** [comment]
Fixed.
