### ISSUE TITLE
Line break on list index in long assignment statement

### ISSUE THREAD

**Issue by dgouldin** [ambv/black#391]
Python version: 3.6.5
Black version: 18.6b4
Does also happen on master: yes

When a list index operation happens on right side of an assignment statement that is over the character limit, black line breaks on the index operation, which IMO is awkward to read.

Before black:
```python
some_list = ["foo"]
this_is_a_really_long_variable_name_just_to_illustrate_the_boundary_condition = some_list[0]
```

After black:
```python
some_list = ["foo"]
this_is_a_really_long_variable_name_just_to_illustrate_the_boundary_condition = some_list[
    0
]
```

My personal preference (which is obviously just a preference):
```python
some_list = ["foo"]
this_is_a_really_long_variable_name_just_to_illustrate_the_boundary_condition = \
    some_list[0]
```

If this is intended behavior, is there a PEP-related reason not to use `\` in this case, or is it style choice?

**Comment by zsol** [comment]
Hey @dgouldin, thanks for reporting!
Yes, this is definitely a bug in black. #330 and #236 talk about this already, so I'll close this out. Feel free to comment on those if you want to add more details.

As for the use of `\`: @ambv has a lengthy explanation of why black avoids using it [here](https://github.com/ambv/black/issues/64#issuecomment-375429106), but maybe this really should be in the readme somewhere.

**Comment by zsol** [comment]
#392 for the documentation update
