### ISSUE TITLE
Pre-commit-hook ignores exclude patterns

### ISSUE THREAD

**Issue by Copper-Head** [ambv/black#395]
My team wants to try `black` as a pre-commit hook on a provisional basis, so we run it only on files in one directory of the project as we develop a new feature.

While configuring this, I discovered that `black` [seems to ignore inclusion/exclusion rules completely if it's given a path to a file not a folder](https://github.com/ambv/black/blob/master/black.py#L323). Since the input to a pre-commit hook is a list of modified/created filepaths, all or our lovely inclusion/exclusion rules get ignored completely and that makes us sad :(

I'm not familiar enough with the code to have a good gauge of this, but how much work do you think it would be to add support for this?

Thanks for the cool tool!!
P.S.
Personally, I'd take the leap and format the whole repo, but I'm not alone in this world ;)

**Comment by zsol** [comment]
Hi @Copper-Head 

How are you trying to configure your pre-commit hook? I suggest you create a `pyproject.toml` file where you define your include/exclude rules and then have pre-commit run `black` without any arguments. This will help you preserve consistency as the hook will run on the same things as if anyone just runs `black` manually. This is described in a bit more detail in [the readme](https://github.com/ambv/black#version-control-integration)

**Comment by Copper-Head** [comment]
Thanks for the response!
I am indeed using a `pyproject.toml` file and `black` is even finding it, as I saw when I ran it in verbose mode.

To be clear, here's the structure of my repo (distilled to only the relevant details):
```
repo/
    pkg/
        dir_a/format_me.py
        dir_b/let_me_be.py
    pyproject.toml
    .pre-commit-config.yaml
````
I want to only run `black` on files in `pkg/dir_a`.

- When I run `black pkg` the `pyproject.toml` is loaded and respected, so only files in `dir_a` are formatted
- When I try to commit a file from `dir_b` it still gets formatted even though (when running in verbose mode) `black` reports loading the config file.
- When I run `black -v pkg/dir_b/let_me_be.py`, this file is formatted even though the config is loaded.

Looking at the comment above [this line](https://github.com/ambv/black/blob/master/black.py#L323), I get the impression that this behavior is intended. I.e. if we give `black` a path to a specific file, it ignores all our exclude/include rules.

**Comment by Copper-Head** [comment]
@asottile Thanks for the tip! This is what we ended up doing.

I didn't close this issue in case someone else wants to discuss whether or not the behavior of black that I brought up is desired. However if there are no takers, feel free to close this, the immediate issue on our end has been resolved!

**Comment by zsol** [comment]
I do think this is intentional behavior on black's part, so will close this until someone comes up with a convincing argument to change it :) I think it's useful to be able to explicitly format a single file disregarding the project configuration, vs formatting the entire project

**Comment by Kos** [comment]
Hi! I'm trying out [`pre-commit`](https://pre-commit.com/) on a monorepo with several projects. Looks like I bumped into this issue.

The project layout looks like:

```
repo_root/
	project-a/
		.flake8
		project.toml
		...
	project-b/
		.flake8
		project.toml
		...
```

Some projects have subdirs which are not the app's source files, and they are excluded from linting and blacking via `.flake8` or `project.toml` respectively.

If I run `flake8 project-a/ignored_dir/some_file.py`, then flake8 picks up an `exclude` pattern and doesn't report any errors.

However, `black --check project-a/ignored_dir/some_file.py` in the same situation reports errors in that file.

`flake8`'s behaviour is what I'm expecting; if I'd like to have `black` behave in the same way, should I collect all the `project.toml` exclusion rules and copy them to `pre-commit`, or is there a better way?

**Comment by jnns** [comment]
There's another discussion about implementing this at https://github.com/python/black/issues/438

**Comment by ssbarnea** [comment]
Does anyone knows how to implement multiple exclusions? Appaently pre-commit chokes if exclude receives a list instead of a string.

Using a regex to match all excludes seems a real challenge in some cases, even of people with many years of perl esperience ;)

**Comment by asottile** [comment]
Say you want to exclude both `^foo/` and `^bar/` you can combine them with `|` (naively: `(^foo/|^bar/)`)

You can also mark your regex as verbose and write a multiline regex:

```yaml
exclude: |
    (?x)(
        ^foo/|
        ^bar/
    )
```

**Comment by ssbarnea** [comment]
@asottile I did not say is was impossible, but challanging. I sorted my case after taking care of few escapes.

**Comment by milind-shakya-sp** [comment]
Running `pre-commit run --files` seems to ignore exclude config as well.

**Comment by asottile** [comment]
seems to work for me?

```console
$ pre-commit run black --files setup.py
black....................................................................Passed
$ nano .pre-commit-config.yaml  # here I edit the file
$ tail -5 .pre-commit-config.yaml 
-   repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
    -   id: black
        exclude: ^setup\.py$
$ pre-commit run black --files setup.py
black................................................(no files to check)Skipped
```

unless you're talking about `black`'s exclusion through `pyproject.toml`, etc -- and then yeah that's the same as #438

**Comment by milind-shakya-sp** [comment]
@asottile Just tried it again, seems to work. 👍

**Comment by max-sixty** [comment]
If anyone else comes to this issue from a web search:

Using `force-exclude` in `pyproject.toml` works carries over to pre-commit successfully.

I don't think this is ideal — that running `black` in and outside of pre-commit has different outcomes with `include` or `exclude` configs — but sounds like pre-commit wants to handle listing the files, and black will understandably check a file if it's passed.

**Comment by anuj-scanova** [comment]
Trying to exclude django's migration directories using the following `.pre-commit-config.yml` files but not working

```yml
repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0  # Use the latest stable version
    hooks:
      - id: black
        language_version: python3
        exclude: |
          (?x)(
              ^migrations/
          )
```
