### ISSUE TITLE
something error on Python3.7 and Vim8.1

### ISSUE THREAD

**Issue by jinzk** [ambv/black#396]
I am using vim installed by homebrew on macos. When i upgrade the Python to version 3.7, The vim show some error message on startup. The error message as following

Error detected while processing /Users/alex/.vim/bundle/black/plugin/black.vim:
line  120:
/must>not&exist/foo:1: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
Press ENTER or type command to continue

**Comment by junchenfeng** [comment]
I have the same problem. Now the brew install python defaults to 3.7.

**Comment by zsol** [comment]
Looks like this is an issue tracked in vim: https://github.com/vim/vim/issues/3117
