### ISSUE TITLE
Multiline string formatting. It this intended behavior?

### ISSUE THREAD

**Issue by testvinder** [ambv/black#397]
I was surprised to see Black change this:

```
a = "&SortByValue=priority&SortByOrder=asc" \
    "&IndexToStartPaging={3}" \
    "&NumberOfElementsToShow={2}" \
    "&CacheDurationMinutes=0" \
    "&AllowAlternativeResults=false"
```

to this:

`a = "&SortByValue=priority&SortByOrder=asc" "&IndexToStartPaging={3}" "&NumberOfElementsToShow={2}" "&CacheDurationMinutes=0" "&AllowAlternativeResults=false"
`
I could understand joining it one string. Both are valid but second one looks weird to me. Is this intended? The output also breaks line length rule.

**Comment by gh640** [comment]
I'm not the maintainer and not confident but it seems to be intended.

> Note: don’t use backslashes for formatting or you’ll lose your voting rights.

https://black.readthedocs.io/en/stable/reference/reference_functions.html?highlight=prefix#black.normalize_prefix

PEP 8 says:

> The preferred way of wrapping long lines is by using Python's implied line continuation inside parentheses, brackets and braces. Long lines can be broken over multiple lines by wrapping expressions in parentheses. These should be used in preference to using a backslash for line continuation.

https://www.python.org/dev/peps/pep-0008/#maximum-line-length

So either of the following patterns are recommended for your case, I believe:

```python
a = (
    "&SortByValue=priority&SortByOrder=asc"
    + "&IndexToStartPaging={3}"
    + "&NumberOfElementsToShow={2}"
    + "&CacheDurationMinutes=0"
    + "&AllowAlternativeResults=false"
)
```

```python
a = (
    "&SortByValue=priority&SortByOrder=asc"
    "&IndexToStartPaging={3}"
    "&NumberOfElementsToShow={2}"
    "&CacheDurationMinutes=0"
    "&AllowAlternativeResults=false"
)
```

**Comment by testvinder** [comment]
Thanks a lot for your response @gh640 . My surprise was not that Black corrects the use of backslashes. My surprise was with the output. Your two suggestions seem much better than what Black suggests.

**Comment by zsol** [comment]
Thanks for reporting, this is already tracked under #330 
We're working on it :)

**Comment by sealor** [comment]
I have a similar problem with formatting. IMHO black should at least support multi-lines strings where every line is a real line with a new line character.

Example code and expected result after formatting:
```
a = (
    "@@ -1,2 +1 @@\n"
    "-garbage1\n"
    "-garbage2\n"
    "+Hello World!\n"
)
```
Not intended and formatted code by black:
```
a = "@@ -1,2 +1 @@\n" "-garbage1\n" "-garbage2\n" "+Hello World!\n"
```

**Comment by ichard26** [comment]
@sealor Experimental string processing makes it possible to keep your example split (https://github.com/psf/black/issues/1540), although ESP's future is still TBD.

**Comment by sealor** [comment]
@ichard26 
Thanks! This would be the optimal solution.

I found the following solution for my current case:
```
a = (
    "@@ -1,2 +1 @@\n",
    "-garbage1\n",
    "-garbage2\n",
    "+Hello World!\n",
)
```
(note the `,` at the end of each line)
