### ISSUE TITLE
Black introduces E302 with a Comment at Line 0 and no Imports

### ISSUE THREAD

**Issue by SethMichaelLarson** [ambv/black#40]
Operating system: Debian 9
Python version: 3.6.4
Black version: black.py, version 18.3a2

Black converts this:

```python
# License/Header comment

def includeme(config):
    pass
```
into this:
```python
# License/Header comment
def includeme(config):
    pass
```
which causes this:
```
./compute/storage/__init__.py:14:1: E302 expected 2 blank lines, found 0
```

**Comment by ambv** [comment]
Thanks for your report, I will be dealing with empty lines for the next release!

**Comment by SethMichaelLarson** [comment]
Thanks for the quick turn-around! Do you have a donation link?

**Comment by ambv** [comment]
Thanks for asking! I appreciate that. I don't intend to make money by working on Black.

I invite you to [donate to the Python Software Foundation](https://www.python.org/psf/donations/) instead. This organization protects our trademarks, sponsors development sprints and conferences, and so on.

**Comment by SethMichaelLarson** [comment]
Oh I'm already a donor to PSF. I'll have to increase my donation! :)

**Comment by ambv** [comment]
This is now fixed in 18.3a3! Thanks! ✨ 🍰 ✨

**Comment by nickpresta** [comment]
I'm not sure if this is a regression, or if classes are handled differently, but I have the following code:

```python


# -----
# something
# -----
class FooState:
    YES = "yes"
    NO = "no"
```

which `black` reformats to:

```python
# -----
# something
# -----
class FooState:
    YES = "yes"
    NO = "no"
```

which results in:

```
E302 expected 2 blank lines, found 0
```

Should I open a new issue? Is this expected behavior and `flake8` is just wrong?

**Comment by ambv** [comment]
flake8 is wrong, you don't have to have those pointless empty new lines at the *start* of the file.

**Comment by nickpresta** [comment]
I figured as much. I disabled E302 given I want to let `black` handle all "formatting"-related concerns.
