### ISSUE TITLE
Ability to force 0 exit code

### ISSUE THREAD

**Issue by adamcharnock** [ambv/black#401]
I primarily use black via the pre-commit hook. However, there is a bit of a gotcha in that the commit will be rejected if black has to actually make any changes.

My workflow normally looks something like this:

1. Make some code changes
2. Write commit message, commit
3. Black runs via pre-commit hook, updates formatting, and exits with non-zero status code. Commit is rejected
4. *If I notice the commit is rejected* (and I often don't), then repeat the commit again
5. This time it passes because black doesn't need to do anything
6. Finish

This seems convoluted to me. I would really like to be able to either:

1. Tell black to exit `0` even if it has to make changes (ideal)
2. Tell `pre-commit` to ignore errors (non-ideal, because if black actually explodes I *do* want to know about it)

Philosophically-speaking (and feel free to ignore this point), it could be argued that if black successfully modifies the formatting of the various files, that this is in fact a success rather than an error. But that may simply depend on what one thinks the purpose of the tool is in the first place.

Of course, this may already exist and I simply missed it. I couldn't see it in `black --help` though...

Operating system: macOS
Python version: 3.6.5
*Black* version: stable

**Comment by zsol** [comment]
Black _does_ exit with `0` if it makes changes (and otherwise everything is fine). The behavior you're observing is pre-commit detecting changed files and refusing to commit the result. There are more details here: https://github.com/pre-commit/pre-commit/issues/532

**Comment by plammens** [comment]
Closely related to #1857
