### ISSUE TITLE
Slicing seems inconsistent between variables and attributes

### ISSUE THREAD

**Issue by alok** [ambv/black#403]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system:
Python version: 3.7
*Black* version: 18.6b4
Does also happen on master: yes

There seems to be a difference in formatting between attributes and regular variables. For example, `a[foo:]` is left unchanged, but `a[foo.bar:]` becomes `a[foo.bar :]`, which seems inconsistent.

**Comment by mkoura** [comment]
Also e.g. ``a[foo + 1:]`` becomes ``a[foo + 1 :]`` and flake8 doesn't like it: ``E203: whitespace before ':'``.

**Comment by zsol** [comment]
PEP-8 says (roughly) there should be whitespace around `:` if there are any complex expressions on either side of it, where complex expressions are basically anything involving any operator. For this purpose I think `+` and `.` qualifies as an operator, so this is the intended behavior. `E203` is not PEP-8 compliant, so I'd recommend disabling it.

This is explained in a little bit more detail [here](https://github.com/ambv/black#slices)

**Comment by zsol** [comment]
Wouldn't you say `@property` is common enough?

**Comment by alok** [comment]
Conceptually, though, they're used like variables. Most uses of `@property` I've seen are to get variable-like data out, such as `arr.T` in NumPy. If they're generally like variables conceptually, I say they should be treated as such stylistically as well.
