### ISSUE TITLE
os.path issues with Pathlib based paths in black

### ISSUE THREAD

**Issue by moskalenko** [ambv/black#407]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Linux
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master: yes

To answer the last question, follow these steps:
* create a new virtualenv (make sure it's the same Python version);
* clone this repository;
* run `pip install -e .`;
* make sure it's sane by running `python setup.py test`; and
* run `black` like you did last time.

$ pip install -e.
Obtaining file:///home/test/black
  Installing build dependencies ... done
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/test/black/setup.py", line 30, in <module>
        version=get_version(),
      File "/home/test/black/setup.py", line 22, in get_version
        with open(black_py, "r", encoding="utf8") as f:
    TypeError: expected str, bytes or os.PathLike object, not PosixPath
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /home/test/black/

I'm not sure Pathlib and os.path can be mixed.

**Comment by JelleZijlstra** [comment]
I can't reproduce this and I'm not sure how to explain it; PosixPath is in fact an instance os `os.PathLike` unless your Python installation is broken in some way.

Maybe you have a `pathlib` package installed in your site-packages that masks the standard library `pathlib` package and doesn't have the `PathLike` protocol?

**Comment by zsol** [comment]
I can't repro this either. @moskalenko are you sure you're running that `pip install -e` command in a completely fresh virtualenv?

**Comment by moskalenko** [comment]
I apologize. It looks like an old 'pathlib' backport was accidentally installed and took precedence over the built-in pathlib.

**Comment by moskalenko** [comment]
It looks like 'thinc' - https://pypi.org/project/thinc/ was the culprit that brought in a pathlib backport.
