### ISSUE TITLE
Tests fail with latest mypy

### ISSUE THREAD

**Issue by zsol** [ambv/black#408]
As pointed out [here](https://github.com/ambv/black/issues/362#issuecomment-405486224), `test_black.py` has some type errors that only show up on the latest version of mypy.

**Comment by cxong** [comment]
There's a quick fix in #409 which is basically to specify the version in the `pip install` commands for the CI config files. A better one would be to get CI to use `pipenv`. But until this issue is resolved, all builds will break.
