### ISSUE TITLE
Black should not write to the file directly

### ISSUE THREAD

**Issue by ksamuel** [ambv/black#41]
Writing to a file directly has all sorts of drawback:

- A file may not be a real file (it may be something faking to be a file to make it readable)
- You may not have the permission to write the file right now.
- Something else might be writing on the file.
- IDE integration might want to use the output of the tool to do something before applying the changes.
- You have no easy way to make a diff of the changes.

Black should output the changes on stdout by default.

If you want the changes to be applied, you do: black file.py > file.py

If you want the changed to be able to be applied implicitly, you can add an option such as --in-place.  This is what sed or gofmt do.

Alternatively, you can specify more write modes, life cargo does: https://github.com/rust-lang-nursery/rustfmt

**Comment by SethMichaelLarson** [comment]
I actually like the default behavior. I'd think this could maybe be an option rather than the default.

**Comment by treuherz** [comment]
See #25

**Comment by ksamuel** [comment]
Alright. I guess I can close this.
