### ISSUE TITLE
Black breaks typing comments

### ISSUE THREAD

**Issue by willmcgugan** [ambv/black#424]
Operating system: OSX
Python version: 3.6
*Black* version: black, version 18.6b4
Does also happen on master: Yes

Black breaks type-hints in comments. My project is Python2.7 and Python3 compatible, with typing information in comments. When black reformats a function with multiple arguments, it combines type hint comments, which MyPy can no longer understand.

Here's an example:

```
--- ftpfs.py	2018-07-28 11:15:16.171417 +0000
+++ ftpfs.py	2018-07-28 11:24:31.528996 +0000
@@ -697,13 +697,11 @@
                     if not self.isempty(path):
                         raise errors.DirectoryNotEmpty(path)
                 raise  # pragma: no cover
 
     def _scandir(
-        self,
-        path,  # type: Text
-        namespaces=None   # type: Optional[Container[Text]]
+        self, path, namespaces=None  # type: Text  # type: Optional[Container[Text]]
     ):
         # type: (...) -> Iterator[Info]
         _path = self.validatepath(path)
         with self._lock:
             if self.supports_mlst:
```

**Comment by zsol** [comment]
Yep, we know. #282
Thanks for reporting!
