### ISSUE TITLE
Documented mechanism for calling black from Python code

### ISSUE THREAD

**Issue by simonw** [ambv/black#425]
I tried to write a unit test that uses "black --check" to confirm that the other code in the repository is black-approved.

I couldn't see an easy way to do this by importing `black` directly, so instead I used the `click.CliRunner` class to programatically execute it using CLI arguments. Here's [my implementation](https://github.com/simonw/sqlite-utils/blob/501618d0d519f808e54210f3c54420e5559a9343/tests/test_black.py) of that:

```
import black
from click.testing import CliRunner
from pathlib import Path

code_root = Path(__file__).parent.parent


def test_black():
    runner = CliRunner()
    result = runner.invoke(
        black.main,
        [str(code_root / "tests"), str(code_root / "sqlite_utils"), "--check"],
    )
    assert result.exit_code == 0, result.output
```

This works! Or rather, it works under Python 3.6. Python 3.7 in Travis is giving me this [surprising result](https://travis-ci.com/simonw/sqlite-utils/jobs/136947772):

```
__________________________________ test_black __________________________________
    def test_black():
        runner = CliRunner()
        result = runner.invoke(
            black.main,
            [str(code_root / "tests"), str(code_root / "sqlite_utils"), "--check"],
        )
>       assert result.exit_code == 0, result.output
E       AssertionError: 
E       assert -1 == 0
E        +  where -1 = <Result KeyError(<Task finished coro=<BaseEventLoop.run_in_executor() done, defined at /opt/python/3.7-dev/lib/python3.7/asyncio/base_events.py:653> result=False>)>.exit_code
```

I'm still trying to figure out what went wrong there.

At any rate though: it would be really useful if there was an easy, documented mechanism for programatically invoking black.

**Comment by zsol** [comment]
Looks like you want [schedule_formatting](http://black.readthedocs.io/en/stable/reference/reference_functions.html#black.schedule_formatting) with `WriteBack.NO`. That reference manual is all we have for now, while black is still in beta.

**Comment by SWu** [comment]
I'm getting the exact same KeyError exception when using black with python3.7, from the commandline. When I use python3.6 everything works fine, but with python3.7 any time I pass more than one file to black I get:

```
  File ".../bin/black", line 11, in <module>
    load_entry_point('black==18.6b4', 'console_scripts', 'black')()
  File ".../lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File ".../lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File ".../lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".../lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File ".../lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File ".../lib/python3.7/site-packages/black.py", line 352, in main
    executor=executor,
  File ".../lib/python3.7/asyncio/base_events.py", line 440, in run_until_complete
    return future.result()
  File ".../lib/python3.7/site-packages/black.py", line 464, in schedule_formatting
    src = tasks.pop(task)
KeyError: <Task finished coro=<BaseEventLoop.run_in_executor() done, defined at .../lib/python3.7/asyncio/base_events.py:597> result=False>

```

**Comment by ambv** [comment]
Whoa, this doesn't look good. I'll look into this tomorrow.

**Comment by SWu** [comment]
I figured out that it was because the coroutine object API changed somewhere between the alpha and final python 3.7.0 releases. My system was still using an old alpha release of 3.7 when I hit that issue, but after updating my python interpreter it went away.

**Comment by zsol** [comment]
Explains why I couldn't reproduce this

**Comment by ambv** [comment]
@SWu, oh yeah, right. This is why our Travis config was a super early adopter of Python 3.7 because the early alpha build they shipped in Trusty was having this exact issue. I forgot about this. Alright, so safe to close!
