### ISSUE TITLE
vim plugin needs user to run PluginInstall for every vim session

### ISSUE THREAD

**Issue by sureshvv** [ambv/black#427]
Operating system: Linux/Ubuntu 18,04
Python version: 3.6
*Black* version: 18.6b4

**Comment by zsol** [comment]
Would you mind giving more details please?

**Comment by sureshvv** [comment]
Here is my reduced .vimrc

    set rtp+=~/.vim/bundle/Vundle.vim
    call vundle#begin()
    Plugin 'gmarik/Vundle.vim'
    Plugin 'ambv/black', {'rtp': 'vim'}
    call vundle#end() 

When I start my vim session and type 

    `:Black`

It says:

    `E492: Not an editor command: Black`

After I run:

    `:PluginInstall` 

I am able to run the Black command.

**Comment by sureshvv** [comment]
Problem was with my .vimrc

Installing using:

    Plugin 'ambv/black'

solved it.
