### ISSUE TITLE
Black way of splitting tuples without parentesis in conditional expresions doesn't look good

### ISSUE THREAD

**Issue by Alexgmin** [ambv/black#428]
Operating system:
Python version: 2.7.12
*Black* version: 18.6b2
Does also happen on master: Not tested, but watching the commits it should

Original code:
```python
def a(foo, bar):
    return (foo.abcdef, foo.abcdef) if foo.abcdef == bar.abcdef else (foo.abcdef, foo.abcdef)

def b(foo, bar):
    return (foo.abcdef, foo.abcdef) if foo.abcdef == bar.abcdef else foo.abcdef, foo.abcdef

def c(foo, bar):
    return foo.abcdef, foo.abcdef if foo.abcdef == bar.abcdef else (foo.abcdef, foo.abcdef)

def d(foo, bar):
    return foo.abcdef, foo.abcdef if foo.abcdef == bar.abcdef else foo.abcdef, foo.abcdef
```

Formatted code:
```python
def a(foo, bar):
    return (
        (foo.abcdef, foo.abcdef)
        if foo.abcdef == bar.abcdef
        else (foo.abcdef, foo.abcdef)
    )


def b(foo, bar):
    return (
        (foo.abcdef, foo.abcdef) if foo.abcdef == bar.abcdef else foo.abcdef,
        foo.abcdef,
    )


def c(foo, bar):
    return (
        foo.abcdef,
        foo.abcdef if foo.abcdef == bar.abcdef else (foo.abcdef, foo.abcdef),
    )


def d(foo, bar):
    return (
        foo.abcdef,
        foo.abcdef if foo.abcdef == bar.abcdef else foo.abcdef,
        foo.abcdef,
    )

```

Without the optional parenthesis, the multiline splitting black does in the last 3 methods is quite bad.

And obvious workaround is the first method,

Maybe related to https://github.com/ambv/black/issues/330

**Comment by zsol** [comment]
These four functions return different things, and I think black's output makes it much clearer than the original code.

`a` always returns a pair
`b` returns a pair where the first element is either a pair or a single value
`c` returns a pair where the second element is either a pair or a single value
`d` returns a triplet

**Comment by Alexgmin** [comment]
Oh, you're right,  I didn't think about the evaluation order. 
My bad, sorry.
