### ISSUE TITLE
Pdb breakpoint line unnecessarily get formatted

### ISSUE THREAD

**Issue by pavdmyt** [ambv/black#435]
The breakpoint set using `pdb`: `import pdb; pdb.set_trace()` get formatted into 3 lines:

```python
import pdb

pdb.set_trace()
```

I'm using Atom editor with plugin to apply **black** when saving the file. 3 lines instead of single breakpoint line is not very convenient. Maybe it is possible to add an exclusion for such kind of lines?

**Environment**:
Operating system: macOS High Sierra; Version 10.13.6 (17G65)
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master: yes

**Comment by zsol** [comment]
It's unlikely we're going to make an exception for `import pdb; pdb.set_trace()` because that would introduce a considerable amount of complexity and it's really easy to just wrap this in `# fmt: off` `# fmt: on` if you really care about these two being on the same line IMO.

**Comment by thejohnbackes** [comment]
@tino -- What you want is the following:

```
# fmt: off
import pdb; pdb.set_trace()
# fmt: on
```

I've turned this into a snippet in VSCode so that all I have to do is type "pdb" as a prefix. You could do the same in your IDE for ease of use.

**Comment by avalanchy** [comment]
black will not touch this workaround
```
__import__("pdb").set_trace()
```

**Comment by ichard26** [comment]
Since GH-1800 on the master branch, `# fmt: skip` at the end of your `import pdb; pdb.set_trace()` line should work.
