### ISSUE TITLE
Not respecting line limit

### ISSUE THREAD

**Issue by retke** [ambv/black#436]
### System info

Operating system: Darwin 10.13.5 (macOS HighSierra)
Python version: 3.6.5
*Black* version: black-18.6b4
Does also happen on master: yes

### Problem

So, I tried to run black as usual from Visual Studio Code (the problem also happen with normal command line), and I set the line length limit to 100, so the command is `black -l 100 myfile.py`.

That command always worked, but this time, it's not respecting the line length limit. flake8 is giving me these errors a bit everywhere : `[flake8] E501:line too long (153 > 100 characters)`

![screen shot 2018-08-06 at 13 27 22](https://user-images.githubusercontent.com/23153234/43714219-9e6026b2-997c-11e8-80dc-f106315b082f.png)
![screen shot 2018-08-06 at 13 27 32](https://user-images.githubusercontent.com/23153234/43714223-a06fc840-997c-11e8-85af-8ec0732d3f53.png)

**Comment by JelleZijlstra** [comment]
What do the lines that are still too long look like?

**Comment by retke** [comment]
The words that are underlined in red are "line too long" errors by flake8

![screen shot 2018-08-06 at 18 43 52](https://user-images.githubusercontent.com/23153234/43729503-c31924e6-99a8-11e8-8283-0aecd78bd665.png)
![screen shot 2018-08-06 at 18 44 12](https://user-images.githubusercontent.com/23153234/43729504-c340346e-99a8-11e8-9bea-8fe5f8ccc500.png)

The whole file : https://github.com/retke/Laggrons-Dumb-Cogs/blob/v3/roleinvite/roleinvite.py

**Comment by robertquitt** [comment]
I don't think black will break up those strings, as that would change the AST. You have to break up the strings yourself if you want the lines to be under 100 characters wide. If you don't care about the line length problem, then you should probably just have flake8 ignore E501 so that it won't complain about it.

**Comment by retke** [comment]
Okay thanks
