### ISSUE TITLE
Black does join import lines, but does not remove brackets

### ISSUE THREAD

**Issue by Aulos** [ambv/black#44]
Code to format:

```python
from a import (
    aa,
    ab,
)
```

Black output:
```python
from a import (aa, ab)
```

Expected output:
```python
from a import aa, ab
```

Operating system: Ubuntu 17.10
Python version: 3.6.3
Black version: 18.3a2
Does also happen on master: yes

**Comment by ambv** [comment]
This is a duplicate of #4 and a planned feature :-)

**Comment by Aulos** [comment]
It would be nice if it was consistent.

Now code like:
```python
from a import (
    aa,
    ab,
)
from b import ba, bb
```
is transformed to 
```python
from a import (aa, ab)
from b import ba, bb
```

which looks kind of strange.

**Comment by ambv** [comment]
Agreed, this will be fixed soon.

**Comment by ambv** [comment]
In the mean time, as a workaround, if you manually remove the unnecessary punctuation, Black won't add it back ;-)

**Comment by ambv** [comment]
The reason I'm leaving a trailing comma for single-element parenthesized expressions is that it looks like a tuple and removing it would change what your code means.

In the import case it's a false positive of course :-)

**Comment by carljm** [comment]
@ambv Is there anything specifically actionable here that isn't covered by #4? Closing as a dupe; it's still linked from #4 if you want the examples.
