### ISSUE TITLE
Enforce PEP8 class name convention (CapitalizedWords)?

### ISSUE THREAD

**Issue by GandalfSaxe** [ambv/black#442]
How about enforcing class names [according to PEP8](https://www.python.org/dev/peps/pep-0008/#class-names)? I.e. as `MyClass`.

I don't know if naming conventions are enforced for functions, methods and modules (all case with underscores), but that could also be a good idea perhaps?

**Comment by zsol** [comment]
This is well outside of black's scope IMO (it cares about formatting, not naming things) _and_ is a really risky endeavor. Changing class/function/variable names is very likely going to introduce breakages in any significant codebase.

**Comment by GandalfSaxe** [comment]
Fair point 👍

**Comment by home-gehred** [comment]
zsol I agree with you a hundred percent, but would it be possible to give a warning / error to developers so they can change the names?

**Comment by JelleZijlstra** [comment]
That's outside the scope of black; you should use a linter like flake8 or pylint instead. Black just formats code; it doesn't give warnings.
