### ISSUE TITLE
Spaces Before/After Slice :'s

### ISSUE THREAD

**Issue by scolby33** [ambv/black#446]
Operating system: macOS 10.13.6
Python version: 3.7
*Black* version: 18.6b4
Does also happen on master: yes

Black gives the following output:

```python
class ItHasConstants:
    LONG_NAME_FOR_A_CONSTANT = 0


def myfunc():
    mylist = []
    slicea, sliceb = (
        mylist[: ItHasConstants.LONG_NAME_FOR_A_CONSTANT],
        mylist[ItHasConstants.LONG_NAME_FOR_A_CONSTANT :],
    )
```

I think that in this case, it should read:
```python
...
    slicea, sliceb = (
        mylist[:ItHasConstants.LONG_NAME_FOR_A_CONSTANT],
        mylist[ItHasConstants.LONG_NAME_FOR_A_CONSTANT:],
    )
```

With no spaces before or after the `:`. Am I wrong or is this an oversight in Black's handling of slices when attribute access is happening?

**Comment by JelleZijlstra** [comment]
This is intentional behavior. See https://github.com/ambv/black#slices.

**Comment by scolby33** [comment]
In the PEP 8 section referenced from that portion of the docs, I don't see anything that suggests the `[: one_space_form]`  over the `[:no_space_form]`. All that is required is the "same amount of spacing" where, in my mind, zero and one space both qualify.

I understand that you wouldn't want to make a "breaking" change like this though when I'm merely quibbling over an ambiguity. I apologize for not looking to the docs first; this is one of the few times Black's decision has conflicted with my styling instinct and I immediately assumed that it was wrong.

**Comment by cxong** [comment]
@scolby33 the doc mentions equal spacing "except if a parameter is omitted". This is consistent with PEP8, which contains the following acceptable examples:

```
ham[1:9], ham[1:9:3], ham[:9:3], ham[1::3], ham[1:9:]
ham[lower:upper], ham[lower:upper:], ham[lower::step]
ham[lower+offset : upper+offset]
ham[: upper_fn(x) : step_fn(x)], ham[:: step_fn(x)]
ham[lower + offset : upper + offset]
```

Your desired output is represented in the first and second lines; black follows the fourth line. All five are acceptable according to PEP8.

**Comment by zsol** [comment]
`[1:]` is also appropriately spaced. Black puts extra spaces around "complex" expressions and enforces equal spacing around `:` except when a parameter is missing. So all of these are considered blackened:

```
ham[1:9]
ham[1:]
ham[1 + 2 : 9]
ham[1 + 2 :]
ham[obj.attribute : obj.other_attribute]
```

**Comment by scolby33** [comment]
Ohh, I understand now! Thanks for the explanation.
