### ISSUE TITLE
`--check` mode does not write cache

### ISSUE THREAD

**Issue by JelleZijlstra** [ambv/black#448]
I noticed that the cache is not written when `--check` mode is on. This makes sense if the check fails, but if the file being checked is well-formatted, it would seem to be safe to write the cache. I propose that in `--check` mode we write to the cache only if the checked file is well-formatted. 

My proposed behavior is useful when running Black in CI with `--check`, where we will frequently check the same file, and almost all will usually be well-formatted.

**Comment by zsol** [comment]
Agreed :) happy to merge a PR about this

**Comment by ambv** [comment]
Good catch, this is going to make things run faster.
