### ISSUE TITLE
Link to VS Code extension

### ISSUE THREAD

**Issue by joslarson** [ambv/black#45]
@ambv I've been waiting a long time for something like Black to come to Python land, and so to lend my support I just put together a VS Code extension for Black, as it's my editor of choice:

https://marketplace.visualstudio.com/items?itemName=joslarson.black-vscode

It depends on the upcoming piping feature to work, so it won't be "stable" until that lands, but I'm wondering, once it does, what you think about linking to it in the README under the "Editor integration" heading to help other VS Code users find it.

Thanks for your great work on this 👍

**Comment by ambv** [comment]
This is amazing. I will accept your pull request to do just that.

**Comment by ambv** [comment]
Your docs say "ext install prettier-vscode", I guess that's not what we want here ;-)

**Comment by joslarson** [comment]
LOL, good catch! Fixed. In my head this is the Python take on prettier, so makes sense :) I'll hold off on the pull request until the piping support lands in pypi.

**Comment by ambv** [comment]
Note: 18.3a3 is live! Thanks again for the plugin!
