### ISSUE TITLE
Exclude formatter from running on specific lines with inline comment

### ISSUE THREAD

**Issue by jakerye** [ambv/black#451]
Some of my code is just over the border of the line limit. Here is an example:
```
self.parser.add_argument("--co2", action="store_true", help="read co2")
self.parser.add_argument("--mode", type=int, help="set device mode 1-4")
self.parser.add_argument(
    "--status", action="store_true", help="read status register"
)
self.parser.add_argument(
    "--error", action="store_true", help="read error register"
)
self.parser.add_argument("--reset", action="store_true", help="resets sensor")
```

I'd really like it to look like this (or equivalent):
```
self.parser.add_argument("--co2", action="store_true", help="read co2")
self.parser.add_argument("--mode", type=int, help="set device mode 1-4")
self.parser.add_argument("--status", action="store_true", help="read status register") # nofmt
self.parser.add_argument("--error", action="store_true", help="read error register")  # nofmt
self.parser.add_argument("--reset", action="store_true", help="resets sensor")  # nofmt
```

Is this something that aligns with the black ideology?

**Comment by JelleZijlstra** [comment]
You can use `# fmt: off` and `# fmt: on`.

**Comment by jakerye** [comment]
Excellent, thank you!

**Comment by ab-w** [comment]
@jakerye That doesn't work inline as the title of the issue required. I don't want to have to add two new lines if my goal is for `black` to ignore a single line. `# fmt: off` should really work inline too as in the example below:

    self.parser.add_argument("--co2", action="store_true", help="read co2")  # fmt: off

**Comment by eric-wieser** [comment]
@ab-w: `fmt: no` might be clearer than `fmt: off`, to distinguish toggling formatting and disabling it for just one line

**Comment by ab-w** [comment]
@eric-wieser It would be, but I don't see it as being necessary at all. As a case in point, consider pylint. It lets me disable analysis either for a line or for a block, both with the same `pylint: disable=foo,bar` comment. I don't see a need to add complexity for the user as it's already quite clear to the user. If we wanted to be redundantly clearer, we would for instance use a language that used braces instead of indents, or with mandated semicolons at the end of lines, but we don't.

**Comment by dandavison** [comment]
Ref https://github.com/psf/black/issues/790#issuecomment-481154453 which discusses the desirability of an inline comment toggle and has a clever workaround.

**Comment by juliuscrn** [comment]
Doesn't work when  used on jupyter magic commands:

`%matplotlib inline  # fmt: off`

**Comment by geier1993** [comment]
@juliuscrn 
Magic commands are also discussed here:

#774 https://github.com/psf/black/issues/774

**Comment by AustinScola** [comment]
For anyone who stumbles upon this GitHub Issue: it looks like Black now supports skipping a single line by adding `# fmt: skip` at the end of a line:
```python3
foo = 1  # fmt: skip
```

**Comment by HydrogenSulfate** [comment]
> For anyone who stumbles upon this GitHub Issue: it looks like Black now supports skipping a single line by adding `# fmt: skip` at the end of a line:
> 
> ```python
> foo = 1  # fmt: skip
> ```

Only this indeed works rather than `# fmt: off` or `# fmt: no` with black 23.12.0, thanks a lot.
