### ISSUE TITLE
Disable blank lines around top level definition

### ISSUE THREAD

**Issue by tuyenpm9** [ambv/black#457]
Operating system: windows10
Python version: 3.6.5
*Black* version: 18.6b4

I need to use only one blank line or whatever how many blank lines before top level of class/def I want,
How `black` would help in this case?

**Comment by ambv** [comment]
> How black would help in this case?

It wouldn't. It's opinionated and it standardizes the amount of blank lines to adhere to PEP 8.

**Comment by tuyenpm9** [comment]
God, my `vim` fold look ugly with two blank lines.
