### ISSUE TITLE
Extra space in kwarg unpacking

### ISSUE THREAD

**Issue by maxim-lian** [ambv/black#46]
I thought I'd seen this (and maybe put an issue in already on this?) but I can't find it anywhere. So here goes:

```diff
-        return security_screen(**self.screen_kwargs)
+        return security_screen(** self.screen_kwargs)
```

Operating system: MacOS
Python version: 3.6.4
Black version: black, version 18.3a3
Does also happen on master: Yes

**Comment by ambv** [comment]
Thanks for your report, this is now fixed! ✨ 🍰 ✨
