### ISSUE TITLE
black adds unnecessary lines around triple-quoted blocks

### ISSUE THREAD

**Issue by webartifex** [ambv/black#462]
Using the rpy2 library to embed R code in a Python project, a common idiom is this:

```python
import rpy2.robjects as robjects

robjects.r('''
loadRData <- function(fileName){
    #' Load an .rda file and return it as a r.DataFrame.
    load(fileName)
    get(ls()[ls() != "fileName"])
}
''')
```

Appying `black -S` to it, the code becomes:

```python
robjects.r(
    '''
loadRData <- function(fileName){
    #' Load an .rda file and return it as a r.DataFrame.
    load(fileName)
    get(ls()[ls() != "fileName"])
}
'''
)
```

This might be an issue with other language embeddings as well.

My suggestion is that black does not change this idiom, i.e., the opening and closing parenthesis should be coalesced with the triple (single) quotes.

Operating system:
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master: yes

EDIT: earlier versions did not show the whitespace correctly.

**Comment by asottile** [comment]
To make a code block use triple backticks

```markdown
    ```python
    print('like this!')
    ```
```

**Comment by gwax** [comment]
I have run into this with the similar `textwrap.dedent` idiom:

```python
textwrap.dedent("""\
    Hello, I am
    a multiline string used with
    a common idiom
""")
```

black will convert this to:

```python
textwrap.dedent(
    """\
    Hello, I am
    a multiline string used with
    a common idiom
"""
)
```

This is particularly bad in the case of another containing function:

```python
sqlalchemy.text(textwrap.dedent("""\
    SELECT
        *
    FROM
        sometable
"""))
```

becomes:

```python
sqlalchemy.text(
    textwrap.dedent(
        """\
    SELECT
        *
    FROM
        sometable
"""
    )
)
```

**Comment by ambv** [comment]
I'll close this as a duplicate and we'll handle this use case as part of #256, too.
