### ISSUE TITLE
Typo in README (flake8 configuration)

### ISSUE THREAD

**Issue by cailloumajor** [ambv/black#465]
There is a typo in `README.md`, relative to flake8 configuration ([Line length](https://github.com/ambv/black/blob/master/README.md#line-length) section).

As stated in [flake8 documentation](http://flake8.pycqa.org/en/latest/user/configuration.html#project-configuration), underscore instead of hyphens must be used in option name when used in an INI-file.

**Comment by JelleZijlstra** [comment]
Can you be more specific?

**Comment by cailloumajor** [comment]
My apologies, I read too fast.
