### ISSUE TITLE
Formatting fails on lambda expression with default argument

### ISSUE THREAD

**Issue by madig** [ambv/black#468]
Operating system: Win 10 1803 x64
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master: Yes

The following snippet appears to be valid Python code but trips black:
```Python
pem_spam = lambda l, spam = {
    "-----BEGIN PKCS7-----": True, "-----END PKCS7-----": True, "": True
}: not spam.get(l.strip())
```
Found at https://github.com/fonttools/fonttools/blob/master/Lib/fontTools/ttLib/tables/D_S_I_G_.py#L101.

**Comment by zsol** [comment]
Looks like this is a bug in black's bracket matching. We'll fix it, thanks for reporting!

**Comment by JelleZijlstra** [comment]
More specifically it's because `BracketTracker.maybe_decrement_after_lambda_arguments` thinks the `:` in the dict literal is the colon that ends the lambda's argument list. The same bug appears with for ... in. This piece of great Python code also crashes Black:
```
for ((x in {}) or {})['a'] in x:
	pass
```
I will fix it.
