### ISSUE TITLE
Docstrings are not formatted properly

### ISSUE THREAD

**Issue by VighneshKSP** [ambv/black#473]
Operating system: Windows 10
Python version: 3.7.0
*Black* version: 18.6b4
Does also happen on master: Yes

Input:
```
def func():
  """
 abc
 """
```
output:
```
def func():
    """
 abc
 """
```

Supplied input had 2 spaces for the docstring's starting quote and 1 space for the content `abc` and ending quotes. After running black on the file, it had four spaces for the starting quote while the remaining where unaffected. As per the discussion #144, expectation is that this should be formatted as per PEP 257 guidelines.

**Comment by zsol** [comment]
#144 is not implemented yet. Until then, this behavior is expected (as black will use 4 spaces for indentation and will not change the contents of docstrings).
