### ISSUE TITLE
typing.Union should not be joined if end of line has comments

### ISSUE THREAD

**Issue by gaborbernat** [ambv/black#476]
black 18.6b4

```python
from typing import Union


A = Union[
    int,  # my comment
    float,  # my other comment
]
```

gets translated into:

```python
from typing import Union


A = Union[int, float]  # my comment  # my other comment
```

Interestingly black already handles lists well:

```python
# this does not get reformatted
A = [
    int,  # my comment
    float,  # my other
]
```

**Comment by zsol** [comment]
FWIW, the list example also does get reformatted:
```
-A = [
-    int,  # my comment
-    float,  # my other
-]
+A = [int, float]  # my comment  # my other
```

Because all that code fits on one line including both comments, this is unlikely to get solved, except maybe for the type annotations case but the solution is unclear there as well: #282
