### ISSUE TITLE
Cannot pip install black: No matching distribution found for black

### ISSUE THREAD

**Issue by MrCsabaToth** [ambv/black#478]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

I'm trying to install black from pip and I'm getting:

```
(virtualenvname) username@machine:~/webapp$ pip install black
Collecting black
  Could not find a version that satisfies the requirement black (from versions: )
No matching distribution found for black

```
Operating system: Linux, Devuan ascii
Python version: 2.7.13
*Black* version: newest???

**Comment by JelleZijlstra** [comment]
Black only runs on Python 3.6 and newer, although it can format code written for older Python versions. Try `python3.6 -m pip install black` (you may have to install python3.6 or 3.7 first).

**Comment by MrCsabaToth** [comment]
Sorry, I have also Python 3.5.3 (system provided) and also Python 3.6.6 (compiled on my own). Now I prioritized Python 3.6.6 over Python 3.5 with `update-alternatives`. I'll try your command

**Comment by MrCsabaToth** [comment]
`python3.6 -m pip install black` worked.

**Comment by JelleZijlstra** [comment]
Good to hear!

**Comment by MrCsabaToth** [comment]
Haha, run into this on Windows as well!
