### ISSUE TITLE
"black --exclude .vscode --diff ." is writing files back

### ISSUE THREAD

**Issue by holmboe** [ambv/black#482]
Operating system: Ubuntu 18.04
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master: Don't know.

I read the `black --help` output and it seemed that `--diff` should behave like a typical dry-run but apparently that's not the case. Am I missing something or is this expected behaviour?

**Comment by sjohannes** [comment]
I tested this and it seems to only be a UI issue (`black --diff` says "reformatted" and celebrates but it doesn't actually reformat). Could you check whether that's the case?

If I'm wrong and it does reformat, in the meantime you can use `black --check --diff`. The only difference is that it returns with nonzero exit code when the check fails.

(I would actually argue that `black --diff` without `--check` *should* reformat, but that would break backwards compatilibity.)

**Comment by zsol** [comment]
I can't reproduce this and I don't think it can happen. @holmboe feel free to reopen this if you have steps to repro
