### ISSUE TITLE
Compatibility with AutoPEP8 and yapf command line

### ISSUE THREAD

**Issue by kunalgrover05** [ambv/black#489]
Hi there. I am recently experimenting with different linters and ```black``` seems to win it easily. I was very happy with a lot of things that work which are broken by ```AutoPEP8``` and ```yapf```.

We use [Arcanist](https://secure.phabricator.com/book/phabricator/article/arcanist/) as our Code review tool(which co-exists with Phabricator). I am trying to set up Python linting using ```black``` for our project. Arcanist supports linting by writing a custom wrapper around a command line tool and using the error code / stdout and stderr to find out what to do.

The good part about both of those tools is that they have a consistent command line where default is to print the new file to stdout. This makes it incredibly easy to make it just replace my file with the new file.

I wanted to understand why ```black``` has a different set of default behaviors, any reason for that? At the same time, in order to make it work similar to the other 2 tools, can we add a command line parameter which simply prints the new file instead of printing the diff or replacing it in place? 
It should be easier to do it in black rather than wiring up a PHP git patch parser in my Arc plugin. (although it definitely should not be hard)

**Comment by kunalgrover05** [comment]
My bad, I didn't think this through. Simply patch the original file to get the correct result:
```
black core/models.py --diff | patch core/models.py -o -
```

The only question would be if we should try to maintain parity with the behavior of autopep8, apart from that feel free to close the issue.

**Comment by jlisee** [comment]
Based on: #431  I whipped up a simple shell script which I call from a simple class extending `ArcanistExternalLinter.php`:

```bash
#! /bin/bash
cat $1 | black --quiet -
exit $?
```

Every other linting tool I have used across many languages has an option to not edit things in place and instead just write to stdout.  The above is workable, but integration would be easier if there was a compatibility output.

**Comment by kunalgrover05** [comment]
@jlisee That looks good. I implemented based on the patch utility as represented above. 

Adding it here for others for future reference: https://github.com/kunalgrover05/arcanist-python-lint-autoformat

**Comment by zsol** [comment]
Thanks for exploring this. At my company we use the output of `black --diff` parse the diff output in an arcanist wrapper, which is not great because some people might get ideas about applying only certain hunks of the diff, and that's not generally safe.

As for conforming with autopep8's command line interface, that's not a goal right now.
