### ISSUE TITLE
Space before method brackets for built-in functions

### ISSUE THREAD

**Issue by loechel** [ambv/black#49]
I have the problem that black does a reformat of built-in functions, in my case on exec and eval as those have been statements in Python 2 but are methods in Python 3. 

```patch python
-        return exec("code", {}, {})
+        return exec ("code", {}, {})
````

Operating system: MacOS
Python version: 3.6.4
Black version: black, version 18.3a3
Does also happen on master: Yes

**Comment by ambv** [comment]
Yes, this is indeed a bug stemming from usage of lib2to3. We should probably just don't allow for the old `exec` and `eval` forms.
