### ISSUE TITLE
Black should include extension-less Python files with a shebang by default

### ISSUE THREAD

**Issue by jdufresne** [ambv/black#491]
Standalone Python scripts often don't have an extension, but include a shebang. e.g. `#!/usr/bin/env python3`. Black should detect these files and format them the same as a `.py` file. Other format tools, such as isort, already do this. For details on how isort does this, see:

https://github.com/timothycrosley/isort/blob/fcd80d46e66179f9464c2df745ffed07622d9ee3/isort/main.py#L61-L74

Right now, I'm required to list each extension-less script explicitly, which I find to be error prone as new scripts are added.

**Comment by zsol** [comment]
Can you describe how you're calling black and where you're listing these scripts explicitly?

**Comment by jdufresne** [comment]
I have a `Makefile` that looks something like:

```make
black-check:
	black --check --diff .

black-fix:
	black .
```

This successfully checks or fixes all files in my project that end with `.py`. However, I also have many one-off Python scripts across the project in various directories. These scripts don't have a `.py` extension. Without listing them explicitly, these files are not checked or fixed by the above black command. I have made the following local changes to fix this:

```make
SCRIPTS := \
	path/script1 \
	path/thing1 \
	other/path/script2

black-check:
	black --check --diff . $(SCRIPTS)

black-fix:
	black . $(SCRIPTS)
```

IRL, the scripts aren't so regularly named or organized. All of these scripts have the following shebang `#!/usr/bin/env python3`. I'm suggesting that black should be able to detect Python files by inspecting the shebang just as it detects Python files by inspecting the file suffix. I then wouldn't need to list them explicitly.

**Comment by zsol** [comment]
I'm hesitant to do this because opening each file in a directory recursively to peek at its contents has severe performance implications given a sufficiently big codebase. If your repo is small enough, I think you could use tools like `file` or [identify](https://github.com/chriskuehl/identify) to automatically gather the list of scripts outside of black.

**Comment by nicktimko** [comment]
Would you be accepting of a PR for this if it's off-by-default? e.g. opt in with something like
```
[tool.black]
...
magic_parameter = true
```

**Comment by consideRatio** [comment]
I ended up with a CI failure that was caused by a difference between these:

```sh
# will include python files without .py extension
pre-commit run --all-files
# will not...
black .
```

I understand that there may be a performance hit, but I would argue it could be suitable to at least support this by the use of a flag to the black CLI.

**Comment by patzm** [comment]
Given that those scripts are typically also marked as executables, would this be a compromise? Inspect the file attribute, and only check for a shebang if the file is executable. That shouldn't add any runtime complexity because you already look at the filesystem attributes (to check the extension), see @zsol's https://github.com/psf/black/issues/491#issuecomment-419550957.

**Comment by briceburg** [comment]
I also have executable python files spattered throughout a repo without the .py extension, but marked executable and the first line contains a shebang like `#!/usr/bin/env python3`.

So my CI script searches for executable files [in the bin/ and lib/ directories], matches the first line for a shebang containing 'python', and passes those files to black. e.g.

```sh
#!/usr/bin/env bash
set -eo pipefail

pyfiles=()

while IFS= read -r -d '' file; do
  if head -n1 "$file" | grep -q '^#!.*python'; then pyfiles+=( "$file" ); fi
done < <(find lib -type f -perm -a=x -print0)

black --check "${pyfiles[@]}"
```
