### ISSUE TITLE
flake8 breakage

### ISSUE THREAD

**Issue by sureshvv** [ambv/black#492]
**Black https://github.com/ambv/black/commit/25795c**

[Playground link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABgAE1dAD2IimZxl1N_WlbvK5V-fnZfBCsrtgusrgnfFel2t2k2kWUYhDx0OUqK0YojNOWs2BRifL_hC9fli1DpIt0jUk7p0Vq6iHCbwZaItkU_AAAAAMP7Mjh8lsFvAAFpYQs0DK4ftvN9AQAAAAAEWVo=)

## Options

`--line-length=60`

## Input

```python
def main():
    s[len(s):2] = 'a'
```

## Output

```python
def main():
    s[len(s) : 2] = "a"

```

## Expected

**Comment by JelleZijlstra** [comment]
This is a bug in flake8; see the README at https://github.com/ambv/black#slices.

**Comment by sureshvv** [comment]
Added

ignore=E203

in the flake8 file located in the .config folder under the home directory.
