### ISSUE TITLE
When trailing comma present, force explode formatting

### ISSUE THREAD

**Issue by jasonkuhrt** [ambv/black#499]
The following is an example of the idea being proposed.

By the current standards of `black` (modulo column size) this is considered readable style:

```py
    return Response(
        statusCode=status_code, body=safe_json.dumps(body or dict()), headers=headers
    )
```

I personally disagree. I understand black is adverse toward configuration, and appreciate the justification for that. So my proposal here is that a trailing comma can force the explosion, like so:

Given a trailing comma:
```py
    return Response(
        statusCode=status_code, body=safe_json.dumps(body or dict()), headers=headers,
    )
```
Black would format like so:
```py
    return Response(
        statusCode=status_code,
        body=safe_json.dumps(body or dict()),
        headers=headers,
    )
```

The benefits are:

1. more readable IMHO
2. more friendly to viewing version control system [git, ...] diffs

**Comment by zsol** [comment]
One of the basic principles of black is that input formatting has no effect on output formatting. This is unlikely to change. About "readable style", there's already a discussion happening over at #404 so I'll close this out.

**Comment by jasonkuhrt** [comment]
I'll keep my eye on #404 thanks.
