### ISSUE TITLE
error: cannot format C:\Users\m\t.py: [Errno 13] Permission denied: C:\Users\m\t.py

### ISSUE THREAD

**Issue by chfw** [ambv/black#501]
Hi all

Has anyone used pycharm with "Black"? I am getting above "Permission Denied" error. Have you gotten the same thing? Or is it just me?

Operating system: Windows
Python version: Python 3.6
*Black* version: 18.6b4
Does also happen on master:

Should.

Thanks

**Comment by zsol** [comment]
This is very likely a problem with your environment @chfw. Make sure the process that black runs in has permissions to write that file.

**Comment by chfw** [comment]
figured it out today. The file itself was set as read-only. When the file flag is removed, pycharm can use black to format it and load it. 

I did not remember how I got it working in cmd shell on the same file. But today, with second pair of eyes, the question is cracked.
