### ISSUE TITLE
Preserve alignmenment

### ISSUE THREAD

**Issue by mbarkhau** [ambv/black#502]
Hi,

I have a plugin that aligns code like this:

```python
environ = {
    "DB_HOST"      : "1.2.3.4",
    "DB_PORT"      : "1234",
    "DB_NAME"      : "app_db_v2",
    "DB_USER"      : "new_user",
    "DB_READ_ONLY" : "0",
    "DB_DDL"       : "~/mkdb.sql",
}
```

Would it be an option to preserve this kind of alignment, or perhaps even have black do the alignment?

**Comment by JelleZijlstra** [comment]
Black is generally unlikely to change its existing style or to add more configuration options (see the README for some explanation).

The style you propose doesn't seem very diff-friendly. If somebody came in and added a key `DB_READ_PASSWORD`, we'd have to reformat all other lines in the dictionary to add more spacing, which would make for a very hard to read diff.

**Comment by zsol** [comment]
Having said that, you can wrap this piece of code in `# fmt: off` `# fmt: on` pairs and black will leave it alone.

**Comment by mbarkhau** [comment]
I've implemented a the alignment codes, so that it could be applied as a postprocessing step after `format_str`. https://gist.github.com/mbarkhau/7ad941b982b96ae62dd66bd6d6924a28

Considering that this will probably never be merged, how would you prefer I go about making a fork of the project?

**Comment by mbarkhau** [comment]
Ok, I guess I'll just create a separate project that is basically a wrapper for black. Hopefully I can rely on the stability of this function declaration 

```python
def format_str(
    src_contents: str, line_length: int, *, mode: FileMode = FileMode.AUTO_DETECT
) -> FileContent:
```

**Comment by Borda** [comment]
Hello, I would have a comment about preserving multi-line dictionary. From my perspective the created such dictionary has its purpose... for example you want to prepare some Kw for a function, see
```
my_params = {
    'parameter_one': 'abcd',
    'parameter_two': False,
    'parameter_three': 15458,
}

my_function(required_param, another_param, **my_params)
```
but here the dictionary will be squashed to a single line...

**Comment by thomasf** [comment]
> which would make for a very hard to read diff.

Not really and many diff tools also have the option to toggle ignore white space only changes.

**Comment by thomasf** [comment]
To me it's not so much about preserving formatting as maybe enforcing alignment where it makes sense 
to do so.

I think that `gofmt` is pretty clever in how it aligns comments. Given that gofmt does not care about line length at all it has an easier job doing this and obviously the member/value alignment of the struct would not work for python but the end of line comment alignment algorithm seems like something that would only be positive for black.. I've run black on some large code bases written by different people and end the loss of line comments are among the top5 readability losses I see commonly.

```go
package main

import "fmt"

type Foo struct {
	Foo      string // asd
	FBar     int    // alwodj
	RockFunk uint64 // laksjd
	PopRap   int64  // alksjd
	Disco    string // alksjd

	Ranch int    // alksjd
	House uint64 // alksjd
	Villa int64  // alksjd
}

func main() {
	fmt.Println("  ")     // asd
	fmt.Println("    ")   // asd
	fmt.Println("      ") // asd

	fmt.Println("       ") // asd
	fmt.Println("     ")   // asd
	fmt.Println("  ")      // asd

	fmt.Println("       ") // asd
	fmt.Println("     ")
	fmt.Println("  ") // asd

	fmt.Println("  ") // asd

	fmt.Println(
		" ",     // asd
		"   ",   // asd
		"     ", // asd
		"  ",    // asd
		"  ",    // asd
		"  ",
		"  ", // asd
	)

	_ = Foo{
		Foo:      "asd",  // asdad
		FBar:     21,     // asd
		RockFunk: 123124, // asd
		PopRap:   123,    // bbb
		Disco:    "asd",  // a

		Ranch: 21341123, // asd
		House: 123,      // qasd
		Villa: 12355,    // asd
	}
}
```

**Comment by mbarkhau** [comment]
@thomasf I put together a [hacky wrapper around black](https://pypi.org/project/straitjacket/) which does this kind of alignment. In some rare circumstances it may exceed the line length when it adds padding, but you can add a newline in those situations.
