### ISSUE TITLE
long strings are not broken into small chunks

### ISSUE THREAD

**Issue by 098799** [ambv/black#515]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system:
Python version: 3.6.5
*Black* version: 18.6b4
Does also happen on master: yes

To answer the last question, you have two options:
1. Use the online formatter at https://black.now.sh/?version=master, which will use the latest master branch.
2. Or run black on your machine:
    * create a new virtualenv (make sure it's the same Python version);
    * clone this repository;
    * run `pip install -e .`;
    * make sure it's sane by running `python setup.py test`; and
    * run `black` like you did last time.

Long strings are not broken into small chunks, therefore violating the 88 character in a line rule (or even 120 if the string is long enough). I'd expect a utility as this one to be aware of line limits and create a following type of break
```
("somestringthatisverylongsomestringthatisverylongsomestringthatisverylong"
"yes it's really really long yes it's really really long yes it's really really long")
```

**Comment by zsol** [comment]
You're right, black doesn't do this yet. It's probably going to do it in the future, #182 tracks this
