### ISSUE TITLE
Possibility of allowing python 3.5 with black (through pip)?

### ISSUE THREAD

**Issue by miguelgfierro** [ambv/black#519]
I tried black with python 3.6 and I really like it.

A couple of colleagues and I were wondering whether it would be possible to have a version of black that supported python 3.5.

**Comment by zsol** [comment]
Hey @miguelgfierro. Black accepts python 3.5 code as input and formats it just fine (in fact it supports python 2 as well). You'll only need 3.6+ to _run_ it.

**Comment by miguelgfierro** [comment]
ok thanks, we'll do that

**Comment by raratiru** [comment]
A recommendation for a good distro? 

Debian is still using python 3.5 out of the box and its [next release](https://www.debian.org/releases/) has not yet been announced. 

> 
> Index of releases
> 
>     The next release of Debian is codenamed "buster" — no release date has been set
>     Debian 9 ("stretch") — current stable release
