### ISSUE TITLE
Bogus Error Message

### ISSUE THREAD

**Issue by AXGKl** [ambv/black#522]
Operating system: (Debian) Linux
Python version: 3.7
*Black* version: 18.6b4
Does also happen on master: yes

First of all: Thanks for black!

Here a funny bogus error message:

```python
black root@ip-10-34-2-19:~r/mdv# cat r.py
errout = lambda *msg: print(" ".join(msg), file=sys.stderr) # <-no error here
correct = 'foo'
def foo():
    if 1:  # <- error here
    i = 2
```
```bash
black root@ip-10-34-2-19:~/mdv# black r.py
error: cannot format r.py: Cannot parse: 2:22: errout = lambda *msg: print(" ".join(msg), file=sys.stderr)
All done! 💥 💔 💥
1 file failed to reformat.
black root@ip-10-34-2-19:~/terminal_markdown_viewer/mdv# black --version
black, version 18.6b4
```

I'm not saying it should format it, I'm only saying that it reports the wrong place for the error, should be the `if1:\ni=2` place.

It seems to be a problem with print() in the ast - if I do `lambda: foo()` it works, if I do `lambda: print()` it does not:

```bash

$ echo -e 'lambda: foo()\nif i:\ni=1' | black -
lambda: foo()
if i:
i=1
error: cannot format -: Cannot parse: 3:0: i=1
All done! 💥 💔 💥
1 file failed to reformat.

$ # same with print function:

$ echo -e 'lambda: print()\nif i:\ni=1' | black -
lambda: print()
if i:
i=1
error: cannot format -: Cannot parse: 1:8: lambda: print()
All done! 💥 💔 💥
1 file failed to reformat.
```

-> a bit annoying when you have big file and and try to find the real place where you messed up...

**Comment by zsol** [comment]
Yes, this is an unfortunate effect of how black tries several different python grammars before giving up and is unable to determine which is the "real" error: #423

**Comment by AXGKl** [comment]
sorry for not having seen #423 - commenting there...
