### ISSUE TITLE
Enforce alignment of and/or in if statements

### ISSUE THREAD

**Issue by kaste** [ambv/black#527]
Operating system: Windows 10
Python version: 3.6
*Black* version: 18.6b4

Thanks for the great tool. I had the following today:

IN

```
                if (
                    virtual_view.select_line(lines - 1).strip() == '' and
                    (lines < 2 or virtual_view.select_line(lines - 2).strip() != '')
                ):
                    continue
```

OUT

```
                if virtual_view.select_line(lines - 1).strip() == '' and (
                    lines < 2
                    or virtual_view.select_line(lines - 2).strip() != ''
                ):
                    ...
```

That seems an odd decision. I would rather like to see black doing this

```
                if (
                    virtual_view.select_line(lines - 1).strip() == ''
                    and (
                        lines < 2 
                        or virtual_view.select_line(lines - 2).strip() != ''
                    )
                ):
                    ...
```

so that the logical operators get visually promoted.

**Comment by kaste** [comment]
I also see this 

```diff
-        if (not original_method or not inspect.isclass(self.mocked_obj) and
-                inspect.ismethod(original_method)):
+        if (
+            not original_method
+            or not inspect.isclass(self.mocked_obj)
+            and inspect.ismethod(original_method)
+        ):
```

which is expected, but then

```diff
-        elif (inspect.isclass(self.mocked_obj) and
-                inspect.isclass(original_method)):
+        elif inspect.isclass(self.mocked_obj) and inspect.isclass(
+            original_method
+        ):
```

🤷‍♂️

**Comment by ambv** [comment]
Black only keeps extra parentheses when there is more than one operator involved. For single operators, additional parentheses are just visual noise.

What Black is not seeing is a form of symmetry that you do perceive. The simple rule to only keep optional parentheses on more than one operator (of the same priority) works predictably for all cases. Trying to introduce "symmetry" would be bound to fail here and there and would slow things significantly down.

Thanks for your thoughtful report but I'm afraid we can't do much about this unless there is some breakthrough in how to inform Black of symmetry in expressions without killing performance.
