### ISSUE TITLE
Special comments formatted into normal comments breaks pweave, spyder IDE

### ISSUE THREAD

**Issue by piccolbo** [ambv/black#532]
Operating system: OS X
Python version: 3
*Black* version:18.6b4
Does also happen on master: yes

Literate programming and other types of sw use special comments to interleave text and code. In the case of pweave it's #', for Spyder IDE #%%. Black adds a space after the #, thus preventing the use of either. I know how to use #fmt: off, but they quickly pollute the ouput. If there any workaround? Thanks.

**Comment by ambv** [comment]
Thanks for your report!

**Comment by piccolbo** [comment]
WFM, sweet!
