### ISSUE TITLE
attrs<17.3.0 does not provide dataclass

### ISSUE THREAD

**Issue by jeremylow** [ambv/black#54]
Operating system: Linux
Python version: 3.6.4
Black version: 18.3a3
Does also happen on master: N/A

I installed black install an existing project that makes use of attrs via hypothesis. Since black doesn't require a specific version of attrs, the existing installation was used causing this issue. In order to fix the issue, I installed the latest version of [attrs==17.4.0](https://pypi.org/project/attrs/17.4.0/). The old version was 17.2.0, which doesn't provide `attr.dataclass`. Looks like `attr.dataclass` was introduced in version 17.3.0.

Regarding if this issue occurs on master: not really. Installing black by itself into a clean virtualenv doesn't cause any problems, since the latest version of attrs is used.

Solution may be to pin the dependency at:

```python
install_requires=['click', 'attrs>17.2.0'],
```

in https://github.com/ambv/black/blob/1b696555e18afdfee3ca45526370de1af2cd961d/setup.py#L43

**Comment by ambv** [comment]
Good call, will pin the dependency.

**Comment by ambv** [comment]
Thanks for your report, this is now fixed! ✨ 🍰 ✨

**Comment by jeremylow** [comment]
Awesome!
