### ISSUE TITLE
Single number separator is lost when formatting

### ISSUE THREAD

**Issue by jacebrowning** [ambv/black#540]
Operating system:
Python version: 3.7.0
*Black* version: 18.9b0
Does also happen on master: Yes

---

```
number = 40_000
```

is now formatted to:

```
number = 40000
```

This changed when upgrading from `18.6b4` to `18.9b0`

**Comment by JelleZijlstra** [comment]
I can't reproduce this, and in fact Black should *add* the underscores now. How exactly are you invoking Black?

**Comment by jacebrowning** [comment]
@JelleZijlstra I now see there is a different behavior depending on the number of "commas" in the number and have updated my report. 

https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABcAD9dAD2IimZxl1N_WmFzNQnFDGDoFiRINmzoSa7z7R5VPSpn8su7TQiBIeoZHxyjkDPItDIUY68itFLp_hPnVzzTDgAA_3J00oNU1jIAAVtd_RwTbB-2830BAAAAAARZWg==

**Comment by jacebrowning** [comment]
I've also noticed this change:

```
- 'timestamp': 1531785600.0,
+ 'timestamp': 1_531_785_600.0,
```

**Comment by JelleZijlstra** [comment]
That's intentional, see the changelog: https://github.com/ambv/black#189b0.

**Comment by zsol** [comment]
Underscores are only added for numeric literals with more than 5 digits. All of these are blackened:
```
100_000
10000
10000.00001
100_000.0
```

**Comment by ambv** [comment]
We're only adding underscores for large numbers. For five digit numbers and smaller underscores are excessive in our view. But for bigger numbers it's unambiguously helpful so we put them in.

Remember that Black doesn't look at existing formatting, it will standardize the style regardless of the source's formatting.
