### ISSUE TITLE
Mention in docs that int formatting only adds underscores above 10000

### ISSUE THREAD

**Issue by underyx** [ambv/black#546]
Just spent a while looking for this info to give some teammates peace of mind that we won't start seeing 2_018, 1_024, and so on. I had to read the code to find out when underscores are added, which is not catastrophic, but not ideal either

**Comment by zsol** [comment]
Yes, we should make the docs clearer on this. Wanna put up a pr?

**Comment by underyx** [comment]
I could, yep! Opened the issue from my phone so I couldn't do it then. I saw some discussions about the logic and now it seems more complex than 'above 10000' though. Could you describe what rules I should document?

**Comment by zsol** [comment]
For integers longer than 5 digits, underscores are used. For floats, this rule applies to both sides of the decimal point

**Comment by underyx** [comment]
Not needed anymore, as the feature was removed due to https://github.com/ambv/black/issues/549
