### ISSUE TITLE
Cannot parse dict comprehension with negative number

### ISSUE THREAD

**Issue by vaer-k** [ambv/black#55]
Operating system: MacOS 10.12.6
Python version: 3.6
Black version: 18.3a3
Does also happen on master: yes

`{a: b * -2 for a, b in dictionary.items()}`
becomes
`{a: b * -2for a, b in dictionary.items()}`

which, surprisingly to me, doesn't break, but is clearly wrong.

`{a: b * 2 for a, b in dictionary.items()}`
is not affected by this issue (black leaves it alone.)

**Comment by ambv** [comment]
Thanks for your report! This is now fixed. ✨ 🍰 ✨
