### ISSUE TITLE
Multiline strings have inconsistent quoting

### ISSUE THREAD

**Issue by WouldYouKindly** [ambv/black#556]
Hi!

I've had this code:
```
s = (
    'psql $DSN -c "\copy {table}  '
    'FROM STDIN DELIMITER \',\' CSV"'
)
```

And *Black* gave me this:
```python
s = (
    'psql $DSN -c "\copy {table}  '
    "FROM STDIN DELIMITER ',' CSV\""
)
```

I don't like how on the first line there are single qoutes, while the second line is double-quoted. Is this intentional? Do you think it should be chaged?

Operating system: `Mac OS`
Python version: `3.7`
*Black* version: `18.9b0`
Does also happen on master: `yes, checked on playground`

**Comment by svanburen** [comment]
`black` prefers double quotes: https://github.com/ambv/black#strings

Your first line has an un-escaped double quote though, so `black` leaves it as is to avoid adding more escapes (as detailed in the link above)

**Comment by zsol** [comment]
As @svanburen mentioned, black _prefers_ double quotes, but readability is more important, so it tries to minimize the number of escaping inside the string.

**Comment by WouldYouKindly** [comment]
I can see your point, but would argue that readability actually suffered, because it's not obvious from the first sight that it's even the same string.

Anyway, thank you.

**Comment by samuelcolvin** [comment]
@ambv would reconsider this?

It seems to me beyond debate that the current behaviour is wrong. While it might not be covered by a PEP, I can't imagine any code would intentionally use differing quotes in the same split string.

The following:
```py
test = (
    'testing "testing" testing testing testing testing testing '
    'testing testing testing testing testing testing testing'
)
```
Gets converted to:
```py
test = (
    'testing "testing" testing testing testing testing testing '
    "testing testing testing testing testing testing testing"
)
```

Confirmed on `18.9b0` both pypi and master.
