### ISSUE TITLE
Spaces before colon cause pycodestyle to fail

### ISSUE THREAD

**Issue by StylishTriangles** [ambv/black#565]
Operating system: Ubuntu 18.04
Python version: 3.6.5
*Black* version: 18.9b0
Does also happen on master: yes

Here is a diff when running black on following example:
```diff
-    commits_data = commits[start_revision - 1: end_revision]
+    commits_data = commits[start_revision - 1 : end_revision]
```
This causes latest version of pycodestyle (2.4.0) to fail with message `E203 whitespace before ':'`

**Comment by zsol** [comment]
`E203` is broken, please disable it. https://github.com/PyCQA/pycodestyle/issues/373
