### ISSUE TITLE
pyproject.toml not read by vim plugin

### ISSUE THREAD

**Issue by Fandekasp** [ambv/black#568]
Operating system: Arch linux
Python version: 3.7.0
*Black* version: 18.9b0

We have a django repository with the following pyproject.toml file:
```toml
[tool.black]
line-length = 79
skip-string-normalization = true
include = '\.py?$'
exclude = '''
/(
    \.git
  | keys
  | templates
  | dist
  | keys

  # The following are specific to Black, you probably don't want those.
  | blib2to3
  | tests/data
)/
'''
```

In addition, I installed the vim plugin with the following conf in .vimrc
```vim
Plug 'ambv/black', {'for': 'python'}
autocmd BufWritePre *.py execute ':Black'
```

Now, by default black will set a max-length of 88 and use double-quotes on python files, which is fine as a default. But our project specifies a line-length of 79 and to skip string normalization (ie keep single quote strings as is), yet when saving my files all single-quote strings are converted back to double quotes.

Searching inside the [plugin file](https://github.com/ambv/black/blob/master/plugin/black.vim), I cannot find any mention of pyproject.toml

And the [README](https://github.com/ambv/black/#where-black-looks-for-the-file) says:

> Where Black looks for the file
> By default Black looks for pyproject.toml starting from the common base directory of all files and directories passed on the command line. If it's not there, it looks in parent directories. It stops looking when it finds the file, or a .git directory, or a .hg directory, or the root of the file system, whichever comes first.

How can I get my project's pyproject.toml configuration to be prioritized when editing said project's files from vim ?

**Comment by jgirardet** [comment]
See #414

**Comment by Fandekasp** [comment]
Thanks @jgirardet ! Indeed, this was a duplicate. closing
