### ISSUE TITLE
Document standard input/output handling

### ISSUE THREAD

**Issue by proofit404** [ambv/black#57]
Hi!

Thanks for the great package!

I'm interested to implement Emacs text editor integration for black.

Is it possible to pass file content to standard input followed by EOF and get the formatted code at the standard output?

Instead of replacing file content in place. This will allow preserving undo history of the editor buffer.

Regards, Artem.

**Comment by ambv** [comment]
Yes. Just put "-" as the name of the file. This is the standard Unix way to do this. I will document it so it's obvious.

**Comment by proofit404** [comment]
Great, thanks!
