### ISSUE TITLE
Black produced different code on the second pass of the formatter.

### ISSUE THREAD

**Issue by gr4viton** [ambv/black#575]
Operating system: linux ubuntu
Python version: probly something like 2.7
*Black* version: black, version 18.6b4
Does also happen on master: maybe - kidding - probly nope you can care to try it again

# what
`Black produced different code on the second pass of the formatter.`

+ also you should not put the dot at the end of the url, it takes you to Kansas otherwise
```diff
- Please report a bug on https://github.com/ambv/black/issues. This dif...
+ Please report a bug on https://github.com/ambv/black/issues . This dif...
```
## error cli
```
error: cannot format /dada/dada.py: INTERNAL ERROR: Black produced different code on the second pass of the formatter.  Please report a bug on https://github.com/ambv/black/issues.  This diff might be helpful: /tmp/blk_2b7b0tid.log
```

Ran black like: `black /dada/dada.py --check`

# pass
- [first pass](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEJAJRdAD2IimZxl1N_Wlws4ToyU3Y1WPxi5MQdOS2JmcblG6JdabQRhINTqvM0QBqGnjmcvpj9WUPPWWWmQzH9M6pWUbf5UR1ECZtUPRpbbV1iqthB1eOFJSRfIzlNlxxjUexcOwvbW8n0AbqhTP1e3RSaesjWS4Gefa-mtWNERRzFnlZ8EJxV66W1hoc6tkPdMayO5nmWXDEAbV6ryffwx3sAAbABigIAAClsn2WxxGf7AgAAAAAEWVo=)
- [second pass](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AEgAJpdAD2IimZxl1N_Wlws4SR2T8ZZSNWZVAhexvwHfgl8wEY4AsXj5DLCvOvgVdnEeRGpsLOvxdh_2eVdCuUw2s3Cg4Ipp_nuPJyhS_GtFsQSnNgBjg9q2atRHRMxH_RLM35jcG4tJco_3yNip7BZtvH5KrxmRytkxlHR63unc6nWLM2cYNgWpVSmVV3JgSqaLDYAiX_4hS8JgzqxrwAAAAD33TKJTq2c7QABtgGhAgAAC6f1xLHEZ_sCAAAAAARZWg==)

# Scrambled diff
```diff
--- source
+++ first pass
 
@@ -447,25 +499,30 @@
                 if self.secret == "secret":
                     secret = "secret.secret.secret"
 
                 secret = "secret"
-                if xxxxxx.yyyyyyy_xxxx.__class__ != ttttt.DobeRobe and hasattr(  # noqa: E721
-                    xxxxxx.yyyyyyy_xxxx.pepepep, "bbbbbb"
+                if (
+                    xxxxxx.yyyyyyy_xxxx.__class__ != ttttt.DobeRobe
+                    and hasattr(xxxxxx.yyyyyyy_xxxx.pepepep, "bbbbbb")  # noqa: E721
                 ):
                     yyyyyyy_xxxx_name = xxxxxx.yyyyyyy_xxxx.pepepep.bbbbbb
                 bobuld = parachute_doris.asdat_asdsa(
                     args=(fo_foian(ronalda),),
                     buwas=buwas,
--- first pass
+++ second pass
@@ -504,14 +504,13 @@
                 if self.secret == "secret":
                     secret = "secret.secret.secret"
 
                 secret = "secret"
-                if (
-                    xxxxxx.yyyyyyy_xxxx.__class__ != ttttt.DobeRobe
-                    and hasattr(xxxxxx.yyyyyyy_xxxx.pepepep, "bbbbbb")  # noqa: E721
-                ):
+                if xxxxxx.yyyyyyy_xxxx.__class__ != ttttt.DobeRobe and hasattr(
+                    xxxxxx.yyyyyyy_xxxx.pepepep, "bbbbbb"
+                ):  # noqa: E721
                     yyyyyyy_xxxx_name = ffffff.yyyyyyy_xxxx.pepepep.bbbbbb
                 bobuld = parachute_doris.asdat_asdsa(
                     args=(fo_foian(ronalda),),
                     buwas=buwas,
```

Sorry for the longpost here's an ascii potato: ()

**Comment by cas--** [comment]
Please update the title with a proper description of the issue that has been found. 

Also at time of writing the latest stable version is `18.9b0` and doesn't show this issue so perhaps close this ticket?

**Comment by gr4viton** [comment]
Could not reproduce in latest stable version.
