### ISSUE TITLE
Trailing comments cause unnecessary optional parentheses

### ISSUE THREAD

**Issue by deckar01** [ambv/black#576]
Operating system: Ubuntu 18.04
Python version: 3.6.6
*Black* version: 18.9b0
Does also happen on master: Yes ([example](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AGNAQpdAD2IimZxl1N_WlkOEznFeHcSXu8_XA3021O0vuVt_K6ldWu6rlv3qq_SsnRojNYej-JXPz8YLdom0rid6__kpPpxbjxFpG8FvONGycZnvluc0YQgVfY9h2-Bfow9GeO1pJok95J6wOcQexjcDybJ9Tm9WapkDUW2vE5mjQ250VRxMltJyEfYiGrkGmWj7puFXYpffhr6dyxOcWwk6y4hEr4kU6VJ02kyWC_8mOm1c-vqYdd-14SZTRQieh-SXClPVKQLQWOQGP0s1JM5TRebaYivUp1aHpFMZr5F1oAEEsQ1aqKKHWJQOI6v2DNwKnwPduHPl4cIPA8F_g1jYxos2Y_Ty9Pds4jE9V72AAAA5M-4Wh1aeF4AAaYCjgMAAB8KEHmxxGf7AgAAAAAEWVo=))
Related issues: #232

## Reproduction steps

1. Write a line of code
2. Add a long comment at the end of the line of code that exceeds the maximum line length

```py
foo = 'bar baz bing boo blah'  # This is a long comment that really shouldn't be at the end of a line in the first place, but black leaves it at the end of the line and uses it to decide if the actual expression needs parenthesis even though it doesn't and adding them has a very small chance of fixing the line length
```

## Actual behavior

The code to wrap with parenthesis and put an a separate line.

```py
foo = (
    "bar baz bing boo blah"
)  # This is a long comment that really shouldn't be at the end of a line in the first place, but black leaves it at the end of the line and uses it to decide if the actual expression needs parenthesis even though it doesn't and adding them has a very small chance of fixing the line length
```

## Expected behavior

No parenthesis or wrapping. The length of the comment should not be included in the calculation that determines if the code should wrap.

```py
foo = 'bar baz bing boo blah'  # This is a long comment that really shouldn't be at the end of a line in the first place, but black leaves it at the end of the line and uses it to decide if the actual expression needs parenthesis even though it doesn't and adding them has a very small chance of fixing the line length
```

**Comment by JelleZijlstra** [comment]
I've also encountered this and it produces rather ugly output. I'd prefer if Black in this case moves the comment to the previous line.

**Comment by gricey432** [comment]
@JelleZijlstra wouldn't that break type comments?

```
foo = 'bar'  # type: str
```
```
# type: str
foo = "bar"
```

**Comment by JelleZijlstra** [comment]
That's true, and also other tools' special comments (noqa and similar).

**Comment by matejcik** [comment]
dup of #374 
(no progress there but at least now the bugs are linked)

**Comment by deckar01** [comment]
Thanks for finding that @matejcik.
