### ISSUE TITLE
using from within in a Python 2 virtual environment?

### ISSUE THREAD

**Issue by indirectlylit** [ambv/black#585]
We'd love to use `black` in our project, but the Python 3 requirement makes this difficult because our application needs to be able to be developed and run under both 2 and 3.

Any tips for integrating `black` into a version-agnostic development environment?

**Comment by JelleZijlstra** [comment]
As @jgirardet says, Black formats Python 2 code correctly already. We're unlikely to make it possible to run Black under a lower Python version, but that's not necessary to use the tool.

**Comment by indirectlylit** [comment]
Thanks for the info! Yeah I'm aware that it formats py2 code fine which is why we want to use it.

I'd like to avoid requiring our developers to `sudo pip3 install black`: there are many possible ways people install Python, so asking people to install global packages seems like risky advice to support. Currently it's easier for us to say "if things are broken, make a new virtual environment".

If `black` had some system-level installers to hide the details (e.g. through `apt`, `brew`, and a windows installer) that would be easier for us to incorporate into our developer setup guide.

Similarly, running a `blackd` instance is an interesting idea if we had a foolproof way of recommending devs install it on their local machines.

**Comment by rooterkyberian** [comment]
you can also run it in Docker: https://github.com/jbbarth/docker-black

**Comment by asottile** [comment]
`sudo pip` / `sudo pip3` should really not be used -- if you must use `pip install --user`.  I personally don't like usersitedir so I set up a virtualenv in my homedirectory as follows:

```bash
virtualenv ~/opt/venv
~/opt/venv/bin/pip install black
ln -sf ~/opt/venv/bin/black ~/bin/black
```

and then I put `~/bin` on my `PATH`

**Comment by cas--** [comment]
Surprised that no one has mentioned that [pre-commit ](https://pre-commit.com) creates a Py3.6 venv just for black.

Black docs: https://github.com/ambv/black#version-control-integration

From our [pre-commit config](https://github.com/deluge-torrent/deluge/blob/develop/.pre-commit-config.yaml):
```yaml
repos:
  - repo: https://github.com/ambv/black
    rev: 18.9b0
    hooks:
      - id: black
        name: Fmt Black
        language_version: python3.6
```

Run from terminal with:

    pre-commit run --all-files
    pre-commit run --files test.py

**Comment by indirectlylit** [comment]
that looks like the correct answer - closing :)

**Comment by vikas1018** [comment]
@JelleZijlstra: Do we need to specify language version as `language_version: python2.7` in pre-commit-config.yaml to format python2.7 codebase?

**Comment by cas--** [comment]
@vikas1018 Black requires no configuration to format Py2.7 code. 

The `language_version` option is to tell pre-commit to run Black under Python 3.6 interpreter.

**Comment by indirectlylit** [comment]
Just to follow-up: while the pre-commit integration is potentially useful, the fact that Black requires >= python 3.6 makes it much less useful. Our developers run a variety of versions of Python 3. For example, the latest `brew` installs 3.7 and Ubuntu has 3.5.

Therefore we've been exploring distributing self-contained binaries built using PyInstaller as described in https://github.com/ambv/black/issues/362

It's a lot of hoops to jump through, but the benefits seem worth it. Would love to see Black either support all versions of Python 3 or have official self-contained installers for major operating systems in the future to support the diversity of developer and CI environments.

**Comment by indirectlylit** [comment]
looks from https://github.com/ambv/black/issues/521 like py 3.5 support will not be happening

**Comment by asottile** [comment]
For ubuntu xenial if you're willing to use a ppa: [deadsnakes](https://github.com/deadsnakes) ([PPA page](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa)) provides backports of 3.6 / 3.7 / 3.8 

with pypy3.6 available I assume it'll work pretty soon -- some cursory tests shows it breaks for [this](https://bitbucket.org/pypy/pypy/issues/2985/pypy36-osreplace-pathlike-typeerror)

this patch makes black work with pypy3.6 though:

```diff
$ diff -u /tmp/t/pypy3.6-v7.1.0-linux64/site-packages/black.py{.old,}
--- /tmp/t/pypy3.6-v7.1.0-linux64/site-packages/black.py.old	2019-03-31 12:35:22.813881755 -0700
+++ /tmp/t/pypy3.6-v7.1.0-linux64/site-packages/black.py	2019-03-31 12:34:40.597881755 -0700
@@ -3721,7 +3721,7 @@
         new_cache = {**cache, **{src.resolve(): get_cache_info(src) for src in sources}}
         with tempfile.NamedTemporaryFile(dir=str(cache_file.parent), delete=False) as f:
             pickle.dump(new_cache, f, protocol=pickle.HIGHEST_PROTOCOL)
-        os.replace(f.name, cache_file)
+        os.replace(f.name, str(cache_file))
     except OSError:
         pass
 
```

**Comment by jcopps** [comment]
> you can also run it in Docker: https://github.com/jbbarth/docker-black

Love this. Very helpful and handy.

**Comment by ichard26** [comment]
If compatibility isn't an issue, the upcoming black updates (can't give you a timeframe) should have OS native binaries available through GitHub Releases. ex. the `black` file in this release: https://github.com/psf/black/releases/tag/19.10b0 (although this version is quite old!)
