### ISSUE TITLE
Black removes newlines in code purposefully separated out to improve readability

### ISSUE THREAD

**Issue by butla** [ambv/black#586]
Operating system: Kubuntu 18.04 x64
Python version: 3.6.6
*Black* version: 18.9b0
Does also happen on master: Yes

Black seems like a great tool, but I have some issues after running it against one of my projects. In function definitions and calls I sometimes introduce newlines just so they don't look too dense, which may happen with longer names (which, I think, can occur when striving for self-descriptability of the code). To illustrate, this:

```
def __init__(
            self,
            params: UploaderParams,
            kinesis_client,
            event_loop: asyncio.AbstractEventLoop):
        self._params = params
        self._loop: asyncio.AbstractEventLoop = event_loop
        self._kinesis_client = kinesis_client
        self._buffer = EventsBuffer(
            params.events_buffer_params,
            stream_name=self._params.kinesis_stream,
        )
```

gets turned into 
```
def __init__(
        self, params: UploaderParams, kinesis_client, event_loop: asyncio.AbstractEventLoop
    ):
        self._params = params
        self._loop: asyncio.AbstractEventLoop = event_loop
        self._kinesis_client = kinesis_client
        self._buffer = EventsBuffer(
            params.events_buffer_params, stream_name=self._params.kinesis_stream
        )
```

which in my opinion is harder on the eyes to parse. I didn't use syntax coloring on purpose, cause it's not there always when I'm looking at the code.

Is it possible to make Black leave the newlines I put in there on purpose alone? I know that can use comments to disable the formatting, but for me this just introduces new problems: more visual clutter, having to remember to type the comments.

**Comment by JelleZijlstra** [comment]
The general idea behind black is to move code to a consistent style, without regard to the previous formatting. This ensures that code formatted using black is always consistent.

Splitting up long argument/parameter lists over multiple lines depending on previous formatting would make black-formatted code inconsistent in style and make the tool harder to implement, so we're unlikely to change anything here.

**Comment by butla** [comment]
OK, no hard feelings.
