### ISSUE TITLE
Internal error on a complex variable type annotation

### ISSUE THREAD

**Issue by roganov** [ambv/black#59]
Black reports internal error on this code

```python
import typing as t

filters: t.List[
    t.Tuple[str, t.Union[str, t.List[t.Optional[str]]]],
] = []
```

Operating system: Ubuntu
Python version: 3.6.3
Black version: 18.3a3
Does also happen on master: yes

**Comment by ambv** [comment]
Oh, this is a bit tricky. When you are indexing in Python, commas create implicit tuples. In other words:
```
some_dict[1] == some_dict.__getitem__(1)
some_dict[1,] == some_dict.__getitem__( (1,) )
```

So the bug here is that Black needs to avoid messing with trailing commas within square brackets if they are indexing and not list literals.

Thanks for your report! ✨ 🍰 ✨

**Comment by ambv** [comment]
Alright, I fixed my bug. Now fix yours: your List[] type shouldn't have a trailing comma, that makes an implicit tuple.
