### ISSUE TITLE
Comments being left justified, bad when comments are stubbed out code - just leave them alone

### ISSUE THREAD

**Issue by jvahue** [ambv/black#596]
Operating system: Black Playground 11/6/2018
Python version: Black Playground 11/6/2018
*Black* version: Black Playground 11/6/2018
Does also happen on master: 

Put a file in to try out Black and saw all my commented out code was left justified, making it difficult to bring the code back by un-commenting it.

**Comment by zsol** [comment]
You can wrap your commented out code in `# fmt: off` `# fmt: on` blocks to preserve whitespace in them

**Comment by jldevezas** [comment]
I know this has been closed for a whole now, but I believe this should be reconsidered. During debugging, it's normal for blocks of code to be temporarily commented out. If black indents this under, let's say, the previous `if `, when it should be under the same level, then a distracted programmer could easily uncomment the block and wrongly leave it under the `if` block. Does this concern make sense? It seems to me black is making a wrong choice here. Even if the comment were a regular comment, why would black reposition it inside the previous block?

**Comment by JelleZijlstra** [comment]
If you comment out code like this:

```
    if sources:
        # try:
        #     res = mypy.build.build(sources=sources, options=options)
        # except mypy.errors.CompileError as e:
        #     raise StubtestFailure(f"failed mypy compile:\n{e}") from e
        # if res.errors:
        #     raise StubtestFailure("mypy build errors:\n" + "\n".join(res.errors))

        global _all_stubs
        _all_stubs = res.files
```
Black will leave the leading space alone. That's how most editors do it by default if you use a command like Cmd+/.

**Comment by jldevezas** [comment]
@JelleZijlstra That's not it. Here's an example of what I mean:

```python
if cond1:
    print("code here")

if cond2:
    print("more code here")
```

If you comment the second `if`, you will get this:


```python
if cond1:
    print("code here")

    # if cond2:
    #     print("more code here")
```

If you uncomment back, you will get:

```python
if cond1:
    print("code here")

    if cond2:
        print("more code here")
```

You might not agree, but I personally find this inconsistent behavior, worth taking a look at, as it's not uncommon at all.

**Comment by JelleZijlstra** [comment]
I can't reproduce that behavior: https://black.vercel.app/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AC6AHBdAD2IimZxl1N_Wlws4TQhI6pD0uXxX7RR5ooUKbRVtOLg_Eitq-VXSdyageOasnuvhgRQERodoovGPR-g93fi5gA8aGFfLYB8uPwWZPFIhrZNXmrQ2qw6IoFz9k9L043WBXpU731yEmRVWwQLqqhKyQAAXKJ4MH91ShgAAYwBuwEAAGKK9lyxxGf7AgAAAAAEWVo=

**Comment by jldevezas** [comment]
You're right. I can't reproduce it either on vscode now (different machine). Perhaps there is some other formatter (from my side) causing the issue. I will confirm whether or not it was black and let you know. I thought it was a design choice, but it doesn't look that way, so I'm fine with it. Thanks for the clarifications!
