### ISSUE TITLE
Leave alone blank lines in multiline function calls

### ISSUE THREAD

**Issue by alok** [ambv/black#597]
Python version: 3.7.0
*Black* version: master

This is relevant for a lot of machine learning frameworks, which tend to split up function calls into groups of related keyword arguments (e.g. args related to logging in one group, args related to tuning parameters in another, etc`). It's also used for defining neural networks, like

```python
nn.Sequential(
    a,
    b,
    c,

	d,
    e,
    f,
)
```
where `a, b, c` and `d, e, f` are part of the same "layer".

`black` removes the blank line between these blocks, making code very hard to read. The workaround of putting a blank comment between them is also rather ugly. I think that much like single blank lines outside of function calls, single blank lines inside them should be left alone unless the whole call could fit on a single line.

**Comment by zsol** [comment]
@alok sorry but this is unlikely to be supported by black. I would argue that this is not a great API design, but there's not much you can do about that. One workaround you can do that will make your code readable regardless of whether you use black is to group arguments together like so:
```
first = (a, b, c)
second = (d, e, f)
nn.Sequential(*first, *second)
```
