### ISSUE TITLE
relative imports convert `. .` to `..`

### ISSUE THREAD

**Issue by maxim-lian** [ambv/black#6]
Excited about the effort - thanks for kicking this off! Hopefully of what yapf once dreamed

One quick issue when scanning the output: is this intended?

```
# existing
from ..convert import from_iris

# black
from . .convert import from_iris
```

**Comment by ambv** [comment]
No, this is not intended. Extra spaces might appear here and there for a while. That's the safe default for unrecognized code patterns. I can reproduce this and will fix shortly.

**Comment by ambv** [comment]
Thank you for your report, this is now fixed!

**Comment by maxim-lian** [comment]
Thank you for such a fast turnaround!
