### ISSUE TITLE
--skip-numeric-underscore-normalization missing from the command line options section in documentation

### ISSUE THREAD

**Issue by monocongo** [ambv/black#602]
The option to skip numeric underscore normalization is present in the README but not in the documentation. I've already looked into fixing this but apparently the way the documentation is generated makes this more complicated than just adding one line into the relevant section of `docs/index.rst`. (My doc-fu is weak.)

BTW thanks for such good documentation, someone has obviously put a lot of time into that.

![screenshot from 2018-11-12 10-43-12](https://user-images.githubusercontent.com/1328158/48358704-55c92400-e669-11e8-8723-087369c618c1.png)

**Comment by zsol** [comment]
RIP `--skip-numeric-underscore-normalization` it was fun while it lasted
