### ISSUE TITLE
Black formats pyenv builtin library files outside of project folder

### ISSUE THREAD

**Issue by gtalarico** [ambv/black#603]
Apologies in advance if I am missing something obvious, but I am not sure how I managed to do this.
I used `black .` from my project directory, thinking it would format my project files, instead, I accidentally formatted my entire pyenv venv builtin library 😂 

```bash
~/dev/kit
(venv) ❯❯❯ which black
/Users/gtalarico/dev/kit/venv/bin/black
~/dev/kit
(venv) ❯❯❯ black .
reformatted /Users/gtalarico/.pyenv/versions/3.7.0/lib/python3.7/_bootlocale.py
reformatted /Users/gtalarico/.pyenv/versions/3.7.0/lib/python3.7/__future__.py
reformatted /Users/gtalarico/.pyenv/versions/3.7.0/lib/python3.7/_dummy_thread.py
reformatted /Users/gtalarico/.pyenv/versions/3.7.0/lib/python3.7/abc.py
reformatted /Users/gtalarico/.pyenv/versions/3.7.0/lib/python3.7/bisect.py
reformatted /Users/gtalarico/.pyenv/versions/3.7.0/lib/python3.7/_weakrefset.py
reformatted /Users/gtalarico/.pyenv/versions/3.7.0/lib/python3.7/base64.py
... (my entire venv builtin lib)
```

Operating system: MacOs
Python version: 3.7.0
*Black* version: 18.9b0

Relevent Environment Variables:
```env
PATH=/Users/gtalarico/dev/kit/venv/bin:/usr/local/opt/openssl/bin:/usr/local/opt/openssl/bin/:/Users/gtalarico/.pyenv/shims:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
PIPENV_DEFAULT_PYTHON_VERSION=3.7
PWD=/Users/gtalarico/dev/kit
PYENV_SHELL=fish
PYENV_VERSION=3.7.0
PYTHONSTARTUP=/Users/gtalarico/.pythonrc
SHELL=/usr/local/bin/fish
VIRTUAL_ENV=/Users/gtalarico/dev/kit/venv
VIRTUAL_ENV_DISABLE_PROMPT=1
```

**Comment by zsol** [comment]
Clearly we need to make sure virtualenv itself is blackened ;)

**Comment by zsol** [comment]
Looks like there's a symlink in `~/dev/kit/venv` that points to the actual virtualenv, which is why black formats it. You can exclude it with command line flags

**Comment by gtalarico** [comment]
Awesome, thanks Zsol.
Seems obvious now.... it just followed the symlinks inside `venv`...
I usually use `virtualenvwrapper` so I am not used to having the virtualenv inside my project folders.

`black . --exclude venv/`  works as expected

![image](https://user-images.githubusercontent.com/9513968/48442448-45de3c80-e75c-11e8-852b-ec457685ff18.png)
