### ISSUE TITLE
Split the left side of an assignment if longer

### ISSUE THREAD

**Issue by Khoyo** [ambv/black#610]
Operating system: GNU/Linux
Python version: 3.6
*Black* version: 18.9b0
Does also happen on master: yes

In our codebase, we sometimes have long tuple unpacking in one assignment, like:

```
a, b, c, d, e, [...], z = args
```

Since these run well over the line length limit, black transform them to:

```
a, b, c, d, e, [...], z = (
    args
)
```

But these still run over the limit.

It would be much better to convert to:

```
(
    a,
    b,
    c,
    d,
    e,
    [...],
    z,
) = args
```

Which black already does if you parenthesize the left side.

(I understand these long assignments are bad, but this is a large codebase and the refactoring necessary to stop this is non-trivial)

**Comment by amiller27** [comment]
Seconding this.  This can happen pretty quickly if the variable names aren't super short as well (i.e. I'm having this problem with only four things on the left hand side instead of seven).

**Comment by zsol** [comment]
Let's discuss in #656 which has more examples
