### ISSUE TITLE
Invalid code when comments inside import statement parentheses

### ISSUE THREAD

**Issue by fredley** [ambv/black#612]
Operating system: OSX
Python version: 3.6.5
*Black* version: 18.9b0
Does also happen on master: [Yes](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADDAHpdAD2IimZxl1N_WlXnON2nzNG_BfI5BzQfpPnalTlFrncmY0kglaZF122ozJl2ID89TjNVJdFk4uwWiWtwKNajut2v3G-dDw4JA_rfQEjggTuIlxr9WYzHTa6B9YErlR-b71jPUf4rFi1Yp3bfE6hpS-Cw8x52yBRaBcgeAAAAiGxBBU-FP0QAAZYBxAEAAFUb582xxGf7AgAAAAAEWVo=)

Input:
```
class BlackFail:
    def fail(self):
        from os.path import (
            join,
            # FAIL
        )
```

Expected output:
(Same as input)

Actual output:
```
class BlackFail:
    def fail(self):
        from os.path import (
            join,
            # FAIL
            ,
        )
```

Hanging comma causes black to produce invalid output.

**Comment by scotchka** [comment]
Simpler code that produces same error:
```
from random import (
    random,
    # comment
)
```

**Comment by scotchka** [comment]
Also, comma is inserted AFTER the comment:
```
from random import (
	random
	#comment
)
```
blackens to
```
from random import (
    random
    # comment
    ,
)
```

**Comment by zsol** [comment]
Let's keep the discussion in #671
