### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by normoes** [ambv/black#624]
Please include the usage of `--exclude` into the README.

I was struggling to find how to use it:
```
black . --diff --exclude '\.venv/|\.local/|\.cache/|\.git/|migrations/'
```

I was missing the `'...'`.

**Comment by JelleZijlstra** [comment]
dupe of #623

**Comment by normoes** [comment]
Two times?
Sorry, can't remember putting it here two times :)
Thanks for closing it!
