### ISSUE TITLE
how safe is black?

### ISSUE THREAD

**Issue by komuw** [ambv/black#625]
Hi, 

I'm thinking of running black on one of my services in one go(one pull request) and deploy it to production. 

- Is it safe to do so?
- Is there a possibility of black introducing bugs?

cc @ambv @zsol

**Comment by JelleZijlstra** [comment]
Yes, this should be safe unless you're doing something very weird. Black has an internal safety check that makes sure that the AST stays the same before and after it runs, so the Python code you're running should stay the same.

The main problem you're likely to run into is that magical comments used by some tools (e.g., `# type: ignore`, `# noqa` and similar) will be moved around. After you run Black you may have to manually correct the placement of some of these comments. That's the only problem I ran into when applying Black to a huge internal codebase.

In theory there could be other issues if your code does something like inspect its own source code at runtime and extract information using a regex, but, well, I hope you don't do that.

**Comment by komuw** [comment]
@JelleZijlstra thanks, thats super helpful.
