### ISSUE TITLE
Formatting heavily nested code

### ISSUE THREAD

**Issue by klahnakoski** [ambv/black#626]
This is a please-change-formatting request.  I do not think it conflicts with existing rules.

Here is a piece of code that Black formatted, but it is a bit ugly:

        config = Config(
            **unwrap(
                set_default(
                    {},
                    config,
                    {
                        "overrides": {
                            "run": {
                                # "hide": True,
                                "out_stream": self.stdout,
                                "err_stream": self.stderr,
                            }
                        }
                    },
                )
            )
        )

If there is only one item enclosed in brackets, we can put it on the same line as the opening bracket:

        config = Config(**unwrap(set_default(
            {},
            config,
            {"overrides": {"run": {
                # "hide": True,
                "out_stream": self.stdout,
                "err_stream": self.stderr,
            }}},
        )))

Thank you.

**Comment by zsol** [comment]
I don't think the proposed formatting is more readable at all. In fact, I think both of them are pretty unreadable because of the amount of nesting going on.

I don't think there's much Black can do about this.
