### ISSUE TITLE
Syntax error in playground causes infinite loop

### ISSUE THREAD

**Issue by gvanrossum** [ambv/black#631]
**Black v18.9b0**

## Options

`--line-length=60`

## Input

```python
import (foo, bar)
```

## Output

No output; playground website hangs.

**Comment by gvanrossum** [comment]
Note that this is a syntax error. I've found that the playground hangs on other syntax errors as well (e.g. I tried `print(x := 1)`).

**Comment by zsol** [comment]
FWIW, black itself errors out as expected:
```
error: cannot format -: Cannot parse: 1:7: import (foo, bar)
```

**Comment by ambv** [comment]
@jpadilla, can you solve this on the black-playground end?

**Comment by jpadilla** [comment]
@ambv fixed, thanks! [link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABeAEFdAD2IimZxl1N_WlwxRhR7MSgAZsIFN6S51yWVOwcSRADn3GChFCG6kprRGX3wJBgiU8hSkvyvVF4oqtABksS_O75ZAAAAADQqtZbWytqoAAFdX1faR9QftvN9AQAAAAAEWVo=)
