### ISSUE TITLE
Black not handling multi line strings properly

### ISSUE THREAD

**Issue by sureshvv** [ambv/black#648]
**Black https://github.com/ambv/black/commit/fe24a1**

[Playground link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ABuAExdAD2IimZxl1N_WmBlye5upLBx2ppE2NkV5JGQWUIDe0AWAOSeSHuXJ4_pvwvYda-63u4md_cAm4_Nf_JhHXLMrMBs80jUMdnsisUVIQAA7K_4dRmNSxQAAWhvTSivUB-2830BAAAAAARZWg==)

## Options

`--line-length=60`

## Input

```python
msg = "Hello "
      "World"
```

## Output

```python
Cannot parse: 2:0:       "World"
```

## Expected

**Comment by JelleZijlstra** [comment]
That's a syntax error for Python too. You need to put your strings in parentheses or put a backslash at the end of the first line.
