### ISSUE TITLE
Why set splitted as all elements on new line?

### ISSUE THREAD

**Issue by zaz600** [ambv/black#650]
**Black v18.9b0**

[Playground link](https://black.now.sh/?version=stable&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ADdAFVdAD2IimZxl1N_Wk6rijOtxSJdXQe7iK2WB1hl91e_IFwmFN92gbCEHisS2hhUWeBZOANHTQqBktta6lZCsP8sS9rzIcp1dAthJi65shJFVoiW0ewetwAAAAAAjcQQQSw0FOgAAXHeAQAAAOSsUo2xxGf7AgAAAAAEWVo=)

## Options

`--line-length=60`
`--pyi`

## Input

```python

KEYS1 = {"aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa"}

KEYS2 = {"aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa"}

```

## Output

```python
KEYS1 = {"aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa"}

KEYS2 = {
    "aaaaa",
    "aaaaa",
    "aaaaa",
    "aaaaa",
    "aaaaa",
    "aaaaa",
}

```

## Expected
Something like this

```python
KEYS1 = {"aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa"}

KEYS2 = {
    "aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", 
    "aaaaa"
}
```

**Comment by zaz600** [comment]
# Problem


Base code
```python
KEYS1 = {"aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa"}
```

Alice make changes
```python
KEYS1 = {"aaaaa", "aaaaa", "aaaaa", "aaaaa", "bbbbb"}
```
Alice format code with black:
```python
KEYS1 = {"aaaaa", "aaaaa", "aaaaa", "aaaaa", "bbbbb"}
```

Bob make changes
```python
KEYS1 = {"aaaaa", "aaaaa", "aaaaa", "aaaaa", "aaaaa", "ccccc"}
```
Bob format code with black:
```python
KEYS1 = {
    "aaaaa",
    "aaaaa",
    "aaaaa",
    "aaaaa",
    "aaaaa",
    "ccccc",
}
```

We have ugly merge conflict two changes

**Comment by nicktimko** [comment]
In your example, the list was made longer, so you could extend that to making the list arbitrarily long. In that case, the solutions would seem to be one of 

* never break lists onto multiple lines
* *always* break lists (basically ignoring the line-length)
* look at the repository history and/or remember the past state of each variable (possibly also be sensitive to the number of committers?)

**Comment by reagle** [comment]
Sometimes I have similar structures, such as a list of a couple dozen words, or a hundred integers, and black forces them each to their own line, which is ghastly, as is the case in the third line:

```
ARTICLES = {'a', 'an', 'the'}
CONJUNCTIONS = {'and', 'but', 'nor', 'or'}
SHORT_PREPOSITIONS = {'among', 'as', 'at', 'by', 'for', 'from', 'in',
                      'of', 'on', 'out', 'per', 'to', 'upon', 'with', }
```

```
ARTICLES = {"a", "an", "the"}
CONJUNCTIONS = {"and", "but", "nor", "or"}
SHORT_PREPOSITIONS = {
    "among",
    "as",
    "at",
    "by",
    "for",
    "from",
    "in",
    "of",
    "on",
    "out",
    "per",
    "to",
    "upon",
    "with",
}
```

**Comment by reagle** [comment]
@nicktimko, thanks. I had searched the documentation for "disable" and "suspend" but hadn't come across `# fmt: off`.

**Comment by zsol** [comment]
As explained in the comments above, this is the intended behavior, and you can opt code out using `# fmt: off` and `# fmt: on` pairs.
