### ISSUE TITLE
Formatting of pandas expressions suboptimal for readability

### ISSUE THREAD

**Issue by clstaudt** [ambv/black#662]
Arguing with the formatting decisions of black may be besides the point, but I am pretty happy with it with the exception of one type of expressions:

```
        trend = matching_items.groupby(pandas.Grouper(key="ERDAT", freq=timeframe))[
            "KWMENG"
        ].sum()

```

This is a typical `pandas` expression where some method calls are chained and fields of the dataframe are selected. Black seems to treat the field selection as a list and indents it on a new line. I think this is counterintuitive and does not improve readability. Is it intentional or a potential enhancement to treat this differently?

Operating system: macOS
Python version:  3.7.0
*Black* version: '18.9b0'

**Comment by tuchandra** [comment]
This seems related to #571 - I'll +1 this as something that seems kind of bizarre.

**Comment by swenzel** [comment]
black won't reformat this unless your line is > `line-length`.
In one line, your statement would be 91 chars, the default `line-length` is 88.
Two solutions for that, either increase `line-length` or refactor your code so you get multiple shorter lines. For example:

```
grouper = pandas.Grouper(key="ERDAT", freq=timeframe)
grouped_items = matching_items.groupby(grouper)
trend = grouped_items["KWMENG"].sum()
```

I'd prefer the latter. This way you can provide more descriptive code. I'm certain you can find better names for `grouper` and `grouped_items` but you see what I mean.

Long lines with lots of in-line code and logic really aren't that great for readability...

**Comment by clstaudt** [comment]
"One of the hardest things in programming is naming things" - and especially intermediate results in pandas transform chains, that's why you are going to have a hard time convincing pandas programmers to adopt the unusual style you propose. I am going to disagree and say that chained method calls can be great for readability if formatted correctly.

**Comment by zsol** [comment]
Let's keep the discussion in #571
