### ISSUE TITLE
Black de-indents body of commented out functions/methods

### ISSUE THREAD

**Issue by pmav99** [ambv/black#668]
```
Operating system: 4.19.12-arch1-1-ARCH
Python version: 3.7.1
*Black* version: 18.9b0
Also happens on master: True
```
I did check the issues but I couldn't find this exact case being mentioned. 

I guess that, since the ast tree doesn't know anything about the commented function, this is not fixable but anyway:

**before**
``` python
def foo(arg1, arg2):
    print(arg1, arg2)


# def goo(arg1, arg2):
    # print(arg1, arg2)


class A(object):

    def foo(self):
        pass

    # def goo(self):
        # pass
```
**after**
``` python
def foo(arg1, arg2):
    print(arg1, arg2)


# def goo(arg1, arg2):
# print(arg1, arg2)


class A(object):
    def foo(self):
        pass

    # def goo(self):
    # pass
```

The problem with this is that if you use black on e.g. file save, you cannot comment out a function while developing, because you will not be able to uncomment it later on.

**Comment by zsol** [comment]
Sorry, figuring out if a comment is code or not is out of scope for a simple project like Black.
