### ISSUE TITLE
Possible inconsistency in keyword argument spacing with type hints

### ISSUE THREAD

**Issue by tweakimp** [ambv/black#678]
I dont know if this is supposed to be this way, but I think it is inconsistent.
```python
def test(arg=None):
    pass


def test2(arg:list=None):
    pass

```
becomes
```python
def test(arg=None):
    pass


def test2(arg: list = None):
#             ↑    ↑ ↑
    pass

```
If there is no type hint, there is no spacing in the keywords at all. If there is a type hint, there are spaces between the type hint, the `=` and the `None`.
Is that supposed to be that way?
[online test](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4AChAF5dAD2IimZxl1N_WlbvK5V_5PM4NcmuiXZ2wDnA5lpIxi_eK_wywYAcPOVanPhgmnv-F925CjDJbKRQiv3EJ3K8r-CaYWYAE_FCEGZjuSokjp3nU3T5XJaM8-EIuqRvGAAAAADqOjwgnHdEbwABeqIBAAAA6VG327HEZ_sCAAAAAARZWg==)

Operating system: Win 10, 64bit
Python version: 3.6.8
*Black* version: 18.9b0
Does also happen on master:
yes, checked with online test

**Comment by JelleZijlstra** [comment]
This is the standard convention for typed code; for example, https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#conventions wants it this way. I thought PEP 8 also mandates this style but I can't find it there now.
