### ISSUE TITLE
Black changes '#:' to '# :'

### ISSUE THREAD

**Issue by sfermigier** [ambv/black#68]
Operating system: Mac OS
Python version: 3.6.4
Black version: 18.3a3
Does also happen on master: yes

---

'#:' are used by Sphinx to generate documentation on object attributes.

Black erroneously changes them to '# :', like in this example:

```
-    #: Environment variable used to locate a config file to load last (after
-    #: instance config file). Use this if you want to override some settings
-    #: on a configured instance.
+    # : Environment variable used to locate a config file to load last (after
+    # : instance config file). Use this if you want to override some settings
+    # : on a configured instance.
```

**Comment by SethMichaelLarson** [comment]
I would argue it's not erroneous. There's supposed to be a space after a comment a-la PEP8.

**Comment by ambv** [comment]
Since Sphinx is so popular and we already don't split shebangs and ##, I will fix that.

**Comment by ambv** [comment]
This is now fixed. Thanks! ✨ 🍰 ✨
