### ISSUE TITLE
Consider more consistent/aggressive wrapping for better diffs

### ISSUE THREAD

**Issue by DanCardin** [ambv/black#685]
Primarily I'm talking about the first-wrapped-line handling (dunno if there's a better name)
```
# 1st line doesnt wrap, great!
WrapperObject(aaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbb, ccccccccccccccc, ddddddddddddd, e)

# 2nd line wraps, but tries to put all the args on 1 line :/
WrapperObject(
    aaaaaaaaaaaaaaaa, bbbbbbbbbbbbbbbbb, ccccccccccccccc, dddddddddddddddd, ee
)

# 3rd line exceeds some heuristic that tells it to finally wrap one, per line.
WrapperObject(
    aaaaaaaaaaaaaaaa,
    bbbbbbbbbbbbbbbbb,
    ccccccccccccccc,
    dddddddddddddddd,
    eeeeeeeeeeeee,
)
```

My thought would be:
- last one matches the decision made for imports
- last one has least diff/churn issues
- 2nd one doesn't include the trailing comma that you normall get
- once you exceed the first line length limit, its fair game to wrap one per line.

In practice I tend to see a lot of things like
```
result = foo(
    some_args_which_are, collectively_long, but_not_too_long, alskdjflasjdflajdfljaldjf
).other_thing(
    some_args_which_are, collectively_long, but_not_too_long, alskdjflasjdflajdfljaldjf
).other_thing_again(
    pg.query(Example)
    .join(OtherExample)
    .options(joinedload(OtherExample))
    .filter(Object.id == object.id)
)
```
This starts to get into territory similar to https://github.com/ambv/black/issues/67 re fluent interfaces.

In particular I really like what its doing to the inner chained calls in the last portion, but the rest I wish it would format like so:
```
result = foo(
    some_args_which_are,
    collectively_long,
    but_not_too_long,
    alskdjflasjdflajdfljaldjf,
).other_thing(
    some_args_which_are,
    collectively_long,
    but_not_too_long,
    alskdjflasjdflajdfljaldjf,
).other_thing_again(
    pg.query(Example)
    .join(OtherExample)
    .options(joinedload(OtherExample))
    .filter(Object.id == object.id)
)
```

And even that...I might be an outlier, but I think the below variant is preferable because its consistent with the style you get in the body of the bottom `other_thing_again` section, as well as being consistent (inside the parens) with the style you get from very long expressions which meet the heuristic of one-item-per-line

```
result = (
    foo(
        some_args_which_are,
        collectively_long,
        but_not_too_long,
        alskdjflasjdflajdfljaldjf,
    )
    .other_thing(
        some_args_which_are,
        collectively_long,
        but_not_too_long,
        alskdjflasjdflajdfljaldjf,
    )
    .other_thing_again(
        pg.query(Example)
        .join(OtherExample)
        .options(joinedload(OtherExample))
        .filter(Object.id == object.id)
    )
)
```

**Comment by DanCardin** [comment]
having suggested this, I realize it would likely change a lot of existing formatting at this point, and its certainly less obvious in my examples than https://github.com/ambv/black/issues/67 were

I just didn't notice issues quite like this and it regularly comes up as unfortunate formatting in the sort of code we appear to write

**Comment by zsol** [comment]
I get where you're coming from, but at this point it's unlikely we're going to make such a fundamental change to the code style.

**Comment by advance512** [comment]
@DanCardin I'm with you on this, 100%. Makes git diffs much easier, and also reading the code much easier (more whitespace, clear vertical separation between parameters/arguments).

Forking into gray? ;)
