### ISSUE TITLE
Long 'del' statement not split into multiple lines

### ISSUE THREAD

**Issue by jrh206** [ambv/black#693]
Operating system: Windows 10
Python version: 3.6.6
*Black* version: 18.9b0
Does also happen on master: yes

In an `__init__` file, I have the following:

```python
from .business_day_convention import BusinessDayConvention
from .date_generation_rule import DateGenerationRule
from .schedule import Schedule
from .schedule_context import ScheduleContext
from .period import Period
from .time_unit import TimeUnit
from .frequency import Frequency

del business_day_convention, date_generation_rule, schedule, schedule_context, period, time_unit, frequency
```

I expect the final `del` statement to be split on multiple lines (like imports) but it is not

Expected output:
```python
from .business_day_convention import BusinessDayConvention
from .date_generation_rule import DateGenerationRule
from .schedule import Schedule
from .schedule_context import ScheduleContext
from .period import Period
from .time_unit import TimeUnit
from .frequency import Frequency

del (
    business_day_convention,
    date_generation_rule,
    schedule,
    schedule_context,
    period,
    time_unit,
    frequency,
)
```

**Comment by JelleZijlstra** [comment]
Thanks for the report, we'll fix it.

**Comment by JelleZijlstra** [comment]
Relatedly, we also don't appear to split up `import a, b, c, d` if it is too long.

**Comment by JelleZijlstra** [comment]
... which makes sense because `import (a, b)` is a syntax error. The `del` change is tricky because we'd change the AST:
```
In [326]: def d(s): return ast.dump(ast.parse(s))

In [333]: d("del a, b")
Out[333]: "Module(body=[Delete(targets=[Name(id='a', ctx=Del()), Name(id='b', ctx=Del())])])"

In [334]: d("del (a, b)")
Out[334]: "Module(body=[Delete(targets=[Tuple(elts=[Name(id='a', ctx=Del()), Name(id='b', ctx=Del())], ctx=Del())])])"
```
The two statements do produce the same bytecode, but the AST change makes it so that inserting parens in del statements will break our AST safety check.

**Comment by joaoe** [comment]
> Relatedly, we also don't appear to split up `import a, b, c, d` if it is too long.

You can split into multiple import statements
```
import a
import b
import c
...
```

**Comment by joaoe** [comment]
If you find a long `del` or other sort of expression you can't wrap, might I suggest black issues a warning ?
