### ISSUE TITLE
Triple-quote multiline strings could be more compact.

### ISSUE THREAD

**Issue by FlipperPA** [ambv/black#697]
Operating system: CentOS 7.6
Python version: 3.6
*Black* version: 18.9b0
Does also happen on master: Yes.

Here's a basic example; Black adds two un-necessary carriage returns to this valid PEP-8 syntax, which is more compact. You can see from the example where this sort of string formatting is frequent. :)

Input:

```python
from example import example_execute

example = example_execute("""
    SELECT something FROM something
""")
```

Output:

```python
from example import example_execute


example = example_execute(
    """
    SELECT something FROM something
"""
)
```

Apologies if this is a dupe, but I wasn't able to find an existing issue among the existing multi-line string issues. Thanks for your efforts - I love the package!

**Comment by sitsofe** [comment]
Sounds similar to #256 ...

**Comment by zsol** [comment]
Yep, let's track this in #256
