### ISSUE TITLE
Unneeded spaces added after open parens?

### ISSUE THREAD

**Issue by maxim-lian** [ambv/black#7]
Weirdness around the space after the parentheses. Also weird because I'd have thought the existing line was fine, and fit into the 79 characters I passed as an option

```python
# existing
-    new_coord_names = (coord_names | set(vars_to_create)) - set(vars_to_remove)
-

# black
+    new_coord_names = ( coord_names | set(vars_to_create)) - set(
+        vars_to_remove
+    )
```

**Comment by ambv** [comment]
Thanks for your report! I can reproduce this and will fix shortly.
