### ISSUE TITLE
create Sphinx docs and ReadTheDocs hosting

### ISSUE THREAD

**Issue by carljm** [ambv/black#70]
We should have Sphinx documentation in the repo, and probably host them on RTD.

**Comment by carljm** [comment]
@willingc - @ambv mentioned you are working on this? Thank you!!

**Comment by carljm** [comment]
Some writing on why Black opposes backslashes that would be good to include in some form: https://github.com/ambv/black/issues/64#issuecomment-375429106

**Comment by willingc** [comment]
Thanks @carljm. I'll likely push a skeleton PR in the hour. I'll include support for both rst and markdown sources so folks can pick their favorites.

**Comment by ambv** [comment]
Alright: http://black.readthedocs.io/en/latest/

Carol, thanks a lot for your help here, this is a great start! ✨ 🍰 ✨

**Comment by willingc** [comment]
Sweet. Thanks @ambv. Now for the fun part - iterating. :sunny:
