### ISSUE TITLE
remove py36

### ISSUE THREAD

**Issue by jgirardet** [ambv/black#703]
Hi,

With --target-version pushed, what's the point of keeping py36 for black ?
Considering it's been removed in blackd, it should be the same for black.

**Comment by JelleZijlstra** [comment]
I didn't want to drop backward compatibility with existing black configurations.

Also, I don't think I removed support for anything from blackd. What feature do you think was removed?

**Comment by jgirardet** [comment]
oh sorry I read to fast the implementation.
But since since black hates configuration, I think this should be at least deprecate or deprecation warning in a next release.
After all it's still in beta, it's still time for deprecating some useless options.

**Comment by zsol** [comment]
FWIW I also think we should drop `--py36` while we're in pre-release. There should be one way to do things, and we shouldn't be afraid to deprecate features/APIs in this phase.

**Comment by JelleZijlstra** [comment]
Sounds good. Should we just drop it in the upcoming release or leave it in for one more for compatibility?

**Comment by zsol** [comment]
I don't have a strong opinion on it, but if I were to do it, I'd remove it in the next release :)

**Comment by zsol** [comment]
I've developed a strong opinion :) let's remove it
