### ISSUE TITLE
Merging of intentionally parenthesized strings

### ISSUE THREAD

**Issue by pe224** [ambv/black#706]
Python version: 3.6.7
*Black* version: 18.9b0
Does also happen on master: yes

In
```python
msg = (
    'my\n'
    'intentional\n'
    'split'
)
```

Out (raw)
```python
msg = "my\n" "intentional\n" "split"
```

Out (after manual reformatting)
```python
msg = "my\nintentional\nsplit"
```

I think both output versions decrease readability as the initial string is intentionally split at newlines - even when taking into account that modern editors visually distinguish the `\n` control character from the rest of the string.

This is specific to the situation when the merged string would not exceed max characters and would fit on a single line.

Is it an option to exclude string merging in this situation?

**Comment by zsol** [comment]
If you want to keep your manual formatting, you can surround this block with `# fmt: off` and `# fmt: on`. Black won't special case for this for now.

**Comment by pe224** [comment]
Thanks.
Do you have a suggestion how to keep the linebreaks of multiline strings (such as above) visible in the presence of black without littering the code with `# fmt`?

**Comment by zsol** [comment]
You can also use proper multiline strings `"""`, then there's no need for the parenthesis.

**Comment by pe224** [comment]
But then you need to wrap it in `textwrap.dedent` and possibly even `.strip()` to get rid of spurious newlines in the beginning and end, right?
IMHO the elegant solution (using parentheses) is maybe a bit too easily dismissed for such cases where strings end in `\n`
