### ISSUE TITLE
Excessive number of records emitted by root logger

### ISSUE THREAD

**Issue by apljungquist** [ambv/black#715]
There are two instances in `driver.py` of a logger being instantiated to the root logger unless another logger is specifically provided like

```python
        if logger is None:
            logger = logging.getLogger()
```

Another logger is never explicitly provided and as such thousands of records are submitted to the root logger. This becomes a problem when using black from another python script.

Perhaps a more elegant solution would be to retrieve a named logger like 

```python
# driver.py
        if logger is None:
            logger = logging.getLogger(__name__)
```

that can then be configured like

```python
# main.py
logging.getLogger('blib2to3.pgen2.driver').setLevel(logging.WARNING)
```

Would a pull request addressing this be considered?

Operating system: MacOS 10.14.3
Python version: 3.7.2
*Black* version: 18.9b0
Does also happen on master: Probably

**Comment by JelleZijlstra** [comment]
That seems reasonable; feel free to submit a PR.

**Comment by ricoms** [comment]
did this PR happened and merged? I'm having issues with this nowadays

**Comment by apljungquist** [comment]
As of this patch the driver will still submit log records but it will do so to the `blib2to3.pgen2.driver` logger instead of the root logger which seems to be what you observe. I don't think it would be right to force libraries to stop logging altogether so what the app can do is to configure that logger. In my post above I show how to remove everything that is not a warning or more severe:

```python
logging.getLogger('blib2to3.pgen2.driver').setLevel(logging.WARNING)
```

**Comment by ricoms** [comment]
is that like this:

```
import logging

logging.getLogger('blib2to3.pgen2.driver').setLevel(logging.WARNING)
```

or if I already have a logger, I should just 

```
from myown_logger import logger

logger.getLogger('blib2to3.pgen2.driver').setLevel(logging.WARNING)
```

?

**Comment by apljungquist** [comment]
The former.

I recommend everyone read the python logging tutorial:
https://docs.python.org/3/howto/logging.html#advanced-logging-tutorial

**Comment by ricoms** [comment]
thanks, but that solution is not working for me.

**Comment by apljungquist** [comment]
Feel free to post a link to or mention me in a discussion/issue on the
other project if you want a second pair of eyes on the code.
