### ISSUE TITLE
SyntaxError with re-raise statement in Python 2

### ISSUE THREAD

**Issue by joaoe** [ambv/black#716]
**Operating system:** Windows 10, both native build and Cygwin
**Python version:** python 3.6
**Black version:** master, 18.9b0

Apparently Black does not support raise statements with tuples in python2, e.g.
```
import sys

def fn1():
	raise ValueError("asd")

def fn2():
	try:
		fn1()
	except ValueError as e:
		#raise TypeError(*e.args).with_traceback(e.__traceback__)
		raise TypeError, TypeError(*e.args), sys.exc_info()[2]

fn2()
```
The commented line is the equivalent syntax for python 3

The result I get:
```
$ black b.py
error: cannot format b.py: cannot use --safe with this file; failed to parse source file with Python 3.6's builtin AST. Re-run with --fast or stop using deprecated Python 2 syntax. AST error message: invalid syntax (<unknown>, line 11)
$ black -t cpy27 b.py
Cannot use both --target-version and --py36
```
Side note: I don't know if `--target-version` is supposed to be a syntax hint.

**Comment by zsol** [comment]
Have you tried running black with `--fast`, like the error message says? :)

**Comment by JelleZijlstra** [comment]
The second error looks concerning. Do you have a pyproject.toml that sets `--py36`?

**Comment by joaoe** [comment]
> Have you tried running black with `--fast`, like the error message says? :)

Yeah, but I'm not entirely sure why that should change the supported syntax :) Perhaps black should fallback automatically to an older syntax if the latest and bestest does not parse ? 

> The second error looks concerning. Do you have a pyproject.toml that sets `--py36`?

No. I'm running black from black's own git tree.

**Comment by zsol** [comment]
> Yeah, but I'm not entirely sure why that should change the supported syntax :) Perhaps black should fallback automatically to an older syntax if the latest and bestest does not parse ?

Black verifies that the reformatted code is AST-equivalent to the original one. It does this by parsing both using the builtin `ast` module, but since black itself is running with python 3.6+, that module doesn't support the older (and newer) syntax. Specifying `--fast` disables this sanity check.

> No. I'm running black from black's own git tree.

Black's own `pyproject.toml` specifices `py36 = true`, which is why you're seeing this error message.
