### ISSUE TITLE
Trailing commas in deeply nested collections

### ISSUE THREAD

**Issue by acetylen** [ambv/black#717]
Operating system: Kubuntu 18.04
Python version: 3.6.7
*Black* version: 18.9b0
Does also happen on master: yes

When making dicts that mimic JSON, you sometimes end up with deeply nested structures. If such a dict happens to have other nested dict members at the end, the trailing comma appended to the parent structure by Black looks really out-of-place.

```python
json_dict = {
    "a": {
        "b": 1234,
        "c": {
            "d": {
                "e": 5678
            }
        },  # <-- This trailing comma looks weird
    }
}
```

It's obvious why this happens, and rules-wise it makes sense, but visually it looks inconsistent.

This may be the inverse of #132; should there be cases where a trailing comma is *not* added?

**Comment by JelleZijlstra** [comment]
This is obviously a matter of personal preference, but Black tries to format things in such a way that later diffs are minimized (e.g., when somebody adds a new entry to the dict). See https://github.com/ambv/black#how-black-wraps-lines. We're unlikely to change the formatting here.
