### ISSUE TITLE
Don't reformat JSON files.

### ISSUE THREAD

**Issue by dimaqq** [ambv/black#719]
I think `black`'s detection of what is or is not a Python file could be better.

Most JSON documents parse as Python source.
(technically unless they contain `null`, but even these are accepted, since black doesn't evaluate global references).

A large enough JSON document is bound to be reformatted with trailing commas by `black`, which are illegal in JSON.

I tend to run `black (git ls-files -m)` during development / before commit, and that sometimes catches a few non-Python files. Most of them don't parse as Python, so `black` complains and leaves them alone. JSON documents get blackened. For example `Pipfile.lock`.

I would propose that `black` left alone "degenerate" Python-like files, specifically files comprising a single expression.

Operating system: macos
Python version: 3.7.2, 3.8.a1
*Black* version: black==18.9b0, master
Does also happen on master: yes

**Comment by dimaqq** [comment]
On the second thought, I can think of at least 1 kind of sole expression that should still be blackened -- a sole docstring.

A sole plain string is harder - it's valid JSON thus potentially should not be changed, but it could be an incomplete Python file, in which case it should...

**Comment by zsol** [comment]
I think black is the wrong layer to solve this problem. Black will always assume the input it's passed in is to-be-formatted python source code. I suggest you come up with something better than `black (git ls-files -m)` to be part of your workflow. Maybe filter the output of `git ls-files`.

**Comment by wchargin** [comment]
> Maybe filter the output of `git ls-files`.

No external filtering required: `git ls-files ':!*.json'`.

(See `man 7 gitglossary` and search for “`exclude`”.)
