### ISSUE TITLE
Black cannot format a markdown file with a html <img> tag

### ISSUE THREAD

**Issue by nbeuchat** [ambv/black#721]
I am trying to format a README.md file. The first line of the README contains an html `img` tag so that we can have our company logo on the top right of every README. 

When running `black README.md`, I receive the following error:

```
error: cannot format README.md: Cannot parse: 1:0: <img align="right" height="50" src="https://s3.amazonaws.com/path/to/logo.png">
All done! 💥 💔 💥
1 file failed to reformat.
```

**Operating system:**
Python version: 3.6.8
*Black* version: 18.9b0
Does also happen on master: Yes (tested by cloning and installing master locally)

By the way, the online formatter gave me a `type object 'FileMode' has no attribute 'from_configuration'` (for any code, not just my example)

Thanks for your help!

**Comment by zsol** [comment]
Black doesn't support markdown files, sorry.
