### ISSUE TITLE
Push 19.2b0 to PyPi

### ISSUE THREAD

**Issue by gpakosz** [ambv/black#735]
I'm sorry I'm following the issue pattern. Title says it all, could 19.2b0 be pushed to PyPi?

**Comment by JelleZijlstra** [comment]
We can't because it's March by now. :) I know I've said this before, but we're getting close to pushing out a new release now.

**Comment by ambv** [comment]
Done, 19.3b0 is out.

**Comment by gpakosz** [comment]
Thank you
