### ISSUE TITLE
type object 'FileMode' has no attribute 'from_configuration'

### ISSUE THREAD

**Issue by ReddyKilowatt** [ambv/black#744]
**Black https://github.com/ambv/black/commit/ea55ff**

[Playground link](https://black.now.sh/?version=master&state=_Td6WFoAAATm1rRGAgAhARYAAAB0L-Wj4ACeAG1dAD2IimZxl1N_Wk6rkcNtQDQ3eCFPiV4DOwtIw5J3-oUni-ZztdwUqYCxq_oeQ4S3NTaULJ5Ld3rqD1hGcbal48tyam_VMgxkBmO5pcgQLsv_uaWFMtYhPnckW7FealperA7_QOXx-UVesKA0LQAAAAAAQOSOkGHau-4AAYkBnwEAALgjayOxxGf7AgAAAAAEWVo=)

## Options

`--line-length=60`

## Input

```python

def command(CamelCaseArg, another_arg, Bad_Camelcase):
    print(CamelCaseArg)
```

## Output

```python
type object 'FileMode' has no attribute 'from_configuration'
```

## Expected
Who knows? No info is given how to runthe plaground. Only an error message is displayed,w
which doesn't explain anything. -> type object 'FileMode' has no attribute 'from_configuration'

**Comment by JelleZijlstra** [comment]
This is probably a bug in the playground. `from_configuration` definitely does exist in this repo. I don't see anything obviously wrong in the code in https://github.com/jpadilla/black-playground; @jpadilla any ideas?

**Comment by illfated** [comment]
From what I can find, you just need to use the link https://black.now.sh/?version=master .
When using only https://black.now.sh/ (https://black.now.sh/?version=stable),
it appears to be normal and not as easy to provoke the error message.

**Comment by jpadilla** [comment]
Working on fixing this soon.

**Comment by adamdavis40208** [comment]
Just an FYI, both master and stable are giving this error now

**Comment by adamdavis40208** [comment]
Seems better now! Thanks to whoever rebooted the website /s

**Comment by jpadilla** [comment]
Confirming the issue is officially fixed, thank you all! 🎉

**Comment by JelleZijlstra** [comment]
Thanks!
