### ISSUE TITLE
Exit code should be non-zero when no paths are given

### ISSUE THREAD

**Issue by whatisaphone** [ambv/black#746]
`black` does not assume the current directory when no paths are given on the command line. This is in contrast to other tools (flake8, unittest) that do make that assumption. Because Python tools don't agree on this detail, someone may mistakenly put `black --check` in CI and be done with it. Since that exits with 0, CI will happily chug along with no indication that black isn't working as expected.

```sh
$ black --check
No paths given. Nothing to do 😴
$ echo $?
0
```

`mypy` is another tool that, like black, requires a path to be specified. If you make the same mistake with mypy, it will fail fast:

```sh
$ mypy
usage: mypy [-h] [-v] [-V] [more options; see below]
            [-m MODULE] [-p PACKAGE] [-c PROGRAM_TEXT] [files ...]
mypy: error: Missing target module, package, files, or command.
$ echo $?
2
```

I think black should follow mypy's example here.

**Comment by ambv** [comment]
The reason Black behaves like this is command-line wildcards. With Black you can do:
`black *.py` and it will not fail if there's no Python file in the current directory. The reason this is important is that the files can be passed by `xargs` or other Unixy tools. If they end up passing nothing, you don't want your pipeline to fail.

Read the "Note on non-empty variadic arguments" in the Click documentation: https://click.palletsprojects.com/en/7.x/arguments/#variadic-arguments

**Comment by whatisaphone** [comment]
@ambv I don't think that works quite so smoothly in practice. The shell won't expand a wildcard if it matches nothing. Here's what actually happens when you run `black *.py`:

```sh
$ mkdir empty
$ cd empty
$ black *.py
Usage: black [OPTIONS] [SRC]...
Try "black -h" for help.

Error: Invalid value for "[SRC]...": Path "*.py" does not exist.
```

The unixy way is generally to fail fast if an expected argument is missing:

```sh
$ find -name '*.py' | xargs chmod 644
chmod: missing operand after ‘644’
Try 'chmod --help' for more information.
$ echo $?
123
```

For the case of `xargs`, it has a flag `-r`/`--no-run-if-empty` that lets the pipeline succeed if the caller explicitly decides that doing nothing is a valid outcome:

```sh
$ find -name '*.py' | xargs --no-run-if-empty chmod 644
$ echo $?
0
```

All that said, I guess it's ultimately a philosophical issue, so if you're not convinced, I'll leave it at that.
