### ISSUE TITLE
black inserts unnecessary whitespace around print() with target_version = py27

### ISSUE THREAD

**Issue by rouge8** [ambv/black#752]
black is adding whitespace between `print` and `(` with `--target-version py27`.

**Test file:**

```python
from __future__ import print_function

print("hello world")
```

**Result:**

```console
$ black t.py --target-version py27 --diff
--- t.py	2019-03-14 22:09:34.902887 +0000
+++ t.py	2019-03-14 22:10:21.022372 +0000
@@ -1,4 +1,4 @@
 from __future__ import print_function

-print("hello world")
+print ("hello world")

reformatted t.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

Operating system: OS X 
Python version: 3.7.2
*Black* version: 19.3b0
Does also happen on master: yes

**Comment by ambv** [comment]
That's a bug, it's trying the non-print function grammar first. @JelleZijlstra :-)

**Comment by vbukhonov** [comment]
@ambv @JelleZijlstra 
Hello. Sorry, but I am still facing this bug under python 3.

**Comment by chebee7i** [comment]
Can we get a release out for this? Trying to use the current release on 2.x is producing ugly code with these extra spaces.

**Comment by tommyjcarpenter** [comment]
Has this been switched to the stable branch? I am using the latest stable version of black and I still hit this issue.

**Comment by vinyasmusic** [comment]
Facing this issue with Python 3.6 
Black formats this piece of code `print("cacheops.{} for {}".format(event, sender))` to `print ("cacheops.{} for {}".format(event, sender))` 
And then the flake8 checker flags this under E211

**Comment by tommyjcarpenter** [comment]
I vote to reopen this issue. I do not think this is closed or resolved.

**Comment by cg-cnu** [comment]
Ran into this on V 19.10b0. Looks like the spaces after the `print ()` are added if there is a print statement (`print "test"`) in the code. Totally my mistake but thought it might save others some hair.
