### ISSUE TITLE
Run black within another script without exiting

### ISSUE THREAD

**Issue by rileyjohngibbs** [ambv/black#756]
Operating system: Linux
Python version: 3.6
*Black* version: 18.9b0
Does also happen on master: Yes

I'd like to write some Python code to a file and then use black to reformat that file. Calling `main(["file.py"])` will reformat the file, but will also then immediately exit out of the parent script. Is there a way to avoid this, or am I just using it totally inappropriately?

**Comment by zsol** [comment]
Try calling a lower-level function, like `format_string`

**Comment by JelleZijlstra** [comment]
Or call Black in a subprocess.
