### ISSUE TITLE
black inserts unnecessary whitespace around exec() with target_version = py27

### ISSUE THREAD

**Issue by rouge8** [ambv/black#757]
black is adding whitespace between `exec` and `(` with `--target-version py27`. This also happens with `--target-version py27 --target-version py37`

**Test file:**

```python
exec("1 + 1")
```

**Result:**

```console
$ black --target-version py27 t.py --diff
--- t.py	2019-03-15 07:21:56.222569 +0000
+++ t.py	2019-03-15 07:22:05.901294 +0000
@@ -1,2 +1,2 @@
-exec("1 + 1")
+exec ("1 + 1")
```

Operating system: OS X 
Python version: 3.7.2
*Black* version: 19.3b0
Does also happen on master: yes, as of d6db1c12a8e14833fe22da377cddc2bd1f43dc14

**Comment by JelleZijlstra** [comment]
I'll fix this for `-t py27 -t py37`, but this is not clearly a bug for `-t py27`, because in that case `exec` is a statement, not a function. We may still want to special-case it so Black produces more 2/3-compatible-looking code by default though.
