### ISSUE TITLE
Black does not ignore jupyter magic commands within # fmt: off/on blocks

### ISSUE THREAD

**Issue by jzazo** [ambv/black#774]
Operating system: Ubuntu 18.04
Python version: 3.6.7
*Black* version: 18.9b0
Does also happen on master: Yes

The following snippet gives constant formating error:
```
# fmt: off
%load_ext autoreload
%autoreload 2
# fmt: on
```

**Comment by zsol** [comment]
Black expects its input to be valid python source code. That snippet is not :)

**Comment by boyoungzheng** [comment]
How about adding an option to let `black` know if it needs to skip magic commands? I will appreciate it.
The reason is that Hydrogen can now use Jupyter kernels. Magic commands frequently show in my codes.

**Comment by jzazo** [comment]
I have the same use case. There is an option in Hydrogen to load magic commands whenever you load a jupyter kernel, and [here](https://github.com/nteract/hydrogen/issues/1564) is an open issue about the format for multiple lines. Sadly, for some reason it does not work properly either.

**Comment by JelleZijlstra** [comment]
Supporting this would be difficult because Black uses a Python parser to parse its input, and as @zsol pointed out what you have isn't valid Python code. We could enhance the parser to support this sort of thing, but it's not exactly easy.

**Comment by boyoungzheng** [comment]
How about this approach:
define a function `comment_magic` based on regex
define a function `uncomment_magic` based on regex
define a flag `f_user_keep_magic` to show if the user wants to keep magic commands

When `black` is invoked
    run `comment_magic` (to get rid of magic commands)
    run `black` as usual (magic commands are already commented)
    if f_user_keep_magic:
        run `uncomment_magic` (uncomment magic commands per user's need)

**Comment by zsol** [comment]
I'd suggest wrapping black itself in a Jupyter-aware parser that
understands magic commands, knows how to format them and hands everything
else off to black

**Comment by geier1993** [comment]
If someone wants to follow @boyoungzheng approach:

I have a repo with some databrick notesboook (usual python files with magic commands)
I run this on all python files:
```
find . -type f -name '*.py' -exec sh -c "echo \"{}\" && cat \"{}\" | sed 's/^\(\W*\)%/\1# BLACK_UNCOMMENT_PERCENTAGE /' | black --skip-string-normalization - | sed 's/^\(\W*\)# BLACK_UNCOMMENT_PERCENTAGE /\1%/' > \"{}_formatted\" && mv \"{}_formatted\" \"{}\""  \;
```

**Comment by MarcoGorelli** [comment]
@geier1993 trouble is, just because a line starts with `%` doesn't mean it's a magic. 

e.g.:
```python
('%s'
% 'foo'
)
```

Also, there are magics that don't start with `%`, such as
```python
flake_version = !flake8 --version
```

I'm working on a solution to this in https://github.com/psf/black/pull/2357 (on the back of the magic handling in [nbQA](https://github.com/nbQA-dev/nbQA))- it sounds like you have a few repositories with notebooks with magics in them, so if you could try checking that branch out and running it against them (and report any bugs) then that'd be really helpful

**Comment by grisaitis** [comment]
one approach is to replace magics with valid python code. instead of 

```
# cell 1
%timeit -n1 pass

# cell 2
%%timeit -n1
pass
``` 

you can do 

```
from IPython.core.getipython import get_ipython

# cell 1
get_ipython().run_line_magic("timeit", "-n1 pass")

# cell 2
get_ipython().run_cell_magic("timeit", "-n1", "pass")
```

or, if your linter yells at you because `get_ipython` can return `None`,

```
from IPython.core.interactiveshell import InteractiveShell
if InteractiveShell.initialized():
    ipython = InteractiveShell.instance()
    ipython.run_line_magic("timeit", "-n1 pass")
    ipython.run_cell_magic("timeit", "-n1", "pass")
```

i find this is useful when developing notebooks in plain .py files, eg with visual studio code.

**Comment by ankostis** [comment]
Does the  @boyoungzheng approach hold any water?
