### ISSUE TITLE
lint Ecmascript?

### ISSUE THREAD

**Issue by gotexis** [ambv/black#778]
This is probably farfetched, but is there any Python Ecmascript linters out there?

**Comment by JelleZijlstra** [comment]
Do you mean an ECMAScript linter written in Python?

**Comment by illfated** [comment]
A regular Google search should return a lot of suggestions: https://www.google.com/search?q=ECMAScript+linter

**Comment by gotexis** [comment]
@illfated yes, but since its pretty greedy i just called subprocess on eslint-prettier
Haha

**Comment by JelleZijlstra** [comment]
Doesn't sound like there's anything for Black to do here.
