### ISSUE TITLE
Do not show messages when file was read from standard input

### ISSUE THREAD

**Issue by proofit404** [ambv/black#78]
When running `black -` messages `- already well formatted, good job.` and `reformatted -` should not be shown.

**Comment by ambv** [comment]
You can simply use 2>/dev/null in this case, no?

**Comment by proofit404** [comment]
Well, I have two problems here. I use this in the Emacs package to format current file "in memory".

If the buffer contains correct python source, I want to substitute current content with the black output. In this case, redirect to `/dev/null` helps.

If the buffer contains code with a syntax error, I want to show error output in the separate editor window. In this case, redirect to the `/dev/null` will hide the actual error.

But if I keep stderr as is, in the normal case source code buffer will contain status messages for successful or skipped formatting.

**Comment by ambv** [comment]
How about this: redirect stderr to /tmp/black_last.log and only show it if the exit code != 0?

Sorry I'm pushing back on changing this. I'm just sure people will just want increased controls over output if I ever agree to this. I'd rather see this handled the UNIX way.

**Comment by proofit404** [comment]
Seems reasonable. I don't want to open Pandora's box just to be useful in rare cases.

Thanks again!

**Comment by kalekseev** [comment]
@ambv have the same problem with vim and neoformat, can't we add some option like `--quiet` as in isort or `--silent` to prevent outputting any messages from black?

**Comment by proofit404** [comment]
Hi @kalekseev 

I figured out how to split stdout and stderr into different emacs buffers. It's implemented via a pipe from stderr and actually, there are two processes. Probably Vim has the same possibility.

I agree with @ambv not to add this flag because it increases maintenance support and open questions for a lot more configuration. If it is possible to solve this without changing `black` itself we should try to do so.

As far as I know vim support python as a scripting language. Probably this can help, but it probably depends on vim compilation details. Like against what python version it was compiled?

Regards, Artem.

**Comment by kalekseev** [comment]
Hi @proofit404, yes it's not that hard to read the stdout only, my question is more about convenience. Almost all formatters that I worked with have some sort of that option and I think it could improve user experience with black, because you can run `black --help` and see solution for your problem.
Otherwise user should know about stdout/stderr check how it can be integrate with his editor, etc..

BTW for neoformat I used

```
let g:neoformat_python_black = {
            \ 'exe': 'black',
            \ 'stdin': 1,
            \ 'args': ['--line-length', '110', '-', '2>/dev/null'],
            \ }
``` 

Thanks for the project @ambv!

**Comment by proofit404** [comment]
Isn't stdout and stderr knowledge is obvious for users of the command line?

**Comment by kalekseev** [comment]
@proofit404  If you ask me then I don't think so, also output from black looks similar (no colors for example) so to start thinking about piping user should find that the messages and output goes to different pipes.

BTW I created pr with black support for neoformat https://github.com/sbdchd/neoformat/pull/150 
also out of curiosity checked how much formatters in neoformat rely on stderr to /dev/null redirect

```
$ rg '/dev/null'

autoload/neoformat/formatters/haskell.vim
16:        \ 'args': ['2>/dev/null'],

autoload/neoformat/formatters/ruby.vim
23:        \ 'args': ['--auto-correct', '--stdin', '%:p', '2>/dev/null', '|', 'sed "1,/^====================$/d"'],
```

**Comment by ambv** [comment]
Don't just put 2 to /dev/null. If Black fails, it will display potentially helpful errors there. Is it possible to redirect output and only show it if return code is not 0?

It seems to me like neoformat and other similar frameworks should do that by default. @kalekseev, how many plugins in neoformat today use a variant of --quiet?

**Comment by carljm** [comment]
> Don't just put 2 to /dev/null. If Black fails, it will display potentially helpful errors there. Is it possible to redirect output and only show it if return code is not 0?

This is why Unix tools conventionally have a quiet mode that avoids all non-error output (in fact the classic Unix way would be to have that mode be the default, but I'm not fussed about that); because at this point it's no longer a matter of a simple redirection, it requires logic, and not every integration framework is going to make that easy.

I think black should have a `--quiet` option that avoids all output except in case of failure.

**Comment by kalekseev** [comment]
@ambv 
> Is it possible to redirect output and only show it if return code is not 0?

as far as I know it's not possible in neoformat right now

> how many plugins in neoformat today use a variant of --quiet?

```
$ rg "silent|\-q(uiet)?" autoload/neoformat/
autoload/neoformat/formatters/xml.vim
8:            \ 'args': ['-quiet',

autoload/neoformat/formatters/objc.vim
8:        \ 'args': ['-q', '-l OC+'],

autoload/neoformat/formatters/perl.vim
8:            \ 'args': ['-q'],

autoload/neoformat/formatters/java.vim
8:            \ 'args': ['-q', '-l JAVA'],

autoload/neoformat/formatters/cpp.vim
8:           \ 'args': ['-q', '-l CPP'],

autoload/neoformat/formatters/markdown.vim
16:            \ 'args': ['--no-color', '--silent'],

autoload/neoformat/formatters/php.vim
14:           \ 'args': ['fix', '-q'],

autoload/neoformat/formatters/python.vim
24:                \ 'args': ['-', '--quiet'],

autoload/neoformat/formatters/c.vim
8:           \ 'args': ['-q', '-l C'],

autoload/neoformat/formatters/d.vim
15:        \ 'args': ['-q', '-l D'],

autoload/neoformat/formatters/cs.vim
8:        \ 'args': ['-q', '-l CS'],

autoload/neoformat/formatters/vala.vim
4:        \ 'args': ['-q', '-l VALA'],

autoload/neoformat/formatters/pawn.vim
8:        \ 'args': ['-q', '-l PAWN'],

autoload/neoformat/formatters/xhtml.vim
8:            \ 'args': ['-quiet',

autoload/neoformat/formatters/html.vim
8:        \ 'args': ['-quiet',
```

Also if we consider windows as supported platform then things become more complicated without such option.

**Comment by ambv** [comment]
I haven't considered Windows before (Black standardizes newlines to \n) but this might be a reason to support --quiet after all. Sigh. Let me see how this behaves on Windows.
