### ISSUE TITLE
slices for functions or method are flake8 uncompatible

### ISSUE THREAD

**Issue by tbicr** [ambv/black#785]
having:
```
A = 1
B = 2
C = '1/2/3'
x = C[int(A):int(B)]
y = C[C.index('/'):C.rindex('/')]

data = [1, 2, 3]
i = 0
df = data[i:i + 1]
```

run:
`black --safe -S -l 100 file.py`

got:
```
A = 1
B = 2
C = '1/2/3'
x = C[int(A) : int(B)]
y = C[C.index('/') : C.rindex('/')]

data = [1, 2, 3]
i = 0
df = data[i : i + 1]
```

expected:
NO CHANGES

Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: 16.04.6 LTS
Python version: 3.7.2
*Black* version: 19.3b0
Does also happen on master: yes

To answer the last question, you have two options:
1. Use the online formatter at https://black.now.sh/?version=master, which will use the latest master branch.
2. Or run black on your machine:
    * create a new virtualenv (make sure it's the same Python version);
    * clone this repository;
    * run `pip install -e .`;
    * make sure it's sane by running `python setup.py test`; and
    * run `black` like you did last time.

**Comment by JelleZijlstra** [comment]
flake8 is incompatible with PEP 8 here. See https://github.com/ambv/black#slices.
