### ISSUE TITLE
strip comment spaces before #

### ISSUE THREAD

**Issue by tbicr** [ambv/black#786]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Ubuntu 16.04.6 LTS
Python version: 3.7.2
*Black* version: 19.3b0
Does also happen on master: yes

Blask can add spaces for comment after `#`, but cannot strip them if there are too many spaces.

having:
```
a = 0  #  too many spaces after #
a = 0  #no spaces after #
```

run:
`black --safe -S -l 100 file.py`

got:
```
a = 0  #  too many spaces after #
a = 0  # no spaces after #
```

expected:
```
a = 0  # too many spaces after #
a = 0  # no spaces after #
```

**Comment by JelleZijlstra** [comment]
If we do this, I'm sure we'll get people complaining about Black breaking commented-out code with indentation, something like this:
```
# def _commented_out_function(x):
#     return x[:-1]
```
So I'm not sure it's worth doing.

**Comment by tbicr** [comment]
good point
