### ISSUE TITLE
no additional space for comment stars with `#'`

### ISSUE THREAD

**Issue by tbicr** [ambv/black#787]
Howdy! Sorry you're having trouble. To expedite your experience,
provide some basics for me:

Operating system: Ubuntu 16.04.6 LTS
Python version: 3.7.2
*Black* version: 19.3b0
Does also happen on master: yes

No additional space formatting for comment that starts with single quote `#'`

haven:
```
#"
#'
```

run:
`black --safe -S -l 100 file.py`

got:
```
# "
#'
```

expected:
```
# "
# '
```

**Comment by wbolster** [comment]
this is by design because of #532
