### ISSUE TITLE
how to remove the trailing comma?

### ISSUE THREAD

**Issue by wangg12** [ambv/black#797]
Is there an option to not add the trailing commas?

**Comment by JelleZijlstra** [comment]
No, Black does not generally support configuration for the way it formats things.

(If you're asking about this because Black will under some circumstances produce incorrect code for Python 3.5, that bug is fixed on master.)

**Comment by dtantsur** [comment]
> that bug is fixed on master

Could this fix please be released? It's a real blocker for now.

**Comment by muppetjones** [comment]
It's a huge blocker. I don't see why this feature doesn't honor the `py36 = false` configuration.

**Comment by zsol** [comment]
@muppetjones as @JelleZijlstra said above, that was a bug that's fixed in master, to be included in the next release
