### ISSUE TITLE
Python 3.5- compatibility issue

### ISSUE THREAD

**Issue by kennethreitz** [ambv/black#8]
```python
    …
    **kwargs,
)
```

**Comment by brianbruggeman** [comment]
I don't think this is an issue.  The docs clearly state python3.6+ compatibility.

**Comment by kennethreitz** [comment]
No, the tool is to be run on Python 3.6, but is to produce code compatible with even Python 2.

**Comment by ambv** [comment]
Kenneth's right. The README states you should be able to reformat even well-behaved Python 2.7 code. This is simply an omission on my part because I don't run Python 2.7 on my own projects anymore.

But, the **kwargs trailing comma is such a small thing to fix that will unlock compatibility with 2.7-3.5 that I'm going to do it for sure.

**Comment by njsmith** [comment]
Watch out that this also affects

```python
def foo(*args,):  # error on 3.5 and earlier
    ...

def foo(a, *, b,): # error on 3.5 and earlier
    ...
```

(For reference it's [bpo-9232](https://bugs.python.org/issue9232).)

**Comment by ambv** [comment]
Yes, I'm familiar with the additional forms. Essentially, whenever the argument list includes a star, it's no longer safe to use a trailing comma unless such trailing comma or an f-string was already present in the file (which signifies the code is already 3.6+).

**Comment by kennethreitz** [comment]
This means if you already ran an early version of Black on the code, it won’t fix it :(

Not a huge deal, but something to consider.

**Comment by ambv** [comment]
Yes, that's the flip side. An easy way to spot those for you would be to run:

$ python3.5 -m compileall .

in your directory and see where you have failures. Hopefully there's not going to be too many. Let me know, if so I'll add a temporary option to never add trailing commas so you can fix your early adopter misformattings :-)

**Comment by ambv** [comment]
This is now fixed as described above. @kennethreitz, let me know if you need help with unbreaking the 3.6-only formattings in your code. If those are pushed to GitHub, I will happily make a pull request that undoes the damage.
