### ISSUE TITLE
Cannot format if at least one space on empty line in file

### ISSUE THREAD

**Issue by movalex** [ambv/black#80]
Operating system: MacOS 10.12.6
Python version: 3.6.4
Black version: 18.3a4
Does also happen on master: yes

```
import sys

 
def printunc():
    pass
```

This small file with tiny whitespace on 3rd line will not parse with error `error: cannot format test.py: Cannot parse: 3:0: `
Is it normal behavior?

**Comment by ambv** [comment]
No, not normal behavior. This is a bug in lib2to3. Thanks for your report, will fix tonight!
