### ISSUE TITLE
Grid formatting

### ISSUE THREAD

**Issue by arita37** [ambv/black#802]
Goal of formatting is to make faster code read for humans,
and detect bugs...

What of you think of this format ?

![image](https://user-images.githubusercontent.com/18707623/55955112-75598c80-5c9b-11e9-82cf-69da1b507487.png)

VS this one 

![image](https://user-images.githubusercontent.com/18707623/55955009-375c6880-5c9b-11e9-9342-585c896efe6a.png)

Formatting by block of code, especially aligning = , makes the code much
faster to read.

**Comment by barni2000** [comment]
Hi @arita37!
Your example does not meet PEP-8. (**PEP-8 is official python style guide**)
Please read this section: https://www.python.org/dev/peps/pep-0008/#id26
Br

**Comment by arita37** [comment]
Ok, there is “official”.
Shouldn’t we re-write the guide ?

Isnt human code lisibility more important than guide ?

My question was not about
if it fits the guide,
but this is better for faster code reading ....?





On Apr 11, 2019, at 23:39, Barnabás Czémán <notifications@github.com> wrote:

Hi @arita37!
Your example does not meet PEP-8. (PEP-8 is official python style guide)
Please read this section: https://www.python.org/dev/peps/pep-0008/#id26
Br

**Comment by barni2000** [comment]
Hi,

It think its not readable and also not writable.

```python3
very_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long = "hello"
short                                                                                                                                                                                                           
                                                                                                                                                                          = "Not readable"
```

**Comment by arita37** [comment]
ok, in case of very long variables,
it can be exception.

Am talking of normal code 
than people write and need to read.








On Apr 12, 2019, at 4:27, Barnabás Czémán <notifications@github.com> wrote:

Hi,

It think its not readable and also not writable.

very_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long_long = "hello"
short                                                                                                                                                                                                           
                                                                                                                                                                          = "Not readable"
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by zsol** [comment]
Please keep the discussion to specific suggestions, otherwise the thread is going to get unfocused quickly.

Having said that, it's unlikely we're going to make significant changes to black's style given its current adoption.

**Comment by arita37** [comment]
my point was about:
grid type formatting of code.
which alloas to catch immediately
design error in the code.

If we consider the code 
to be inserted into a grid,
it would be to identify faster design issues.

The example you show can be handle
as exception , and specific rule can be applied.








On Apr 12, 2019, at 7:06, Zsolt Dollenstein <notifications@github.com> wrote:

Please keep the discussion to specific suggestions, otherwise the thread is going to get unfocused quickly.

Having said that, it's unlikely we're going to make significant changes to black's style given its current adoption.

**Comment by zsol** [comment]
We won't be making such fundamental changes to the style anymore, sorry.
