### ISSUE TITLE
Black playground not working

### ISSUE THREAD

**Issue by AnderUstarroz** [ambv/black#803]
[Black's playground](https://black.now.sh) appears to be currently broken.

**Comment by illfated** [comment]
I wonder; Should it be reported in https://github.com/jpadilla/black-playground/issues or is it caused by changes in Black source (and hence correctly reported here)?

**Comment by AnderUstarroz** [comment]
At the bottom of the [https://black.now.sh](https://black.now.sh) page there was a link "Report issue" that brought me directly here. If the user also have to guess if problem comes from A or B maybe would be a better idea to remove that link as it could be slightly misleading.

**Comment by JelleZijlstra** [comment]
cc @jpadilla. Ideally issues with Black would be reported here and issues with the playground at the link @illfated mentioned.

**Comment by AnderUstarroz** [comment]
closing the issue then

**Comment by jpadilla** [comment]
Thanks for the heads up. I'll update the issue text to try and avoid users from submitting playground issues to this repo.
