### ISSUE TITLE
How long will Black keep formatting Python 2 files?

### ISSUE THREAD

**Issue by fried-sausage** [ambv/black#85]
question, not a bug
https://github.com/python/peps/blob/master/pep-0373.txt
python2 support is to be dropped in 2020.
Does mantainer plan to drop 2.7 altogether at some point? If yes, when will that happen?

I consider using Black in existing projects. In my company we still use 2.7, my rough estimation is we will need at least a year to fully migrate.

**Comment by ambv** [comment]
No, this project will not drop support for *formatting* Python 2.7 files. Not in any foreseeable future and probably never.

Note: to run it, you need Python 3.6 but that's independent.

I hope this helps!
