### ISSUE TITLE
Should black remove unused imports?

### ISSUE THREAD

**Issue by MichalPodeszwa** [ambv/black#86]
I've noticed that right now Black doesn't do that.
I'm wondering whether it's something that Black should take care of?

**Comment by eplaut** [comment]
+1

**Comment by Lukas0907** [comment]
There is already a tool that does that, btw.: https://github.com/myint/autoflake

**Comment by ambv** [comment]
I'm afraid this is scope creep and something that can silently break otherwise valid programs. My intuition is to avoid this in Black.

**Comment by wyuenho** [comment]
Javascript has the same issue and Prettier doesn't seem to have the same qualm in removing unused imports and vars by default. Is there anything special in Python that you can't do with ES modules?

**Comment by ichard26** [comment]
Import has some weird side effects sometimes that would probably be really hard to detect statically. See the example here 
https://github.com/psf/black/issues/333#issuecomment-461803520. The example is a valid program per se, but it depends on an side effect of importing. Even if mod2 doesn't seemed to be used, it **is** needed so the file can access mod.

**Comment by wyuenho** [comment]
I see. I guess `__all__ = [foo, bar]` will also make it hard too, since now you have to chase an entire graph to dereference the values too.

**Comment by hadialqattan** [comment]
> Imports has some weird side effects sometimes that would probably be really hard to detect statically. See the example here
> [#333 (comment)](https://github.com/psf/black/issues/333#issuecomment-461803520). The example is a valid set of instructions per se, but it depends on an side effect of importing. Even if pkg.mod2 doesn't seemed to be used, it **is** needed so the REPL can access pkg.mod which is imported via pkg.mod2.

I agree with you!

BTW, I've developed a tool to do this task safely, If you are interested please check it out!

Docs: https://hadialqattan.github.io/pycln
Repo: https://github.com/hadialqattan/pycln

**(Contributions are always welcome!).**

**Comment by ichard26** [comment]
An example off the top of my head: [readline](https://docs.python.org/3/library/readline.html) is a stdlib module commonly used as simply an import. By importing it, history is enabled for `input()` prompts. 

> [...] it would be really useful.

Yes it would be useful, but I don't believe this is in scope for Black. Black's focus is code style, not code optimization or linting. Other tools can and should handle those; I don't want to be in the business of writing an autofixer for linting issues.

**Comment by Sbrjt** [comment]
For vs code go to settings.json and add:

```
"editor.codeActionsOnSave": {
    "source.organizeImports": "always",
    "source.unusedImports": "always"
},
