### ISSUE TITLE
Support diff output

### ISSUE THREAD

**Issue by brettcannon** [ambv/black#87]
Over on Microsoft/vscode-python#1153 people are asking for support of Black in VS Code. Having diff output from black itself would make this a bit easier for someone to do.

**Comment by ambv** [comment]
Black doesn't support partial reformatting. How does diff output help compared to stdout?

From what I've measured, unless your files are hilariously big, piping everything back is also faster than computing a diff and then applying the patch on the other end.

Not saying no, just need to understand why this is superior to simple stdio piping.

**Comment by brettcannon** [comment]
The diffs lets VS Code, e.g. keep breakpoints working after a reformat.

**Comment by ambv** [comment]
Alright, convinced. Will add this in the next release.
